import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireUserContext } from '@/lib/auth/context';
import { getWorkflowCase } from '@/lib/orchestration/service';
import { acceptQuoteAction, approveCommercialAction, approveIntakeAction, createCommercialReviewAction, createIntakeShellAction, issueQuoteAction, recordQuoteOutcomeAction, reviseQuoteAction } from '../../orchestration/actions';
import { eventLabel, workspaceLabel } from '@/lib/presentation/vocabulary';
import { getCaseDocumentRequirements } from '@/lib/cases/documentRequirements';
import { documentSatisfiesRequirement, resolveActionState, resolveEvidenceState } from '@/lib/workspace/state';
import { toOperatorError } from '@/lib/workspace/operatorErrors';
import RecordWorkspace from '@/components/workspace/RecordWorkspace';
import GovernedAction from '@/components/workspace/GovernedAction';
import DocumentGenerationPanel from '@/components/workspace/documents/DocumentGenerationPanel';
import { getWorkspaceDocument } from '@/components/workspace/documents/documentRegistry';
import MarginSimulator from './MarginSimulator';

const dateTime=(value:string|null|undefined)=>value?new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Not recorded';
const money=(currency:string|null|undefined,amount:number|string|null|undefined)=>amount===null||amount===undefined?'Not recorded':new Intl.NumberFormat('en-GB',{style:'currency',currency:currency||'GBP'}).format(Number(amount));
function Fact({label,value}:{label:string;value:React.ReactNode}){return <div className="vp-fact"><small>{label}</small><strong>{value??'Not recorded'}</strong></div>}

const caseStages=['Technical basis','Partner evidence','Commercial decision','Client quote','Handoff'] as const;

export default async function Case360Page({params,searchParams}:{params:Promise<{id:string}>;searchParams?:Promise<Record<string,string|string[]|undefined>>}){
  const {id}=await params;const query=searchParams?await searchParams:{};const {supabase,organisationId}=await requireUserContext();
  let workflow;try{workflow=await getWorkflowCase(supabase,organisationId,id)}catch{notFound()}
  if(!workflow)notFound();

  const [activityResult,documentsResult,reviewsResult,tasksResult]=await Promise.all([
    supabase.from('activity_events').select('*').eq('organisation_id',organisationId).eq('entity_type','lead').eq('entity_id',id).order('created_at',{ascending:false}).limit(30),
    supabase.from('documents').select('*').eq('organisation_id',organisationId).eq('lead_id',id).order('created_at',{ascending:false}),
    supabase.from('partner_review_requests').select('*, partner:partners(id,company_name,nda_signed), responses:partner_review_responses(*), decisions:partner_review_internal_decisions(*), files:partner_review_files(id)').eq('organisation_id',organisationId).eq('lead_id',id).order('created_at',{ascending:false}),
    supabase.from('tasks').select('*').eq('organisation_id',organisationId).eq('entity_type','lead').eq('entity_id',id).order('created_at',{ascending:false}).limit(12),
  ]);

  const activity=activityResult.data??[];const documents=documentsResult.data??[];const tasks=tasksResult.data??[];
  const review=((reviewsResult.data??[]) as any[])[0] as any|undefined;
  const response=[...(review?.responses??[])].sort((a:any,b:any)=>Number(b.revision)-Number(a.revision))[0];
  const technicalApproved=workflow.technicalIntake?.status==='approved';
  const partnerApproved=['approved','approved_with_conditions'].includes(String(review?.status||''));
  const quote=workflow.clientQuote;
  const quoteDocument=documents.find((document:any)=>document.document_type==='client-quote'&&document.status!=='superseded'&&(!quote?.id||document.quote_id===quote.id));
  const quoteDocumentStatus=String(quoteDocument?.status||'not generated');
  const caseIsHistorical=Boolean(workflow.project);
  const acquisitionHref=workflow.lead.prospect_id?`/workspace/acquisition/${workflow.lead.prospect_id}`:'/workspace/acquisition';

  let currentStatus='Case technical basis',nextAction='Create technical scope',reason='Case 360 formalises the inherited customer and partner evidence before commercial conversion.',actionKey='create_scope',blocker:string|null=null;
  if(workflow.technicalIntake&&!technicalApproved){currentStatus='Technical scope under review';nextAction='Approve technical scope';reason='Approve the inherited customer requirement as a controlled technical basis. Client Requirements evidence must be approved first.';actionKey='approve_scope'}
  if(technicalApproved&&!review){currentStatus='Lifecycle integrity issue';nextAction='Restore inherited partner evidence';reason='Case 360 must inherit the governed Partner Review completed in Acquisition. It must not start a second pre-commercial partner review.';actionKey='integrity_block';blocker='Approved Acquisition Partner Review was not inherited into this Case.'}
  if(review&&!partnerApproved){currentStatus='Lifecycle integrity issue';nextAction='Resolve Acquisition partner decision';reason='Only a concluded approved Acquisition Partner Review belongs in the commercial Case workflow.';actionKey='integrity_block';blocker=`Inherited Partner Review is ${String(review.status||'incomplete').replaceAll('_',' ')} rather than approved.`}
  if(partnerApproved&&!workflow.partnerQuote){currentStatus='Lifecycle integrity issue';nextAction='Restore inherited partner pricing';reason='The approved Acquisition Partner Review must bring its positive governed Partner price into Case 360.';actionKey='integrity_block';blocker='Approved Partner Review exists but governed Partner pricing is missing.'}
  if(partnerApproved&&workflow.partnerQuote&&!workflow.commercialReview){currentStatus='Controlled partner basis';nextAction='Set commercial position';reason='The partner was already selected and priced in Acquisition. Approve the Scope of Work and Partner Technical Assessment, then set the Overflow Partner margin.';actionKey='create_commercial'}
  if(workflow.commercialReview&&!quote){currentStatus='Commercial position ready';nextAction='Generate client quote';reason='The governed cost, selling price and margin can now become one canonical controlled Client Quote.';actionKey='generate_quote'}
  if(quote&&['draft','internal_review'].includes(quote.status)){const quotationApproved=documentSatisfiesRequirement(quoteDocumentStatus,'approved');currentStatus='Draft client quotation';nextAction=quotationApproved?'Issue client quote':'Complete controlled quotation';reason=quotationApproved?'The canonical controlled quotation satisfies the approval gate and may now be commercially issued.':`Commercial issue is blocked until the controlled Client Quote is approved. Current document state: ${quoteDocumentStatus}.`;actionKey='issue_quote';blocker=quotationApproved?null:'Controlled Client Quote approval required.'}
  if(quote?.status==='issued'&&!workflow.project){currentStatus='Awaiting client decision';nextAction='Record written client acceptance';reason='Project 360 can be created only from an issued quotation plus identifiable written acceptance evidence.';actionKey='accept_quote';blocker=null}
  if(quote&&['rejected','expired','withdrawn'].includes(quote.status)&&!workflow.project){currentStatus=`Quote ${quote.status}`;nextAction='Open quote revision';reason='The concluded quotation may be revised through a new controlled publication.';actionKey='revise_quote';blocker=null}
  if(workflow.project){currentStatus='Case handed off';nextAction='Open active project';reason='This Case is historical. The accepted work is now owned by Project 360 and all new delivery evidence must be created there.';actionKey='open_project';blocker=null}

  const documentConfig=caseIsHistorical
    ? {stageLabel:'Case handoff · Historical evidence',items:[]}
    : getCaseDocumentRequirements({
        hasIntake:Boolean(workflow.technicalIntake),scopeApproved:technicalApproved,hasReview:Boolean(review),partnerResponseReady:Boolean(review&&response&&partnerApproved),commercialApproved:workflow.commercialReview?.status==='approved',quoteStatus:quote?.status,
      });
  const requiredRequirements=caseIsHistorical?[]:documentConfig.items.filter(item=>item.requiredNow).map(item=>({key:item.slug,label:getWorkspaceDocument(item.slug)?.title||item.slug.replaceAll('-',' '),requiredStatus:item.minimumStatus,aliases:[item.slug,getWorkspaceDocument(item.slug)?.title||''],description:item.reason}));
  const resolvedEvidence=caseIsHistorical?[]:resolveEvidenceState(documents,requiredRequirements);
  const evidenceBlockers=caseIsHistorical?[]:resolvedEvidence.filter(item=>item.blocking).map(item=>`${item.label}: ${item.operatorState}`);
  const integrityBlocked=actionKey==='integrity_block';
  const actionState=resolveActionState({label:nextAction,businessReady:caseIsHistorical||(!blocker&&!integrityBlocked&&evidenceBlockers.length===0),blockers:caseIsHistorical?[]:[...(blocker?[blocker]:[]),...evidenceBlockers],readyMessage:reason});

  const caseReference=review?.case_reference||workflow.lead.reference||`OP-CASE-${workflow.lead.id.slice(0,8).toUpperCase()}`;
  const success=query.success;
  const stageIndex=workflow.project?4:quote?3:workflow.commercialReview?2:partnerApproved?1:0;
  const owner=workflow.project?'Historical Case · Project 360 owns delivery':review?.partner?.company_name?`Inherited Execution Partner · ${review.partner.company_name}`:'Internal owner';
  const operatorError=query.error?toOperatorError(query.error):null;
  const displayOperatorError=caseIsHistorical&&String(query.error||'').includes('Case is historical')?null:operatorError;

  const notices=<>{success?<div className="vp-callout"><strong>{String(success)}</strong><p>Current status: {currentStatus}. Next: {nextAction}.</p></div>:null}{displayOperatorError?<div className="vp-callout"><strong>{displayOperatorError.title}</strong><p>{displayOperatorError.message}</p></div>:null}</>;

  const header=<div style={{display:'flex',justifyContent:'space-between',gap:24,width:'100%',alignItems:'flex-start',flexWrap:'wrap'}}><div><Link href="/workspace/leads">← Back to cases</Link><p className="vp-kicker">Case 360 · {caseReference}</p><h1>{workflow.lead.title||workflow.lead.company_name}</h1><p className="vp-subtitle">{workflow.lead.company_name}{workflow.lead.contact_name?` · ${workflow.lead.contact_name}`:''}</p><div className="project-os-meta"><span>Current state · {currentStatus}</span><span>{owner}</span></div></div><span className="vp-status">{currentStatus}</span></div>;

  const stateStrip=<div><div style={{display:'grid',gridTemplateColumns:`repeat(${caseStages.length},minmax(0,1fr))`,gap:8}}>{caseStages.map((label,index)=><div key={label} style={{padding:'10px 12px',borderTop:`2px solid ${index===stageIndex?'var(--op-accent)':index<stageIndex?'rgba(255,255,255,.38)':'var(--op-line)'}`,opacity:index>stageIndex?.55:1}}><small style={{display:'block',color:'var(--op-muted)'}}>{index<stageIndex?'Complete':index===stageIndex?(caseIsHistorical?'Handed off':'Current'):'Future'}</small><strong>{label}</strong></div>)}</div><p style={{margin:'14px 0 0',color:'var(--op-muted)'}}>{reason}</p></div>;

  const readiness=<div>{caseIsHistorical?<div className="vp-callout"><strong>Case complete · delivery handed off</strong><p>No further progression occurs in Case 360. Project 360 is the sole operational owner.</p></div>:integrityBlocked?<div className="vp-callout"><strong>Lifecycle integrity requires attention</strong><p>{blocker}</p><p>Do not create replacement Partner Review evidence in Case 360. Resolve the Acquisition record or inherited linkage.</p></div>:actionState.permitted?<div className="vp-callout"><strong>Ready for current decision</strong><p>{reason}</p></div>:<div className="vp-callout"><strong>Progression blocked</strong><p>{actionState.message}</p>{evidenceBlockers.length?<p>{evidenceBlockers.length} controlled evidence requirement{evidenceBlockers.length===1?'':'s'} remain unresolved.</p>:null}</div>}<div className="vp-facts" style={{marginTop:14}}><Fact label="Technical scope" value={workflow.technicalIntake?workspaceLabel(workflow.technicalIntake.status,'technicalIntake'):'Not created'}/><Fact label="Inherited partner evidence" value={review?workspaceLabel(review.status,'partnerReview'):'Missing'}/><Fact label="Partner pricing" value={workflow.partnerQuote?money(workflow.partnerQuote.currency,workflow.partnerQuote.price):'Missing'}/><Fact label="Commercial review" value={workflow.commercialReview?'Recorded':'Not recorded'}/><Fact label="Quote evidence" value={quote?workspaceLabel(quoteDocumentStatus,'document'):'Not required yet'}/></div></div>;

  const actionControls=<>
    {actionKey==='create_scope'?<form action={createIntakeShellAction}><input type="hidden" name="lead_id" value={id}/><button className="button">Create technical scope</button></form>:null}
    {actionKey==='approve_scope'?<form action={approveIntakeAction}><input type="hidden" name="lead_id" value={id}/><input type="hidden" name="intake_id" value={workflow.technicalIntake?.id}/><button className="button">Approve technical scope</button></form>:null}
    {actionKey==='create_commercial'?<form action={createCommercialReviewAction} className="stack"><input type="hidden" name="lead_id" value={id}/><input type="hidden" name="partner_quote_id" value={workflow.partnerQuote?.id}/><MarginSimulator cost={Number(workflow.partnerQuote?.price||0)} currency={workflow.partnerQuote?.currency||'GBP'}/><label>Optional commercial note<textarea name="commercial_note" rows={3}/></label><button className="button">Set commercial position</button></form>:null}
    {actionKey==='generate_quote'?<form action={approveCommercialAction}><input type="hidden" name="lead_id" value={id}/><input type="hidden" name="commercial_review_id" value={workflow.commercialReview?.id}/><button className="button">Approve position and generate Client Quote</button></form>:null}
    {actionKey==='issue_quote'?<form action={issueQuoteAction}><input type="hidden" name="lead_id" value={id}/><input type="hidden" name="quote_id" value={quote?.id}/><button className="button">Issue client quote</button></form>:null}
    {actionKey==='accept_quote'?<div className="stack"><form action={acceptQuoteAction} className="stack"><input type="hidden" name="lead_id" value={id}/><input type="hidden" name="quote_id" value={quote?.id}/><div className="vp-callout"><strong>Written acceptance evidence required</strong><p>Record the evidence you are relying on. The reference may be a PO number, signed quotation reference, email subject/date, or portal confirmation.</p></div><label>Acceptance basis<select name="acceptance_basis" required defaultValue=""><option value="" disabled>Select evidence type</option><option value="signed_quote">Signed quotation</option><option value="purchase_order">Purchase order</option><option value="email_confirmation">Email confirmation</option><option value="client_portal">Client portal acceptance</option><option value="other_written">Other written acceptance</option></select></label><label>Evidence reference<input name="evidence_reference" required placeholder="PO number, signed quote ref, or email subject/date"/></label><div className="grid gap-4 md:grid-cols-2"><label>Accepted by<input name="accepted_by_name" required defaultValue={workflow.lead.contact_name||''}/></label><label>Client email<input name="accepted_by_email" type="email" defaultValue={workflow.lead.contact_email||''}/></label></div><label>Acceptance note<textarea name="acceptance_notes" rows={3} placeholder="Optional context or acceptance conditions"/></label><button className="button">Record acceptance and create Project 360</button></form><details className="vp-disclosure"><summary>Other client outcome</summary><form action={recordQuoteOutcomeAction} className="stack"><input type="hidden" name="lead_id" value={id}/><input type="hidden" name="quote_id" value={quote?.id}/><label>Outcome<select name="outcome" required defaultValue="rejected"><option value="rejected">Rejected</option><option value="expired">Expired</option><option value="withdrawn">Withdrawn</option></select></label><label>Decision note<textarea name="note" rows={3}/></label><button className="button secondary">Record outcome</button></form></details></div>:null}
    {actionKey==='revise_quote'?<form action={reviseQuoteAction} className="stack"><input type="hidden" name="lead_id" value={id}/><input type="hidden" name="quote_id" value={quote?.id}/><label>Revision reason<textarea name="note" rows={3} required/></label><button className="button">Open new controlled revision</button></form>:null}
    {actionKey==='open_project'?<Link className="button" href={`/workspace/projects/${workflow.project?.id}`}>Open active project</Link>:null}
  </>;

  const blockedAction=integrityBlocked?<Link className="button secondary" href={acquisitionHref}>Open Acquisition evidence →</Link>:<a className="button secondary" href="#record-controlled-evidence">Resolve controlled evidence ↓</a>;
  const nextActionPanel=caseIsHistorical?<div><p className="vp-label">Handoff complete</p><h2>Open active project</h2><p>The Case is retained as historical commercial evidence. Mobilisation, execution and new controlled documents now belong to Project 360.</p><Link className="button" href={`/workspace/projects/${workflow.project?.id}`}>Open active project</Link></div>:integrityBlocked?<div><p className="vp-label">Lifecycle integrity</p><h2>{nextAction}</h2><p>{reason}</p>{blockedAction}</div>:<GovernedAction state={actionState} blockedAction={blockedAction}>{actionControls}</GovernedAction>;

  const summary=<div className="vp-facts"><Fact label="Customer" value={workflow.lead.company_name}/><Fact label="Contact" value={workflow.lead.contact_name}/><Fact label="Project type" value={workflow.technicalIntake?.project_type||workflow.lead.project_type}/><Fact label="Discipline" value={workflow.technicalIntake?.discipline}/><Fact label="Deadline" value={workflow.technicalIntake?.deadline}/><Fact label="Documents" value={documents.length}/>{quote?<><Fact label="Quote" value={quote.quote_number}/><Fact label="Total" value={money(quote.currency,quote.total)}/></>:null}</div>;

  const evidence=caseIsHistorical?<div style={{display:'grid',gap:14}}><div className="vp-callout"><strong>Historical Case evidence</strong><p>This evidence is locked to the completed Case. New Statements of Work, mobilisation packs and delivery documents must be created in Project 360.</p><Link className="button" href={`/workspace/projects/${workflow.project?.id}`}>Continue in Project 360</Link></div><div className="project-os-document-list">{documents.filter((document:any)=>document.status!=='superseded').slice(0,12).map((document:any)=><div className="project-os-document-row" key={document.id}><div><strong>{document.title}</strong><small>{document.reference}</small></div><span className="project-os-tag">{workspaceLabel(document.status,'document')}</span></div>)}</div></div>:<div style={{display:'grid',gap:14}}><DocumentGenerationPanel context="case" recordId={id} quoteId={quote?.id} returnTo={`/workspace/leads/${id}`} stageLabel={documentConfig.stageLabel} items={documentConfig.items}/><details className="vp-disclosure"><summary>Underlying customer technical evidence</summary><div className="vp-facts"><Fact label="Scope" value={workflow.technicalIntake?.description||workflow.lead.notes}/><Fact label="Deliverables" value={workflow.technicalIntake?.deliverables||workflow.lead.service}/><Fact label="Technical status" value={workflow.technicalIntake?workspaceLabel(workflow.technicalIntake.status,'technicalIntake'):'Not created'}/></div></details>{response?<details className="vp-disclosure"><summary>Inherited Partner evidence · Revision {response.revision}</summary><div className="vp-facts"><Fact label="Execution Partner" value={review?.partner?.company_name}/><Fact label="Feasibility" value={workspaceLabel(response.feasibility,'feasibility')}/><Fact label="Confidence" value={`${response.confidence_percent}%`}/><Fact label="Capacity" value={workspaceLabel(response.capacity_status,'capacity')}/><Fact label="Hours" value={response.estimated_engineering_hours}/><Fact label="Lead time" value={response.estimated_lead_time_days?`${response.estimated_lead_time_days} days`:'Not recorded'}/>{workflow.partnerQuote?<Fact label="Partner price" value={money(workflow.partnerQuote.currency,workflow.partnerQuote.price)}/>:null}</div></details>:null}</div>;

  const activities=<div>{tasks.length===0?<p style={{color:'var(--op-muted)'}}>{caseIsHistorical?'No Case actions remain open. Delivery work belongs to Project 360.':'No separate Case activities are currently open.'}</p>:<div className="project-os-activity-list">{tasks.map((task:any)=><div key={task.id}><div><strong>{task.title}</strong><small>{workspaceLabel(task.status,'task')} · {task.priority||'normal'}</small></div></div>)}</div>}</div>;
  const communications=<div><p style={{color:'var(--op-muted)',lineHeight:1.6}}>{caseIsHistorical?'Case communications remain available as historical context. New delivery correspondence belongs to Project 360.':'Customer and inherited Partner communication stays attached to this Case without reopening Acquisition decisions.'}</p><Link className="button secondary" href={`/workspace/communications/lead/${id}`}>Open case communications</Link></div>;
  const history=<div>{activity.length===0?<p>No case events recorded.</p>:activity.slice(0,12).map((event:any)=><div className="project-os-history-row" key={event.id}><span>→</span><div><strong>{eventLabel(event.event_type)}</strong><small>{dateTime(event.created_at)}</small></div></div>)}</div>;
  const olderDocuments=documents.length>6?<div className="project-os-document-list">{documents.slice(6,14).map((document:any)=><div className="project-os-document-row" key={document.id}><div><strong>{document.title}</strong><small>{document.reference}</small></div><span className="project-os-tag">{workspaceLabel(document.status,'document')}</span></div>)}</div>:<p>No older evidence outside the current-stage document set.</p>;
  const metadata=<div className="vp-facts"><Fact label="Case reference" value={caseReference}/><Fact label="Lead ID" value={workflow.lead.id}/><Fact label="Created" value={dateTime(workflow.lead.created_at)}/><Fact label="Lead status" value={workspaceLabel(workflow.lead.status,'lead')}/>{workflow.project?<Fact label="Active Project" value={workflow.project.id}/>:null}</div>;
  const audit=<div><p style={{color:'var(--op-muted)',lineHeight:1.6}}>{activity.length} recent governed events are attached to this Case. Acquisition Partner evidence is inherited; commercial and document decisions remain auditable without duplicating the Partner Review.</p><Link href={`/workspace/documents?lead=${id}`}>Open controlled evidence →</Link></div>;

  return <RecordWorkspace header={header} notices={notices} stateStrip={stateStrip} readiness={readiness} nextAction={nextActionPanel} summary={summary} evidence={evidence} activities={activities} communications={communications} history={history} olderDocuments={olderDocuments} metadata={metadata} audit={audit}/>;
}
