import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireUserContext } from '@/lib/auth/context';
import { getWorkflowCase } from '@/lib/orchestration/service';
import { acceptQuoteAction, approveCommercialAction, approveIntakeAction, createCommercialReviewAction, createIntakeShellAction, issueQuoteAction, recordQuoteOutcomeAction, reviseQuoteAction } from '../../orchestration/actions';
import { eventLabel, workspaceLabel } from '@/lib/presentation/vocabulary';
import { resolveCasePresentation } from '@/lib/presentation/operatingState';
import { getCaseDocumentRequirements } from '@/lib/cases/documentRequirements';
import { documentSatisfiesRequirement, resolveActionState, resolveEvidenceState } from '@/lib/workspace/state';
import { toOperatorError } from '@/lib/workspace/operatorErrors';
import RecordWorkspace from '@/components/workspace/RecordWorkspace';
import GovernedAction from '@/components/workspace/GovernedAction';
import DocumentGenerationPanel from '@/components/workspace/documents/DocumentGenerationPanel';
import { getWorkspaceDocument } from '@/components/workspace/documents/documentRegistry';
import MarginSimulator from './MarginSimulator';

const dateTime=(value:string|null|undefined)=>value?new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Not recorded';
const money=(currency:string|null|undefined,amount:number|string|null|undefined)=>amount===null||amount===undefined?'Not recorded':new Intl.NumberFormat('en-GB',{style:'currency',currency:currency||'GBP'}).format(Number(amount));
function Fact({label,value}:{label:string;value:React.ReactNode}){return <div className="vp-fact"><small>{label}</small><strong>{value??'Not recorded'}</strong></div>}

const caseStages=['Technical scope','Partner assessment','Commercial position','Client Quote','Handoff'] as const;

export default async function Case360Page({params,searchParams}:{params:Promise<{id:string}>;searchParams?:Promise<Record<string,string|string[]|undefined>>}){
  const {id}=await params;const query=searchParams?await searchParams:{};const {supabase,organisationId}=await requireUserContext();
  let workflow;try{workflow=await getWorkflowCase(supabase,organisationId,id)}catch{notFound()}
  if(!workflow)notFound();

  const [activityResult,documentsResult,reviewsResult,tasksResult]=await Promise.all([
    supabase.from('activity_events').select('*').eq('organisation_id',organisationId).eq('entity_type','lead').eq('entity_id',id).order('created_at',{ascending:false}).limit(30),
    supabase.from('documents').select('*').eq('organisation_id',organisationId).eq('lead_id',id).order('created_at',{ascending:false}),
    supabase.from('partner_review_requests').select('*, partner:partners(id,company_name,nda_signed), responses:partner_review_responses(*), decisions:partner_review_internal_decisions(*), files:partner_review_files(id)').eq('organisation_id',organisationId).eq('lead_id',id).order('created_at',{ascending:false}),
    supabase.from('tasks').select('*').eq('organisation_id',organisationId).eq('entity_type','lead').eq('entity_id',id).order('created_at',{ascending:false}).limit(12),
  ]);

  const activity=activityResult.data??[];const documents=documentsResult.data??[];const tasks=tasksResult.data??[];
  const review=((reviewsResult.data??[]) as any[])[0] as any|undefined;
  const response=[...(review?.responses??[])].sort((a:any,b:any)=>Number(b.revision)-Number(a.revision))[0];
  const technicalApproved=workflow.technicalIntake?.status==='approved';
  const partnerApproved=['approved','approved_with_conditions'].includes(String(review?.status||''));
  const quote=workflow.clientQuote;
  const quoteDocument=documents.find((document:any)=>document.document_type==='client-quote'&&document.status!=='superseded'&&(!quote?.id||document.quote_id===quote.id));
  const quoteDocumentStatus=String(quoteDocument?.status||'not generated');
  const caseIsHistorical=Boolean(workflow.project);
  const acquisitionHref=workflow.lead.prospect_id?`/workspace/acquisition/${workflow.lead.prospect_id}`:'/workspace/acquisition';

  let currentStatus='Technical scope needed',nextAction='Create technical scope',reason='Bring the agreed client requirement into Case 360 so the commercial work can begin.',actionKey='create_scope',blocker:string|null=null;
  if(workflow.technicalIntake&&!technicalApproved){currentStatus='Technical scope under review';nextAction='Approve technical scope';reason='Approve the inherited client requirement before setting the commercial position.';actionKey='approve_scope'}
  if(technicalApproved&&!review){currentStatus='Partner evidence needs attention';nextAction='Fix missing Partner assessment';reason='The approved Partner Assessment from Acquisition is missing from this Case.';actionKey='integrity_block';blocker='Approved Partner Assessment is missing from this Case.'}
  if(review&&!partnerApproved){currentStatus='Partner evidence needs attention';nextAction='Resolve Partner assessment';reason='The Partner Assessment must be concluded in Acquisition before this Case can continue.';actionKey='integrity_block';blocker=`Partner Assessment is ${String(review.status||'incomplete').replaceAll('_',' ')} rather than approved.`}
  if(partnerApproved&&!workflow.partnerQuote){currentStatus='Partner evidence needs attention';nextAction='Fix missing Partner price';reason='The approved Partner Assessment is present, but its price is missing from this Case.';actionKey='integrity_block';blocker='Approved Partner Assessment is missing its Partner price.'}
  if(partnerApproved&&workflow.partnerQuote&&!workflow.commercialReview){currentStatus='Partner price ready';nextAction='Set commercial position';reason='The Partner is selected and priced. Confirm the technical scope, then set the Overflow Partner margin.';actionKey='create_commercial'}
  if(workflow.commercialReview&&!quote){currentStatus='Commercial position ready';nextAction='Generate Client Quote';reason='The cost, selling price and margin are ready to become the Client Quote.';actionKey='generate_quote'}
  if(quote&&['draft','internal_review'].includes(quote.status)){const quotationApproved=documentSatisfiesRequirement(quoteDocumentStatus,'approved');currentStatus='Draft Client Quote';nextAction=quotationApproved?'Record Client Quote sent':'Approve Client Quote';reason=quotationApproved?'The Client Quote is approved. Record who received it and how it was sent.':`Approve the Client Quote before sending it. Current document state: ${quoteDocumentStatus}.`;actionKey='issue_quote';blocker=quotationApproved?null:'Client Quote approval required.'}
  if(quote?.status==='issued'&&!workflow.project){currentStatus='Awaiting client decision';nextAction='Record client acceptance';reason='Project 360 can be created once written client acceptance is recorded against the issued quote.';actionKey='accept_quote';blocker=null}
  if(quote&&['rejected','expired','withdrawn'].includes(quote.status)&&!workflow.project){currentStatus=`Quote ${quote.status}`;nextAction='Create quote revision';reason='Create a new quote revision if the client wants a revised offer.';actionKey='revise_quote';blocker=null}
  if(workflow.project){currentStatus='Case handed off';nextAction='Open active project';reason='This Case is complete. Delivery now belongs to Project 360.';actionKey='open_project';blocker=null}

  const documentConfig=caseIsHistorical
    ? {stageLabel:'Case handoff · Historical evidence',items:[]}
    : getCaseDocumentRequirements({hasIntake:Boolean(workflow.technicalIntake),scopeApproved:technicalApproved,hasReview:Boolean(review),partnerResponseReady:Boolean(review&&response&&partnerApproved),commercialApproved:workflow.commercialReview?.status==='approved',quoteStatus:quote?.status});
  const requiredRequirements=caseIsHistorical?[]:documentConfig.items.filter(item=>item.requiredNow).map(item=>({key:item.slug,label:getWorkspaceDocument(item.slug)?.title||item.slug.replaceAll('-',' '),requiredStatus:item.minimumStatus,aliases:[item.slug,getWorkspaceDocument(item.slug)?.title||''],description:item.reason}));
  const resolvedEvidence=caseIsHistorical?[]:resolveEvidenceState(documents,requiredRequirements);const evidenceBlockers=caseIsHistorical?[]:resolvedEvidence.filter(item=>item.blocking).map(item=>`${item.label}: ${item.operatorState}`);
  const integrityBlocked=actionKey==='integrity_block';
  const presentation=resolveCasePresentation({currentState:currentStatus,nextAction,reason,actionKey,blocker,evidenceBlockers,historical:caseIsHistorical});
  const actionState=resolveActionState({label:presentation.nextAction.label,businessReady:caseIsHistorical||(!blocker&&!integrityBlocked&&evidenceBlockers.length===0),blockers:caseIsHistorical?[]:[...(blocker?[blocker]:[]),...evidenceBlockers],readyMessage:presentation.summary});

  const caseReference=review?.case_reference||workflow.lead.reference||`OP-CASE-${workflow.lead.id.slice(0,8).toUpperCase()}`;const success=query.success;const stageIndex=workflow.project?4:quote?3:workflow.commercialReview?2:partnerApproved?1:0;
  const contextLabel=workflow.project?'Project 360 owns delivery':review?.partner?.company_name?`Partner · ${review.partner.company_name}`:'Overflow Partner';
  const operatorError=query.error?toOperatorError(query.error):null;const displayOperatorError=caseIsHistorical&&String(query.error||'').includes('Case is historical')?null:operatorError;

  const notices=<>{success?<div className="vp-callout"><strong>{String(success)}</strong><p>{presentation.state} · {presentation.nextAction.label}.</p></div>:null}{displayOperatorError?<div className="vp-callout"><strong>{displayOperatorError.title}</strong><p>{displayOperatorError.message}</p></div>:null}</>;
  const header=<div style={{display:'flex',justifyContent:'space-between',gap:24,width:'100%',alignItems:'flex-start',flexWrap:'wrap'}}><div><Link href="/workspace/leads">← Back to cases</Link><p className="vp-kicker">Case 360 · {caseReference}</p><h1>{workflow.lead.title||workflow.lead.company_name}</h1><p className="vp-subtitle">{workflow.lead.company_name}{workflow.lead.contact_name?` · ${workflow.lead.contact_name}`:''}</p><div className="project-os-meta"><span>{contextLabel}</span>{presentation.waitingOn?<span>Waiting on · {presentation.waitingOn.label}</span>:null}</div></div><span className="vp-status">{presentation.state}</span></div>;
  const stateStrip=<div><div className="case360-stage-strip">{caseStages.map((label,index)=><div className="case360-stage-step" key={label} style={{borderTop:`2px solid ${index===stageIndex?'var(--op-accent)':index<stageIndex?'rgba(255,255,255,.38)':'var(--op-line)'}`,opacity:index>stageIndex?.55:1}}><small style={{display:'block',color:'var(--op-muted)'}}>{index<stageIndex?'Complete':index===stageIndex?(caseIsHistorical?'Handed off':'Current'):'Future'}</small><strong>{label}</strong></div>)}</div><p style={{margin:'14px 0 0',color:'var(--op-muted)'}}>{presentation.summary}</p></div>;

  const readiness=<div>{caseIsHistorical?<div className="vp-callout"><strong>Case complete · delivery handed off</strong><p>No further work happens in Case 360. Continue in Project 360.</p></div>:integrityBlocked?<div className="vp-callout"><strong>Partner evidence needs attention</strong><p>{blocker}</p><p>Fix the Acquisition record or missing link before continuing.</p></div>:actionState.permitted?<div className="vp-callout"><strong>Ready for current decision</strong><p>{presentation.summary}</p></div>:<div className="vp-callout"><strong>Not ready yet</strong><p>{actionState.message}</p>{evidenceBlockers.length?<p>{evidenceBlockers.length} document requirement{evidenceBlockers.length===1?'':'s'} remain unresolved.</p>:null}</div>}<div className="vp-facts" style={{marginTop:14}}><Fact label="Technical scope" value={workflow.technicalIntake?workspaceLabel(workflow.technicalIntake.status,'technicalIntake'):'Not created'}/><Fact label="Partner assessment" value={review?workspaceLabel(review.status,'partnerReview'):'Missing'}/><Fact label="Partner price" value={workflow.partnerQuote?money(workflow.partnerQuote.currency,workflow.partnerQuote.price):'Missing'}/><Fact label="Commercial position" value={workflow.commercialReview?'Recorded':'Not recorded'}/>{quote?<Fact label="Client Quote" value={workspaceLabel(quoteDocumentStatus,'document')}/>:null}</div></div>;

  const actionControls=<>
    {actionKey==='create_scope'?<form action={createIntakeShellAction}><input type="hidden" name="lead_id" value={id}/><button className="button">Create technical scope</button></form>:null}
    {actionKey==='approve_scope'?<form action={approveIntakeAction}><input type="hidden" name="lead_id" value={id}/><input type="hidden" name="intake_id" value={workflow.technicalIntake?.id}/><button className="button">Approve technical scope</button></form>:null}
    {actionKey==='create_commercial'?<form action={createCommercialReviewAction} className="stack"><input type="hidden" name="lead_id" value={id}/><input type="hidden" name="partner_quote_id" value={workflow.partnerQuote?.id}/><MarginSimulator cost={Number(workflow.partnerQuote?.price||0)} currency={workflow.partnerQuote?.currency||'GBP'}/><label>Optional commercial note<textarea name="commercial_note" rows={3}/></label><button className="button">Set commercial position</button></form>:null}
    {actionKey==='generate_quote'?<form action={approveCommercialAction}><input type="hidden" name="lead_id" value={id}/><input type="hidden" name="commercial_review_id" value={workflow.commercialReview?.id}/><button className="button">Approve position and generate Client Quote</button></form>:null}
    {actionKey==='issue_quote'?<form action={issueQuoteAction} className="stack"><input type="hidden" name="lead_id" value={id}/><input type="hidden" name="quote_id" value={quote?.id}/><div className="vp-callout"><strong>Client Quote delivery</strong><p>Record who received the approved Client Quote and how it was sent.</p></div><div className="grid gap-4 md:grid-cols-2"><label>Recipient name<input name="recipient_name" required defaultValue={workflow.lead.contact_name||''}/></label><label>Recipient email<input name="recipient_email" type="email" defaultValue={workflow.lead.contact_email||''}/></label></div><label>Delivery method<select name="delivery_method" required defaultValue="external_email"><option value="external_email">Email with Client Quote</option><option value="secure_link">Secure link</option><option value="client_portal">Client portal</option><option value="other">Other method</option></select></label><label>Delivery evidence<input name="issue_evidence_reference" required placeholder="Email subject/date, secure-link record, portal reference..."/></label><label>Delivery note<textarea name="issue_note" rows={3}/></label><button className="button">Record Client Quote sent</button></form>:null}
    {actionKey==='accept_quote'?<div className="stack"><form action={acceptQuoteAction} className="stack"><input type="hidden" name="lead_id" value={id}/><input type="hidden" name="quote_id" value={quote?.id}/><div className="vp-callout"><strong>Written acceptance required</strong><p>Record the written evidence you are relying on: PO, signed quotation, email or portal confirmation.</p></div><label>Acceptance basis<select name="acceptance_basis" required defaultValue=""><option value="" disabled>Select evidence type</option><option value="signed_quote">Signed quotation</option><option value="purchase_order">Purchase order</option><option value="email_confirmation">Email confirmation</option><option value="client_portal">Client portal acceptance</option><option value="other_written">Other written acceptance</option></select></label><label>Evidence reference<input name="evidence_reference" required placeholder="PO number, signed quote ref, or email subject/date"/></label><div className="grid gap-4 md:grid-cols-2"><label>Accepted by<input name="accepted_by_name" required defaultValue={workflow.lead.contact_name||''}/></label><label>Client email<input name="accepted_by_email" type="email" defaultValue={workflow.lead.contact_email||''}/></label></div><label>Acceptance note<textarea name="acceptance_notes" rows={3} placeholder="Optional context or acceptance conditions"/></label><button className="button">Record acceptance and create Project 360</button></form><details className="vp-disclosure"><summary>Other client outcome</summary><form action={recordQuoteOutcomeAction} className="stack"><input type="hidden" name="lead_id" value={id}/><input type="hidden" name="quote_id" value={quote?.id}/><label>Outcome<select name="outcome" required defaultValue="rejected"><option value="rejected">Rejected</option><option value="expired">Expired</option><option value="withdrawn">Withdrawn</option></select></label><label>Decision note<textarea name="note" rows={3}/></label><button className="button secondary">Record outcome</button></form></details></div>:null}
    {actionKey==='revise_quote'?<form action={reviseQuoteAction} className="stack"><input type="hidden" name="lead_id" value={id}/><input type="hidden" name="quote_id" value={quote?.id}/><label>Revision reason<textarea name="note" rows={3} required/></label><button className="button">Create new quote revision</button></form>:null}
    {actionKey==='open_project'?<Link className="button" href={`/workspace/projects/${workflow.project?.id}`}>Open active project</Link>:null}
  </>;

  const blockedAction=integrityBlocked?<Link className="button secondary" href={acquisitionHref}>Open Acquisition →</Link>:<a className="button secondary" href="#record-controlled-evidence">Resolve document requirements ↓</a>;
  const nextActionPanel=caseIsHistorical?<div><p className="vp-label">Handoff complete</p><h2>Open active project</h2><p>The Case remains available as commercial history. Mobilisation, execution and new documents now belong to Project 360.</p><Link className="button" href={`/workspace/projects/${workflow.project?.id}`}>Open active project</Link></div>:integrityBlocked?<div><p className="vp-label">Partner evidence</p><h2>{presentation.nextAction.label}</h2><p>{presentation.summary}</p>{blockedAction}</div>:<GovernedAction state={actionState} blockedAction={blockedAction}>{actionControls}</GovernedAction>;

  const summary=<div className="vp-facts"><Fact label="Client" value={workflow.lead.company_name}/><Fact label="Contact" value={workflow.lead.contact_name}/><Fact label="Project type" value={workflow.technicalIntake?.project_type||workflow.lead.project_type}/><Fact label="Discipline" value={workflow.technicalIntake?.discipline}/><Fact label="Deadline" value={workflow.technicalIntake?.deadline}/>{quote?<><Fact label="Quote" value={quote.quote_number}/><Fact label="Total" value={money(quote.currency,quote.total)}/></>:null}</div>;
  const evidence=caseIsHistorical?<div style={{display:'grid',gap:14}}><div className="vp-callout"><strong>Historical Case evidence</strong><p>These documents belong to the completed Case. New mobilisation and delivery documents belong to Project 360.</p><Link className="button" href={`/workspace/projects/${workflow.project?.id}`}>Continue in Project 360</Link></div><div className="project-os-document-list">{documents.filter((document:any)=>document.status!=='superseded').slice(0,12).map((document:any)=><Link className="project-os-document-row" href={`/workspace/documents/templates/${document.document_type}?case=${id}&document_record=${document.id}`} key={document.id}><div><strong>{document.title}</strong><small>{document.reference}</small></div><span className="project-os-tag">{workspaceLabel(document.status,'document')}</span></Link>)}</div></div>:<div style={{display:'grid',gap:14}}><DocumentGenerationPanel context="case" recordId={id} quoteId={quote?.id} returnTo={`/workspace/leads/${id}`} stageLabel={documentConfig.stageLabel} items={documentConfig.items}/><details className="vp-disclosure"><summary>Client technical evidence</summary><div className="vp-facts"><Fact label="Scope" value={workflow.technicalIntake?.description||workflow.lead.notes}/><Fact label="Deliverables" value={workflow.technicalIntake?.deliverables||workflow.lead.service}/><Fact label="Technical status" value={workflow.technicalIntake?workspaceLabel(workflow.technicalIntake.status,'technicalIntake'):'Not created'}/></div></details>{response?<details className="vp-disclosure"><summary>Partner assessment · Revision {response.revision}</summary><div className="vp-facts"><Fact label="Execution Partner" value={review?.partner?.company_name}/><Fact label="Feasibility" value={workspaceLabel(response.feasibility,'feasibility')}/><Fact label="Confidence" value={`${response.confidence_percent}%`}/><Fact label="Capacity" value={workspaceLabel(response.capacity_status,'capacity')}/><Fact label="Hours" value={response.estimated_engineering_hours}/><Fact label="Lead time" value={response.estimated_lead_time_days?`${response.estimated_lead_time_days} days`:'Not recorded'}/>{workflow.partnerQuote?<Fact label="Partner price" value={money(workflow.partnerQuote.currency,workflow.partnerQuote.price)}/>:null}</div></details>:null}</div>;
  const activities=<div>{tasks.length===0?<p style={{color:'var(--op-muted)'}}>{caseIsHistorical?'No Case actions remain open. Delivery work belongs to Project 360.':'No separate Case actions are currently open.'}</p>:<div className="project-os-activity-list">{tasks.map((task:any)=><div key={task.id}><div><strong>{task.title}</strong><small>{workspaceLabel(task.status,'task')} · {task.priority||'normal'}</small></div></div>)}</div>}</div>;
  const communications=<div><p style={{color:'var(--op-muted)',lineHeight:1.6}}>{caseIsHistorical?'Case messages remain available as historical context. New delivery correspondence belongs to Project 360.':'Client and Partner messages stay attached to this Case without reopening Acquisition decisions.'}</p><Link className="button secondary" href={`/workspace/communications/lead/${id}`}>Open Case messages</Link></div>;
  const history=<div>{activity.length===0?<p>No Case events recorded.</p>:activity.slice(0,12).map((event:any)=><div className="project-os-history-row" key={event.id}><span>→</span><div><strong>{eventLabel(event.event_type)}</strong><small>{dateTime(event.created_at)}</small></div></div>)}</div>;
  const olderDocuments=documents.length>6?<div className="project-os-document-list">{documents.slice(6,14).map((document:any)=><Link className="project-os-document-row" href={`/workspace/documents/templates/${document.document_type}?case=${id}&document_record=${document.id}`} key={document.id}><div><strong>{document.title}</strong><small>{document.reference}</small></div><span className="project-os-tag">{workspaceLabel(document.status,'document')}</span></Link>)}</div>:<p>No older evidence outside the current-stage document set.</p>;
  const metadata=<div className="vp-facts"><Fact label="Case reference" value={caseReference}/><Fact label="Case ID" value={workflow.lead.id}/><Fact label="Created" value={dateTime(workflow.lead.created_at)}/><Fact label="Case status" value={workspaceLabel(workflow.lead.status,'lead')}/>{workflow.project?<Fact label="Active Project" value={workflow.project.id}/>:null}</div>;
  const audit=<div><p style={{color:'var(--op-muted)',lineHeight:1.6}}>{activity.length} recent events are attached to this Case. Partner evidence is inherited from Acquisition; commercial and document decisions remain traceable here.</p><Link href={`/workspace/documents?lead=${id}`}>Open document registry →</Link></div>;

  return <RecordWorkspace header={header} notices={notices} stateStrip={stateStrip} presentation={presentation} readiness={readiness} nextAction={nextActionPanel} summary={summary} evidence={evidence} activities={activities} communications={communications} history={history} olderDocuments={olderDocuments} metadata={metadata} audit={audit}/>;
}
