'use client';

import { FormEvent, ReactNode, useCallback, useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import PartnerDeliveryFiles from '@/components/execution/PartnerDeliveryFiles';
import { BusinessActivityTimeline } from '@/components/workspace/OperationalObjects';

type ExecutionState={execution?:{execution_state:string;execution_cycle?:number;committed_due_date?:string|null;reporting_cadence?:string;release_notes?:string|null};project?:{project_number:string;title:string;due_date?:string|null;project_stage:string};partner?:{company_name:string;contact_name?:string|null};controlled_scope?:{title:string;reference:string;revision_code?:string|null;status:string}|null;commencement?:Record<string,any>|null;progress_updates?:Array<Record<string,any>>;exceptions?:Array<Record<string,any>>;delivery_submissions?:Array<Record<string,any>>;message?:string};
type Action='start'|'progress'|'issue'|'submit'|null;
type DeliveryFileState={count:number;locked:boolean;cycle:number};
const input='w-full border border-black/15 bg-white px-3 py-2.5 text-sm outline-none focus:border-black';
const label='grid gap-2 text-[10px] font-semibold uppercase tracking-[0.09em] text-neutral-500';
const button='min-h-10 border border-black/20 px-4 py-2 text-sm font-medium hover:bg-black hover:text-white';
const primary='min-h-10 bg-black px-4 py-2 text-sm font-medium text-white disabled:bg-neutral-400';
function date(value:unknown){if(!value)return 'Not set';const d=new Date(String(value));return Number.isNaN(d.getTime())?String(value):d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});}
function pretty(value:unknown){return String(value||'Not recorded').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());}
function businessMessage(value:unknown){return String(value||'').replace(/commencement declaration/gi,'start confirmation').replace(/commencement/gi,'start').replace(/execution cycle/gi,'delivery').replace(/execution/gi,'work').replace(/exception/gi,'issue').replace(/Partner-reported execution evidence/gi,'partner update').replace(/Project 360/gi,'project');}
function Modal({title,eyebrow,onClose,children}:{title:string;eyebrow:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 bg-black/30" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><aside className="absolute inset-y-0 right-0 w-full max-w-xl overflow-y-auto bg-[#f5f4ef] p-6 md:p-8" role="dialog" aria-modal="true" aria-label={title}><div className="flex items-start justify-between gap-6 border-b border-black/10 pb-5"><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-neutral-500">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold">{title}</h2></div><button className={button} onClick={onClose}>Close</button></div><div className="py-7">{children}</div></aside></div>}

export default function PartnerWorkSurface(){
  const {token}=useParams<{token:string}>();const[state,setState]=useState<ExecutionState>({});const[loading,setLoading]=useState(true);const[action,setAction]=useState<Action>(null);const[message,setMessage]=useState('');const[submitting,setSubmitting]=useState(false);const[files,setFiles]=useState<DeliveryFileState>({count:0,locked:false,cycle:1});
  const load=useCallback(async()=>{const response=await fetch(`/api/execution/${token}`,{cache:'no-store'});const body=await response.json();setState(body);setLoading(false);},[token]);useEffect(()=>{load().catch(()=>{setState({message:'Unable to load this partner workspace.'});setLoading(false);});},[load]);
  async function submit(event:FormEvent<HTMLFormElement>,apiAction:'commencement'|'progress'|'exception'|'delivery'){
    event.preventDefault();setMessage('');if(apiAction==='delivery'&&files.count<1){setMessage('Add at least one delivery file before submitting work.');return;}setSubmitting(true);const form=event.currentTarget;const data=new FormData(form);const payload:Record<string,unknown>=Object.fromEntries(data.entries());payload.action=apiAction;
    if(apiAction==='commencement'){for(const key of ['scope_reviewed','inputs_received','capacity_confirmed','no_unresolved_blocker','declaration_checked'])payload[key]=data.get(key)==='true';}
    if(apiAction==='delivery')payload.declaration_checked=data.get('declaration_checked')==='true';
    try{const response=await fetch(`/api/execution/${token}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await response.json();setMessage(businessMessage(body.message||(response.ok?'Update recorded.':'Unable to record update.')));if(response.ok){form.reset();setAction(null);await load();}}finally{setSubmitting(false);}
  }
  if(loading)return <main className="min-h-screen bg-[#f5f4ef] p-8"><div className="mx-auto max-w-6xl animate-pulse"><div className="h-4 w-40 bg-black/10"/><div className="mt-7 h-12 w-2/3 bg-black/10"/><div className="mt-10 h-48 bg-black/5"/></div></main>;
  if(!state.execution||!state.project)return <main className="min-h-screen bg-[#f5f4ef] p-8"><div className="mx-auto max-w-5xl"><p className="text-xs uppercase tracking-widest text-neutral-500">Overflow Partner</p><h1 className="mt-4 text-4xl font-semibold">Partner workspace unavailable</h1><p className="mt-4 text-neutral-600">{businessMessage(state.message)}</p></div></main>;

  const commenced=Boolean(state.commencement);const updates=state.progress_updates||[];const issues=state.exceptions||[];const submissions=state.delivery_submissions||[];const openIssues=issues.filter(item=>['open','acknowledged'].includes(String(item.status)));const submitted=state.execution.execution_state==='delivery_submitted';const correction=state.project.project_stage==='partner_correction';const canWork=['in_progress','partner_correction'].includes(state.project.project_stage)&&!submitted;const canStart=state.project.project_stage==='ready_for_execution'&&!commenced;
  const latest=updates[0];const status=!commenced?'Ready to start':submitted?'Work submitted':openIssues.length?'Issue needs attention':correction?'Changes requested':latest?.progress_state==='at_risk'?'At risk':latest?.progress_state==='blocked'?'Blocked':'In progress';
  const next=!commenced?'Confirm start':submitted?'Wait for Overflow Partner review':openIssues.length?'Resolve or update the open issue':correction?'Submit revised work':'Update progress or submit completed work';
  const timeline=useMemo(()=>[
    ...updates.map((item,index)=>({id:`progress-${index}-${item.submitted_at}`,at:String(item.submitted_at),title:'Progress updated',detail:<span>{pretty(item.progress_state)}{item.percent_complete!==null&&item.percent_complete!==undefined?` · ${item.percent_complete}%`:''}{item.work_in_progress?` · ${item.work_in_progress}`:''}</span>,source:'Progress'})),
    ...issues.map((item,index)=>({id:`issue-${index}-${item.raised_at}`,at:String(item.raised_at),title:'Issue reported',detail:<span>{item.title} · {pretty(item.severity)}</span>,source:'Issue'})),
    ...submissions.map((item,index)=>({id:`delivery-${index}-${item.submitted_at}`,at:String(item.submitted_at),title:Number(item.execution_cycle||1)>1?'Revised work submitted':'Completed work submitted',detail:<span>{item.delivery_summary}</span>,source:'Delivery'})),
  ].sort((a,b)=>new Date(b.at).getTime()-new Date(a.at).getTime()),[updates,issues,submissions]);

  return <main className="min-h-screen bg-[#f5f4ef] text-[#171717]"><div className="mx-auto max-w-[1240px] px-5 py-8 md:px-9 lg:py-12">
    <header className="border-b border-black/10 pb-7"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-neutral-500">Overflow Partner · Your work</p><div className="mt-3 flex flex-wrap items-start justify-between gap-6"><div><p className="text-sm text-neutral-500">{state.project.project_number}</p><h1 className="mt-2 max-w-3xl text-3xl font-semibold tracking-[-0.035em] md:text-5xl">{state.project.title}</h1><p className="mt-3 text-sm text-neutral-600">{state.partner?.company_name||'Delivery Partner'}</p></div><div className="grid min-w-[240px] grid-cols-2 gap-5 border-l border-black/10 pl-6"><div><small className="text-[10px] uppercase tracking-wider text-neutral-500">Status</small><strong className="mt-2 block text-sm">{status}</strong></div><div><small className="text-[10px] uppercase tracking-wider text-neutral-500">Due</small><strong className="mt-2 block text-sm">{date(state.execution.committed_due_date||state.project.due_date)}</strong></div></div></div></header>

    {message?<div className="mt-6 border-l-2 border-black bg-white/60 px-5 py-4 text-sm" role="status">{message}</div>:null}

    <div className="mt-8 grid gap-7 lg:grid-cols-[minmax(0,1fr)_310px]">
      <div className="grid content-start gap-6">
        <section className="border border-black/10 bg-white/55 p-6 md:p-8"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-neutral-500">What you need to do</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.03em]">{next}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-neutral-600">Keep this workspace simple: confirm the work basis, update progress when something materially changes, report issues early, and submit the completed engineering package when ready.</p><div className="mt-6 flex flex-wrap gap-3">{canStart?<button className={primary} onClick={()=>setAction('start')}>Confirm start</button>:null}{canStart?<button className={button} onClick={()=>setAction('issue')}>Report an issue</button>:null}{commenced&&canWork?<button className={button} onClick={()=>setAction('progress')}>Update progress</button>:null}{commenced&&canWork?<button className={button} onClick={()=>setAction('issue')}>Report an issue</button>:null}{commenced&&canWork?<button className={primary} onClick={()=>setAction('submit')}>{correction?'Submit revised work':'Submit completed work'}</button>:null}</div></section>

        <section className="grid gap-px border border-black/10 bg-black/10 sm:grid-cols-3"><div className="bg-[#f5f4ef] p-5"><small className="text-[10px] uppercase tracking-wider text-neutral-500">Progress</small><strong className="mt-2 block text-lg">{latest?.percent_complete!==null&&latest?.percent_complete!==undefined?`${latest.percent_complete}%`:'Not stated'}</strong></div><div className="bg-[#f5f4ef] p-5"><small className="text-[10px] uppercase tracking-wider text-neutral-500">Open issues</small><strong className="mt-2 block text-lg">{openIssues.length}</strong></div><div className="bg-[#f5f4ef] p-5"><small className="text-[10px] uppercase tracking-wider text-neutral-500">Forecast</small><strong className="mt-2 block text-lg">{date(latest?.forecast_delivery_date||state.commencement?.forecast_delivery_date||state.execution.committed_due_date)}</strong></div></section>

        <section className="border-t border-black/10 pt-6"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-neutral-500">Activity</p><h2 className="mt-2 text-2xl font-semibold">Work history</h2><div className="mt-4"><BusinessActivityTimeline items={timeline} empty="No work updates have been recorded yet."/></div></section>
      </div>

      <aside className="grid content-start gap-5 lg:sticky lg:top-8"><section className="border-t-2 border-black pt-5"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-neutral-500">Requirements</p><h3 className="mt-2 text-xl font-semibold">Work basis</h3><div className="mt-5 grid gap-4"><div><small className="text-[10px] uppercase tracking-wider text-neutral-500">Scope</small><strong className="mt-1 block text-sm">{state.controlled_scope?.title||'Scope not attached'}</strong>{state.controlled_scope?<p className="mt-1 text-xs text-neutral-500">{state.controlled_scope.reference}{state.controlled_scope.revision_code?` · ${state.controlled_scope.revision_code}`:''}</p>:null}</div><div><small className="text-[10px] uppercase tracking-wider text-neutral-500">Reporting</small><strong className="mt-1 block text-sm">{pretty(state.execution.reporting_cadence||'As needed')}</strong></div>{state.execution.release_notes?<div><small className="text-[10px] uppercase tracking-wider text-neutral-500">Instructions</small><p className="mt-1 text-sm leading-6 text-neutral-600">{state.execution.release_notes}</p></div>:null}</div></section>{openIssues.length?<section className="border border-black/10 bg-white/50 p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-neutral-500">Needs attention</p><h3 className="mt-2 text-lg font-semibold">{openIssues.length} open issue{openIssues.length===1?'':'s'}</h3><p className="mt-2 text-sm text-neutral-600">Keep Overflow Partner updated if an issue changes delivery timing, scope or required client input.</p></section>:null}</aside>
    </div>

    {action==='start'?<Modal eyebrow="Start work" title="Confirm you are ready to start" onClose={()=>setAction(null)}><form className="grid gap-5" onSubmit={event=>submit(event,'commencement')}><label className={label}>Delivery lead<input className={input} name="execution_lead_name" required/></label><label className={label}>Role<input className={input} name="execution_lead_role"/></label><div className="grid gap-4 sm:grid-cols-2"><label className={label}>Planned start<input className={input} type="date" name="planned_commencement_date" required/></label><label className={label}>Forecast delivery<input className={input} type="date" name="forecast_delivery_date" required/></label></div><label className={label}>Assumptions<textarea className={input} name="assumptions" rows={3}/></label>{[['scope_reviewed','I reviewed the agreed scope'],['inputs_received','I have the required inputs'],['capacity_confirmed','Capacity is confirmed'],['no_unresolved_blocker','No unresolved blocker prevents start'],['declaration_checked','I confirm this information is accurate']].map(([name,text])=><label key={name} className="flex gap-3 text-sm"><input type="checkbox" name={name} value="true" required/>{text}</label>)}<label className={label}>Submitted by<input className={input} name="submitted_by_name" required defaultValue={state.partner?.contact_name||''}/></label><label className={label}>Role<input className={input} name="submitted_by_role"/></label><button className={primary} disabled={submitting}>{submitting?'Saving…':'Confirm start'}</button></form></Modal>:null}
    {action==='progress'?<Modal eyebrow="Progress" title="Update progress" onClose={()=>setAction(null)}><form className="grid gap-5" onSubmit={event=>submit(event,'progress')}><label className={label}>Delivery health<select className={input} name="progress_state" required><option value="on_track">On track</option><option value="at_risk">At risk</option><option value="blocked">Blocked</option></select></label><label className={label}>Percent complete<input className={input} type="number" min="0" max="100" name="percent_complete"/></label><label className={label}>Work completed<textarea className={input} name="work_completed" rows={3} required/></label><label className={label}>Work in progress<textarea className={input} name="work_in_progress" rows={3} required/></label><div className="grid gap-4 sm:grid-cols-2"><label className={label}>Forecast delivery<input className={input} type="date" name="forecast_delivery_date"/></label><label className={label}>Next update<input className={input} type="date" name="next_update_date"/></label></div><label className={label}>Notes<textarea className={input} name="notes" rows={3}/></label><label className={label}>Submitted by<input className={input} name="submitted_by_name" required defaultValue={state.partner?.contact_name||''}/></label><input type="hidden" name="submitted_by_role" value=""/><button className={primary} disabled={submitting}>{submitting?'Saving…':'Save progress update'}</button></form></Modal>:null}
    {action==='issue'?<Modal eyebrow="Issue" title="Report an issue" onClose={()=>setAction(null)}><form className="grid gap-5" onSubmit={event=>submit(event,'exception')}><label className={label}>Severity<select className={input} name="severity" required><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label className={label}>Issue title<input className={input} name="title" required/></label><label className={label}>What happened?<textarea className={input} name="description" rows={4} required/></label><label className={label}>Delivery impact<textarea className={input} name="delivery_impact" rows={3}/></label><label className={label}>Who is needed?<select className={input} name="required_from"><option value="overflow_partner">Overflow Partner</option><option value="client">Client</option><option value="partner">Your team</option><option value="unknown">Not clear yet</option></select></label><label className={label}>Submitted by<input className={input} name="submitted_by_name" required defaultValue={state.partner?.contact_name||''}/></label><input type="hidden" name="submitted_by_role" value=""/><button className={primary} disabled={submitting}>{submitting?'Reporting…':'Report issue'}</button></form></Modal>:null}
    {action==='submit'?<Modal eyebrow="Delivery" title={correction?'Submit revised work':'Submit completed work'} onClose={()=>setAction(null)}><form className="grid gap-5" onSubmit={event=>submit(event,'delivery')}><PartnerDeliveryFiles token={token} onStateChange={setFiles}/><label className={label}>Revision<input className={input} name="revision"/></label><label className={label}>Delivery summary<textarea className={input} name="delivery_summary" rows={4} required/></label><label className={label}>Files and deliverables included<textarea className={input} name="deliverables_manifest" rows={4} required/></label><label className="flex gap-3 text-sm"><input type="checkbox" name="declaration_checked" value="true" required/>I confirm this package represents the completed work being submitted for review.</label><label className={label}>Submitted by<input className={input} name="submitted_by_name" required defaultValue={state.partner?.contact_name||''}/></label><input type="hidden" name="submitted_by_role" value=""/><button className={primary} disabled={submitting||files.count<1}>{submitting?'Submitting…':correction?'Submit revised work':'Submit completed work'}</button></form></Modal>:null}
  </div></main>;
}
