import Link from 'next/link';
import { requireUserContext } from '@/lib/auth/context';
import { listPartnerQuotes } from '@/lib/repositories/workflow';
import { createPartnerQuoteFormAction } from '../workflow-actions';

const input='border border-black/15 bg-white px-3 py-2 text-black';
export default async function Page({searchParams}:{searchParams?:Promise<Record<string,string|undefined>>}){
  const params=searchParams?await searchParams:{}; const {supabase,organisationId}=await requireUserContext();
  const reviewsResult=await supabase.from('partner_review_requests').select('id,case_reference,status,lead_id,partner_id,technical_intake_id,partner:partners(id,company_name),lead:leads(id,title,company_name),responses:partner_review_responses(id,revision,pricing_readiness)').eq('organisation_id',organisationId).in('status',['approved','approved_with_conditions']).order('created_at',{ascending:false});
  const schemaReady=!reviewsResult.error; const approvedReviews=(reviewsResult.data??[]) as any[];
  let quotes:any[]=[]; try{ quotes=await listPartnerQuotes(supabase,organisationId) as any[]; }catch{ quotes=[]; }
  const selectedReview=params.review?approvedReviews.find((item)=>item.id===params.review):undefined;
  return <section><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start',flexWrap:'wrap'}}><div><p className="eyebrow">Commercial</p><h1>Partner Commercial Responses</h1><p className="lede">Capture price and delivery commitments only after the partner technical response has been internally approved.</p></div>{params.lead?<Link className="button secondary" href={`/workspace/leads/${params.lead}`}>Back to Lead 360</Link>:null}</div>
    {params.created?<p className="card">Partner commercial response recorded.</p>:null}{params.error?<p className="card">{params.error}</p>:null}
    {!schemaReady?<p className="card" style={{marginTop:20,borderLeft:'3px solid #b45309'}}>Partner review migration is pending. Commercial response entry remains locked.</p>:null}
    <div className="metric-grid"><article className="metric"><span>Requested</span><strong>{quotes.filter(q=>q.status==='requested').length}</strong></article><article className="metric"><span>Received</span><strong>{quotes.filter(q=>q.status==='received').length}</strong></article><article className="metric"><span>Selected</span><strong>{quotes.filter(q=>q.status==='selected').length}</strong></article></div>
    {schemaReady&&approvedReviews.length?<form action={createPartnerQuoteFormAction} className="card stack" style={{marginTop:24}}><p className="eyebrow">Governed commercial stage</p><h3>Create request / record response</h3><label>Approved technical partner review<select className={input} name="partner_review_request_id" required defaultValue={selectedReview?.id||''}><option value="">Select approved review</option>{approvedReviews.map((review:any)=><option key={review.id} value={review.id}>{review.case_reference} · {review.partner?.company_name} · {review.lead?.title||review.lead?.company_name}</option>)}</select></label>
      <input type="hidden" name="partner_review_response_id" value={selectedReview?.responses?.sort((a:any,b:any)=>b.revision-a.revision)?.[0]?.id||''}/><input type="hidden" name="partner_id" value={selectedReview?.partner_id||''}/><input type="hidden" name="lead_id" value={selectedReview?.lead_id||''}/><input type="hidden" name="technical_intake_id" value={selectedReview?.technical_intake_id||''}/>
      {!selectedReview?<p>Select the approved review from Lead 360 so partner, lead and technical scope are inherited without re-entry.</p>:<div className="metric"><span>Inherited case</span><strong style={{fontSize:18}}>{selectedReview.case_reference} · {selectedReview.partner?.company_name}</strong></div>}
      <div className="grid gap-4 md:grid-cols-2"><input className={input} name="price" type="number" min="0" step="0.01" defaultValue="0"/><input className={input} name="currency" defaultValue="GBP"/><input className={input} name="lead_time_days" type="number" min="0" placeholder="Lead time days"/><input className={input} name="valid_until" type="date"/><input className={input} name="quote_reference" placeholder="Partner quote reference"/><select className={input} name="status" defaultValue="requested"><option value="requested">Requested</option><option value="received">Received</option><option value="under_review">Under review</option><option value="selected">Selected</option><option value="declined">Declined</option><option value="expired">Expired</option></select></div>
      <textarea className={input} name="commercial_assumptions" rows={3} placeholder="Commercial assumptions"/><textarea className={input} name="exclusions" rows={3} placeholder="Commercial exclusions"/><textarea className={input} name="payment_terms" rows={2} placeholder="Payment terms"/><textarea className={input} name="delivery_commitment" rows={2} placeholder="Delivery commitment"/><textarea className={input} name="notes" rows={3} placeholder="Internal commercial notes"/><button className="button" disabled={!selectedReview}>Save commercial response</button></form>:schemaReady?<div className="card" style={{marginTop:24}}><h3>No approved technical partner review</h3><p>Open Lead 360, complete the partner technical review and record internal approval first.</p></div>:null}
    <div style={{display:'grid',gap:12,marginTop:28}}>{quotes.map((q:any)=><article className="metric" key={q.id}><div style={{display:'flex',justifyContent:'space-between',gap:16}}><strong>{q.partner?.company_name||'Partner'}</strong><span>{q.status.replaceAll('_',' ')}</span></div><p>{q.lead?.title||q.lead?.company_name||'Lead'} · {q.currency} {Number(q.price).toFixed(2)} · {q.lead_time_days??'—'} days</p></article>)}</div>
  </section>;
}
