import type { SupabaseClient } from '@supabase/supabase-js';

type CountResult = { count: number | null; error: { message: string } | null };
type BaseRecord = { id: string; created_at: string; updated_at?: string };
type ProspectRow = BaseRecord & { company_name: string; contact_name: string | null; project_type: string | null; requirement_summary: string | null; status: string; source: string; assigned_to: string | null };
type LeadRow = BaseRecord & { company_name: string; contact_name: string | null; contact_email: string | null; project_type: string | null; title: string | null; notes: string | null; service: string | null; status: string; priority: string; owner_id: string | null; reference?: string | null };
type IntakeRow = BaseRecord & { lead_id: string; description: string; deliverables: string | null; deadline: string | null; discipline: string | null; status: string; submitted_at: string | null };
type PartnerQuoteRow = BaseRecord & { lead_id: string; status: string; price: number; currency: string; valid_until: string | null };
type ReviewRow = BaseRecord & { lead_id: string; status: string; client_price: number; margin_percent: number | null };
type QuoteRow = BaseRecord & { lead_id: string; status: string; quote_number: string; total: number; currency: string; issued_at: string | null };
type ProjectRow = BaseRecord & { lead_id: string; status: string; project_number: string; title: string; due_date: string | null };
type TaskRow = BaseRecord & { entity_type: string; entity_id: string; title: string; status: string; priority: string; due_at: string | null };

export type DashboardActivity = { id: string; entity_type: string; entity_id: string; event_type: string; event_data: Record<string, unknown> | null; created_at: string };
export type MissionCase = { id: string; kind: 'prospect' | 'lead'; company: string; contact: string | null; reference: string; requirement: string; service: string; stage: 'prospect' | 'lead' | 'technical' | 'partner' | 'commercial' | 'quote' | 'project'; stageLabel: string; status: string; priority: string; createdAt: string; updatedAt: string; waitingSince: string; nextAction: string; href: string; deadline: string | null; amount: string | null; timeline: DashboardActivity[] };
export type AttentionItem = { id: string; title: string; company: string; reason: string; waitingSince: string; priority: string; href: string; stage: MissionCase['stage'] };
export type DashboardSnapshot = { prospects: number; qualifiedProspects: number; openLeads: number; technicalIntakesAwaitingReview: number; partnerRfqsOutstanding: number; quotesAwaitingApproval: number; activeProjects: number; documents: number; todaysActivity: number; recentActivity: DashboardActivity[]; warnings: string[]; cases: MissionCase[]; attention: AttentionItem[]; pipeline: Record<MissionCase['stage'], MissionCase[]>; selectedCase: MissionCase | null };

async function safeCount(promise: PromiseLike<CountResult>, label: string, warnings: string[]) { const result = await promise; if (result.error) { warnings.push(`${label}: ${result.error.message}`); return 0; } return result.count ?? 0; }
function latest<T extends BaseRecord>(rows: T[], predicate: (row: T) => boolean): T | null { return rows.filter(predicate).sort((a, b) => Date.parse(b.created_at) - Date.parse(a.created_at))[0] ?? null; }

function deriveLeadCase(lead: LeadRow, intakes: IntakeRow[], partnerQuotes: PartnerQuoteRow[], reviews: ReviewRow[], quotes: QuoteRow[], projects: ProjectRow[], activity: DashboardActivity[]): MissionCase {
  const intake = latest(intakes, (row) => row.lead_id === lead.id); const partnerQuote = latest(partnerQuotes, (row) => row.lead_id === lead.id); const review = latest(reviews, (row) => row.lead_id === lead.id); const quote = latest(quotes, (row) => row.lead_id === lead.id); const project = latest(projects, (row) => row.lead_id === lead.id);
  let stage: MissionCase['stage'] = 'lead'; let stageLabel = 'Lead qualification'; let nextAction = 'Create inherited technical intake'; let status = lead.status; let waitingSince = lead.updated_at || lead.created_at; let deadline: string | null = null; let amount: string | null = null;
  if (project) { stage = 'project'; stageLabel = 'Project delivery'; nextAction = 'Manage delivery and controlled documents'; status = project.status; waitingSince = project.updated_at || project.created_at; deadline = project.due_date; }
  else if (quote) { stage = 'quote'; stageLabel = 'Client quote'; status = quote.status; waitingSince = quote.updated_at || quote.created_at; nextAction = quote.status === 'issued' ? 'Record client decision' : 'Review and issue client quote'; amount = `${quote.currency} ${Number(quote.total).toLocaleString('en-GB', { maximumFractionDigits: 2 })}`; }
  else if (review) { stage = 'commercial'; stageLabel = 'Commercial review'; status = review.status; waitingSince = review.updated_at || review.created_at; nextAction = 'Approve commercial position'; amount = `GBP ${Number(review.client_price).toLocaleString('en-GB', { maximumFractionDigits: 2 })}`; }
  else if (partnerQuote || intake?.status === 'approved') { stage = 'partner'; stageLabel = 'Partner pricing'; status = partnerQuote?.status || 'awaiting_partner_quote'; waitingSince = partnerQuote?.updated_at || partnerQuote?.created_at || intake?.updated_at || intake?.created_at || lead.created_at; nextAction = partnerQuote ? 'Review compliant partner quote' : 'Obtain compliant partner pricing'; if (partnerQuote) amount = `${partnerQuote.currency} ${Number(partnerQuote.price).toLocaleString('en-GB', { maximumFractionDigits: 2 })}`; }
  else if (intake) { stage = 'technical'; stageLabel = 'Technical review'; status = intake.status; waitingSince = intake.updated_at || intake.created_at; nextAction = ['submitted', 'under_review'].includes(intake.status) ? 'Review technical scope' : 'Complete and submit technical intake'; deadline = intake.deadline; }
  return { id: lead.id, kind: 'lead', company: lead.company_name, contact: lead.contact_name, reference: lead.reference || `LEAD-${lead.id.slice(0, 8).toUpperCase()}`, requirement: intake?.description || lead.notes || lead.title || `${lead.company_name} engineering requirement`, service: intake?.discipline || lead.project_type || lead.service || 'Engineering overflow support', stage, stageLabel, status, priority: lead.priority || 'normal', createdAt: lead.created_at, updatedAt: lead.updated_at || lead.created_at, waitingSince, nextAction, href: `/workspace/leads/${lead.id}`, deadline, amount, timeline: activity.filter((event) => event.entity_id === lead.id || (event.event_data && event.event_data.leadId === lead.id)).slice(0, 8) };
}

export async function getDashboardSnapshot(supabase: SupabaseClient, organisationId: string): Promise<DashboardSnapshot> {
  const warnings: string[] = []; const startOfToday = new Date(); startOfToday.setHours(0, 0, 0, 0);
  const [prospectResult, leadResult, intakeResult, partnerQuoteResult, reviewResult, quoteResult, projectResult, taskResult, activityResult] = await Promise.all([
    supabase.from('prospects').select('id, company_name, contact_name, project_type, requirement_summary, status, source, assigned_to, created_at, updated_at').eq('organisation_id', organisationId).order('created_at', { ascending: false }),
    supabase.from('leads').select('id, company_name, contact_name, contact_email, project_type, title, notes, service, status, priority, owner_id, reference, created_at, updated_at').eq('organisation_id', organisationId).order('created_at', { ascending: false }),
    supabase.from('technical_intakes').select('id, lead_id, description, deliverables, deadline, discipline, status, submitted_at, created_at, updated_at').eq('organisation_id', organisationId).order('created_at', { ascending: false }),
    supabase.from('partner_quotes').select('id, lead_id, status, price, currency, valid_until, created_at, updated_at').eq('organisation_id', organisationId).order('created_at', { ascending: false }),
    supabase.from('commercial_reviews').select('id, lead_id, status, client_price, margin_percent, created_at, updated_at').eq('organisation_id', organisationId).order('created_at', { ascending: false }),
    supabase.from('quotes').select('id, lead_id, status, quote_number, total, currency, issued_at, created_at, updated_at').eq('organisation_id', organisationId).order('created_at', { ascending: false }),
    supabase.from('projects').select('id, lead_id, status, project_number, title, due_date, created_at, updated_at').eq('organisation_id', organisationId).order('created_at', { ascending: false }),
    supabase.from('tasks').select('id, entity_type, entity_id, title, status, priority, due_at, created_at, updated_at').eq('organisation_id', organisationId).in('status', ['open', 'in_progress', 'blocked']).order('created_at', { ascending: false }),
    supabase.from('activity_events').select('id, entity_type, entity_id, event_type, event_data, created_at').eq('organisation_id', organisationId).order('created_at', { ascending: false }).limit(40),
  ]);
  [prospectResult, leadResult, intakeResult, partnerQuoteResult, reviewResult, quoteResult, projectResult, taskResult, activityResult].forEach((result, index) => { if (result.error) warnings.push(`Mission control query ${index + 1}: ${result.error.message}`); });
  const prospects = (prospectResult.data ?? []) as ProspectRow[]; const leads = (leadResult.data ?? []) as LeadRow[]; const intakes = (intakeResult.data ?? []) as IntakeRow[]; const partnerQuotes = (partnerQuoteResult.data ?? []) as PartnerQuoteRow[]; const reviews = (reviewResult.data ?? []) as ReviewRow[]; const quotes = (quoteResult.data ?? []) as QuoteRow[]; const projects = (projectResult.data ?? []) as ProjectRow[]; const tasks = (taskResult.data ?? []) as TaskRow[]; const activity = (activityResult.data ?? []) as DashboardActivity[];
  const prospectCases: MissionCase[] = prospects.filter((row) => !['converted', 'not_a_fit'].includes(row.status)).map((row) => ({ id: row.id, kind: 'prospect', company: row.company_name, contact: row.contact_name, reference: `PROSPECT-${row.id.slice(0, 8).toUpperCase()}`, requirement: row.requirement_summary || 'Initial requirement submitted; structured scope not yet recorded.', service: row.project_type || 'Engineering requirement', stage: 'prospect', stageLabel: 'Prospect qualification', status: row.status, priority: 'normal', createdAt: row.created_at, updatedAt: row.updated_at || row.created_at, waitingSince: row.updated_at || row.created_at, nextAction: row.status === 'qualified' ? 'Convert to governed lead' : 'Review and qualify enquiry', href: '/workspace/acquisition', deadline: null, amount: null, timeline: activity.filter((event) => event.entity_type === 'prospect' && event.entity_id === row.id).slice(0, 8) }));
  const leadCases = leads.filter((row) => !['won', 'lost'].includes(row.status) || projects.some((project) => project.lead_id === row.id && !['completed', 'closed', 'cancelled'].includes(project.status))).map((lead) => deriveLeadCase(lead, intakes, partnerQuotes, reviews, quotes, projects, activity));
  const cases = [...prospectCases, ...leadCases].sort((a, b) => Date.parse(b.updatedAt) - Date.parse(a.updatedAt));
  const pipeline: DashboardSnapshot['pipeline'] = { prospect: [], lead: [], technical: [], partner: [], commercial: [], quote: [], project: [] }; cases.forEach((item) => pipeline[item.stage].push(item));
  const attention: AttentionItem[] = cases.filter((item) => item.stage !== 'project' || ['waiting', 'review'].includes(item.status)).slice(0, 8).map((item) => ({ id: item.id, title: item.nextAction, company: item.company, reason: item.deadline ? `Deadline ${item.deadline}` : `${item.stageLabel} · ${item.status.replaceAll('_', ' ')}`, waitingSince: item.waitingSince, priority: item.priority, href: item.href, stage: item.stage }));
  tasks.slice(0, 5).forEach((task) => { if (!attention.some((item) => item.id === task.entity_id)) attention.push({ id: task.id, title: task.title, company: task.entity_type.replaceAll('_', ' '), reason: task.due_at ? `Due ${task.due_at}` : `Task · ${task.status}`, waitingSince: task.created_at, priority: task.priority, href: task.entity_type === 'lead' ? `/workspace/leads/${task.entity_id}` : '/workspace/tasks', stage: 'lead' }); });
  const [technicalIntakesAwaitingReview, partnerRfqsOutstanding, quotesAwaitingApproval, documents, todaysActivity] = await Promise.all([
    safeCount(supabase.from('technical_intakes').select('id', { count: 'exact', head: true }).eq('organisation_id', organisationId).in('status', ['submitted', 'under_review', 'clarification_required']), 'Technical intakes', warnings),
    safeCount(supabase.from('partner_quotes').select('id', { count: 'exact', head: true }).eq('organisation_id', organisationId).eq('status', 'requested'), 'Partner RFQs', warnings),
    safeCount(supabase.from('commercial_reviews').select('id', { count: 'exact', head: true }).eq('organisation_id', organisationId).eq('status', 'pending_approval'), 'Commercial reviews', warnings),
    safeCount(supabase.from('documents').select('id', { count: 'exact', head: true }).eq('organisation_id', organisationId), 'Documents', warnings),
    safeCount(supabase.from('activity_events').select('id', { count: 'exact', head: true }).eq('organisation_id', organisationId).gte('created_at', startOfToday.toISOString()), "Today's activity", warnings),
  ]);
  return { prospects: prospects.length, qualifiedProspects: prospects.filter((row) => row.status === 'qualified').length, openLeads: leads.filter((row) => !['won', 'lost'].includes(row.status)).length, technicalIntakesAwaitingReview, partnerRfqsOutstanding, quotesAwaitingApproval, activeProjects: projects.filter((row) => ['planning', 'active', 'waiting', 'review'].includes(row.status)).length, documents, todaysActivity, recentActivity: activity.slice(0, 12), warnings, cases, attention: attention.slice(0, 8), pipeline, selectedCase: cases[0] ?? null };
}
