'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import PartnerDeliveryFiles from '@/components/execution/PartnerDeliveryFiles';

type ExecutionState={
  execution?:{assignment_id:string;execution_state:string;release_reference?:string|null;planned_start_date?:string|null;committed_due_date?:string|null;reporting_cadence:string;release_notes?:string|null;released_at?:string|null};
  project?:{id:string;project_number:string;title:string;start_date?:string|null;due_date?:string|null;project_stage:string};
  partner?:{id:string;company_name:string;contact_name?:string|null};
  controlled_scope?:{id:string;title:string;reference:string;status:string;revision_code?:string|null;issue_purpose?:string|null}|null;
  commencement?:Record<string,unknown>|null;
  progress_updates?:Array<Record<string,unknown>>;
  exceptions?:Array<Record<string,unknown>>;
  delivery_submissions?:Array<Record<string,unknown>>;
  message?:string;
};
type Mode='progress'|'exception'|'delivery'|null;

type DeliveryFileState={count:number;locked:boolean;cycle:number};
const field='w-full border-0 border-b border-black/20 bg-transparent px-0 py-3 text-base outline-none focus:border-black';
const label='grid gap-2 text-xs font-medium uppercase tracking-[0.08em] text-neutral-500';
const section='grid gap-7 border-t border-black/10 pt-8';
function pretty(value?:unknown){return String(value||'not recorded').replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase());}
function date(value?:unknown){if(!value)return'Not set';const d=new Date(String(value));return Number.isNaN(d.getTime())?String(value):d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});}

export default function PartnerExecutionPage(){
  const{token}=useParams<{token:string}>();
  const[state,setState]=useState<ExecutionState>({});const[loading,setLoading]=useState(true);const[submitting,setSubmitting]=useState(false);const[message,setMessage]=useState('');const[mode,setMode]=useState<Mode>(null);const[deliveryFiles,setDeliveryFiles]=useState<DeliveryFileState>({count:0,locked:false,cycle:1});
  const load=useCallback(async()=>{const response=await fetch(`/api/execution/${token}`,{cache:'no-store'});const body=await response.json();setState(body);setLoading(false);},[token]);
  useEffect(()=>{load().catch(()=>{setState({message:'Unable to load this Partner Execution workspace.'});setLoading(false);});},[load]);

  async function submit(event:FormEvent<HTMLFormElement>,action:'commencement'|'progress'|'exception'|'delivery'){
    event.preventDefault();setMessage('');
    if(action==='delivery'&&deliveryFiles.count<1){setMessage('Attach at least one engineering output file before submitting this delivery.');return;}
    if(action==='delivery'&&deliveryFiles.locked){setMessage('This execution cycle has already been submitted. Its delivery evidence is locked.');return;}
    setSubmitting(true);const form=event.currentTarget;const data=new FormData(form);const payload:Record<string,unknown>=Object.fromEntries(data.entries());payload.action=action;
    if(action==='commencement'){payload.scope_reviewed=data.get('scope_reviewed')==='true';payload.inputs_received=data.get('inputs_received')==='true';payload.capacity_confirmed=data.get('capacity_confirmed')==='true';payload.no_unresolved_blocker=data.get('no_unresolved_blocker')==='true';payload.declaration_checked=data.get('declaration_checked')==='true';}
    if(action==='delivery')payload.declaration_checked=data.get('declaration_checked')==='true';
    const response=await fetch(`/api/execution/${token}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await response.json();setSubmitting(false);setMessage(body.message||(response.ok?'Update recorded.':'Unable to record update.'));
    if(response.ok){form.reset();setMode(null);await load();}
  }

  if(loading)return <main className="min-h-screen bg-[#f5f4ef] px-6 py-20 text-[#151515]"><p>Loading controlled execution workspace…</p></main>;
  if(!state.execution||!state.project)return <main className="min-h-screen bg-[#f5f4ef] px-6 py-20 text-[#151515]"><div className="mx-auto max-w-5xl border-t border-black/10 pt-10"><p className="text-xs uppercase tracking-[0.12em] text-neutral-500">Overflow Partner</p><h1 className="mt-4 text-4xl font-semibold">Execution workspace unavailable</h1><p className="mt-5 text-neutral-600">{state.message}</p></div></main>;

  const commenced=Boolean(state.commencement);const updates=state.progress_updates||[];const exceptions=state.exceptions||[];const submissions=state.delivery_submissions||[];const openExceptions=exceptions.filter(item=>['open','acknowledged'].includes(String(item.status)));const latest=updates[0];
  const canReport=['in_progress','partner_correction'].includes(String(state.project.project_stage));

  return <main className="min-h-screen bg-[#f5f4ef] px-5 py-10 text-[#151515] md:px-10 md:py-16"><div className="mx-auto max-w-7xl">
    <header className="grid gap-8 border-t border-black/10 pt-8 lg:grid-cols-[1.15fr_0.85fr]"><div><p className="text-xs font-medium uppercase tracking-[0.12em] text-neutral-500">Overflow Partner · Controlled execution</p><h1 className="mt-5 max-w-4xl text-4xl font-semibold tracking-[-0.04em] md:text-6xl">{state.project.title}</h1><p className="mt-5 text-lg text-neutral-600">{state.project.project_number}</p></div><div className="grid content-start gap-5 border-l border-black/10 pl-0 lg:pl-8"><div><p className="text-xs uppercase tracking-[0.1em] text-neutral-500">Execution Partner</p><p className="mt-2 text-xl font-medium">{state.partner?.company_name}</p></div><div className="grid grid-cols-2 gap-5 border-t border-black/10 pt-5"><div><p className="text-xs uppercase tracking-[0.08em] text-neutral-500">Project stage</p><p className="mt-2 text-sm font-medium">{pretty(state.project.project_stage)}</p></div><div><p className="text-xs uppercase tracking-[0.08em] text-neutral-500">Committed due</p><p className="mt-2 text-sm font-medium">{date(state.execution.committed_due_date||state.project.due_date)}</p></div></div><div><p className="text-xs uppercase tracking-[0.08em] text-neutral-500">Reporting requirement</p><p className="mt-2 text-sm">{pretty(state.execution.reporting_cadence)}</p></div></div></header>

    <section className="mt-12 grid gap-6 border-y border-black/10 py-7 md:grid-cols-4"><div><p className="text-xs uppercase tracking-[0.08em] text-neutral-500">Commencement</p><p className="mt-2 font-medium">{commenced?'Declared':'Awaiting declaration'}</p></div><div><p className="text-xs uppercase tracking-[0.08em] text-neutral-500">Latest progress</p><p className="mt-2 font-medium">{latest?pretty(latest.progress_state):'No update'}</p></div><div><p className="text-xs uppercase tracking-[0.08em] text-neutral-500">Open exceptions</p><p className="mt-2 font-medium">{openExceptions.length}</p></div><div><p className="text-xs uppercase tracking-[0.08em] text-neutral-500">Delivery submissions</p><p className="mt-2 font-medium">{submissions.length}</p></div></section>
    {message?<div className="mt-7 border-l-2 border-orange-500 bg-white/40 px-5 py-4 text-sm" role="status">{message}</div>:null}

    <div className="mt-12 grid gap-14 lg:grid-cols-[0.82fr_1.18fr]"><aside className="grid content-start gap-8 lg:sticky lg:top-8 lg:self-start">
      <section className="grid gap-5"><div><p className="text-xs uppercase tracking-[0.1em] text-neutral-500">Controlled release</p><h2 className="mt-2 text-2xl font-semibold">Execution basis</h2></div>{state.controlled_scope?<div className="border-t border-black/10 pt-5"><p className="text-xs uppercase tracking-[0.08em] text-neutral-500">Controlled scope</p><p className="mt-2 font-medium">{state.controlled_scope.reference}</p><p className="mt-1 text-sm text-neutral-600">{state.controlled_scope.title}{state.controlled_scope.revision_code?` · ${state.controlled_scope.revision_code}`:''}</p></div>:<p className="border-l-2 border-orange-500 pl-4 text-sm text-neutral-600">No controlled execution scope is linked. Do not commence execution.</p>}{state.execution.release_notes?<div className="border-t border-black/10 pt-5"><p className="text-xs uppercase tracking-[0.08em] text-neutral-500">Release instructions</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{state.execution.release_notes}</p></div>:null}</section>
      {commenced&&canReport?<section className="grid gap-3 border-t border-black/10 pt-7"><p className="text-xs uppercase tracking-[0.1em] text-neutral-500">Report execution</p><button onClick={()=>setMode('progress')} className="border border-black/20 px-5 py-3 text-left text-sm font-medium hover:bg-black hover:text-white">Submit progress update →</button><button onClick={()=>setMode('exception')} className="border border-black/20 px-5 py-3 text-left text-sm font-medium hover:bg-black hover:text-white">Raise execution exception →</button><button onClick={()=>setMode('delivery')} className="border border-black/20 px-5 py-3 text-left text-sm font-medium hover:bg-black hover:text-white">Submit engineering delivery →</button></section>:null}
    </aside>

    <div className="grid content-start gap-12">
      {!commenced?<form className="grid gap-9" onSubmit={event=>submit(event,'commencement')}><section className={section}><div><p className="text-xs uppercase tracking-[0.12em] text-neutral-500">01 · Commencement declaration</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.025em]">Confirm execution can begin.</h2><p className="mt-3 max-w-2xl leading-7 text-neutral-600">This declaration is the controlled commencement event. A valid submission advances a Ready for execution Project to In progress.</p></div><div className="grid gap-8 md:grid-cols-2"><label className={label}>Execution lead<input className={field} name="execution_lead_name" required/></label><label className={label}>Role<input className={field} name="execution_lead_role"/></label><label className={label}>Planned commencement<input className={field} name="planned_commencement_date" type="date" required defaultValue={state.execution.planned_start_date||state.project.start_date||''}/></label><label className={label}>Forecast delivery<input className={field} name="forecast_delivery_date" type="date" required defaultValue={state.execution.committed_due_date||state.project.due_date||''}/></label></div><div className="grid gap-3 text-sm leading-6">{[['scope_reviewed','I have reviewed the controlled execution scope and release instructions.'],['inputs_received','The technical inputs required to start execution have been received.'],['capacity_confirmed','We have the capacity and capability to commence the assigned work.'],['no_unresolved_blocker','There is no unresolved blocker preventing commencement.']].map(([name,text])=><label key={name} className="flex items-start gap-3"><input className="mt-1" type="checkbox" name={name} value="true" required/><span>{text}</span></label>)}</div><label className={label}>Assumptions / commencement note<textarea className={`${field} min-h-24 resize-y normal-case tracking-normal`} name="assumptions"/></label><div className="grid gap-8 md:grid-cols-2"><label className={label}>Submitted by<input className={field} name="submitted_by_name" required/></label><label className={label}>Role<input className={field} name="submitted_by_role"/></label></div><label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1" type="checkbox" name="declaration_checked" value="true" required/><span>We confirm that we are commencing execution against the identified controlled project scope and that the statements above are accurate.</span></label><button disabled={submitting||!state.controlled_scope} className="min-h-12 bg-black px-7 py-3 text-sm font-medium uppercase tracking-[0.08em] text-white disabled:bg-neutral-500">{submitting?'Recording…':'Confirm commencement'}</button></section></form>
      :<section className="grid gap-8"><div><p className="text-xs uppercase tracking-[0.12em] text-neutral-500">Execution timeline</p><h2 className="mt-2 text-3xl font-semibold">Partner-reported evidence</h2><p className="mt-3 text-neutral-600">Updates are retained as historical evidence. They do not overwrite earlier declarations.</p></div><div className="grid gap-4">{updates.length===0&&exceptions.length===0&&submissions.length===0?<div className="border-t border-black/10 py-6 text-neutral-500">No execution updates have been submitted after commencement.</div>:[...updates.map(item=>({kind:'Progress update',at:item.submitted_at,title:pretty(item.progress_state),detail:String(item.work_in_progress||'')})),...exceptions.map(item=>({kind:'Exception',at:item.raised_at,title:String(item.title||''),detail:`${pretty(item.severity)} · ${String(item.description||'')}`})),...submissions.map(item=>({kind:'Delivery submission',at:item.submitted_at,title:String(item.revision||`Execution cycle ${String(item.execution_cycle||'')}`),detail:String(item.delivery_summary||'')}))].sort((a,b)=>new Date(String(b.at)).getTime()-new Date(String(a.at)).getTime()).map((item,index)=><article key={`${item.kind}-${index}`} className="grid gap-2 border-t border-black/10 py-5"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs uppercase tracking-[0.08em] text-neutral-500">{item.kind}</p><time className="text-xs text-neutral-500">{date(item.at)}</time></div><strong className="text-lg">{item.title}</strong><p className="whitespace-pre-wrap text-sm leading-6 text-neutral-600">{item.detail}</p></article>)}</div></section>}

      {mode==='progress'?<form onSubmit={event=>submit(event,'progress')} className={section}><div><p className="text-xs uppercase tracking-[0.12em] text-neutral-500">Progress update</p><h2 className="mt-2 text-2xl font-semibold">Report current execution.</h2></div><div className="grid gap-8 md:grid-cols-2"><label className={label}>Execution state<select className={field} name="progress_state" required defaultValue="on_track"><option value="on_track">On track</option><option value="at_risk">At risk</option><option value="blocked">Blocked</option></select></label><label className={label}>Partner-reported completion %<input className={field} name="percent_complete" type="number" min="0" max="100" step="1"/></label></div><label className={label}>Work completed since last update<textarea className={`${field} min-h-24 resize-y normal-case tracking-normal`} name="work_completed" required/></label><label className={label}>Work currently in progress<textarea className={`${field} min-h-24 resize-y normal-case tracking-normal`} name="work_in_progress" required/></label><div className="grid gap-8 md:grid-cols-2"><label className={label}>Forecast delivery<input className={field} name="forecast_delivery_date" type="date"/></label><label className={label}>Next update date<input className={field} name="next_update_date" type="date"/></label></div><label className={label}>Notes<textarea className={`${field} min-h-20 resize-y normal-case tracking-normal`} name="notes"/></label><div className="grid gap-8 md:grid-cols-2"><label className={label}>Submitted by<input className={field} name="submitted_by_name" required/></label><label className={label}>Role<input className={field} name="submitted_by_role"/></label></div><div className="flex gap-3"><button disabled={submitting} className="bg-black px-6 py-3 text-sm font-medium text-white">Submit update</button><button type="button" onClick={()=>setMode(null)} className="border border-black/20 px-6 py-3 text-sm">Cancel</button></div></form>:null}

      {mode==='exception'?<form onSubmit={event=>submit(event,'exception')} className={section}><div><p className="text-xs uppercase tracking-[0.12em] text-neutral-500">Execution exception</p><h2 className="mt-2 text-2xl font-semibold">Raise a blocker or risk.</h2><p className="mt-2 text-sm text-neutral-600">Do not bury delivery-impacting issues inside a progress note.</p></div><div className="grid gap-8 md:grid-cols-2"><label className={label}>Severity<select className={field} name="severity" required defaultValue="medium"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label className={label}>Action required from<select className={field} name="required_from" required defaultValue="overflow_partner"><option value="overflow_partner">Overflow Partner</option><option value="client">Client</option><option value="partner">Execution Partner</option><option value="unknown">To be determined</option></select></label></div><label className={label}>Exception title<input className={field} name="title" required/></label><label className={label}>Description<textarea className={`${field} min-h-28 resize-y normal-case tracking-normal`} name="description" required/></label><label className={label}>Delivery impact<textarea className={`${field} min-h-20 resize-y normal-case tracking-normal`} name="delivery_impact"/></label><div className="grid gap-8 md:grid-cols-2"><label className={label}>Raised by<input className={field} name="submitted_by_name" required/></label><label className={label}>Role<input className={field} name="submitted_by_role"/></label></div><div className="flex gap-3"><button disabled={submitting} className="bg-black px-6 py-3 text-sm font-medium text-white">Raise exception</button><button type="button" onClick={()=>setMode(null)} className="border border-black/20 px-6 py-3 text-sm">Cancel</button></div></form>:null}

      {mode==='delivery'?<form onSubmit={event=>submit(event,'delivery')} className={section}><div><p className="text-xs uppercase tracking-[0.12em] text-neutral-500">Engineering delivery · Cycle {deliveryFiles.cycle}</p><h2 className="mt-2 text-2xl font-semibold">Submit actual engineering output for Overflow Partner review.</h2><p className="mt-2 text-sm text-neutral-600">This is Partner delivery evidence only. It does not issue anything to the client.</p></div><label className={label}>Revision / submission reference<input className={field} name="revision" placeholder="Rev A"/></label><label className={label}>Delivery summary<textarea className={`${field} min-h-28 resize-y normal-case tracking-normal`} name="delivery_summary" required/></label><label className={label}>Deliverables manifest<textarea className={`${field} min-h-32 resize-y normal-case tracking-normal`} name="deliverables_manifest" required placeholder="List drawings, models, CAM outputs and other deliverables included."/></label><PartnerDeliveryFiles token={token} onStateChange={setDeliveryFiles}/><div className="grid gap-8 md:grid-cols-2"><label className={label}>Submitted by<input className={field} name="submitted_by_name" required/></label><label className={label}>Role<input className={field} name="submitted_by_role"/></label></div><label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1" type="checkbox" name="declaration_checked" value="true" required/><span>We confirm that the listed engineering outputs and attached files are submitted against the controlled project scope for Overflow Partner review.</span></label><div className="flex flex-wrap gap-3"><button disabled={submitting||deliveryFiles.count<1||deliveryFiles.locked} className="bg-black px-6 py-3 text-sm font-medium text-white disabled:bg-neutral-400">{submitting?'Submitting…':deliveryFiles.count<1?'Attach output files first':'Submit engineering delivery'}</button><button type="button" onClick={()=>setMode(null)} className="border border-black/20 px-6 py-3 text-sm">Cancel</button></div></form>:null}
    </div></div>
  </div></main>;
}
