import { requireUserContext } from '@/lib/auth/context';
import { listPartners } from '@/lib/repositories/workflow';
import { createPartnerFormAction } from '../workflow-actions';

const input='border border-black/15 bg-white px-3 py-2 text-black';
export default async function PartnersPage({ searchParams }: { searchParams?: Promise<Record<string,string|undefined>> }) {
 const params=searchParams?await searchParams:{}; const {supabase,organisationId}=await requireUserContext(); const partners=await listPartners(supabase,organisationId);
 return <section><p className="eyebrow">Engineering</p><h1>Partner directory</h1><p className="lede">Control approved execution partners, capabilities, NDA status and supplier readiness.</p>{params.created?<p className="card">Partner created.</p>:null}{params.error?<p className="card">{params.error}</p>:null}
 <div className="metric-grid"><article className="metric"><span>Total partners</span><strong>{partners.length}</strong></article><article className="metric"><span>Approved</span><strong>{partners.filter(p=>p.status==='approved').length}</strong></article><article className="metric"><span>NDA signed</span><strong>{partners.filter(p=>p.nda_signed).length}</strong></article></div>
 <form action={createPartnerFormAction} className="card stack" style={{marginTop:24}}><h3>Add partner</h3><div className="grid gap-4 md:grid-cols-2"><input className={input} name="company_name" placeholder="Company name" required/><input className={input} name="country" placeholder="Country"/><input className={input} name="contact_name" placeholder="Contact name"/><input className={input} name="email" type="email" placeholder="Email"/><input className={input} name="phone" placeholder="Phone"/><select className={input} name="status" defaultValue="prospective"><option value="prospective">Prospective</option><option value="approved">Approved</option><option value="suspended">Suspended</option><option value="inactive">Inactive</option></select><select className={input} name="nda_signed" defaultValue="false"><option value="false">NDA not signed</option><option value="true">NDA signed</option></select><input className={input} name="rating" type="number" min="0" max="5" step="0.1" placeholder="Rating"/></div><textarea className={input} name="services" required rows={3} placeholder="Capabilities and services"/><textarea className={input} name="notes" rows={3} placeholder="Notes"/><button className="button">Add partner</button></form>
 <div style={{display:'grid',gap:12,marginTop:28}}>{partners.map(p=><article className="metric" key={p.id}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><strong style={{fontSize:22}}>{p.company_name}</strong><p>{p.services}</p></div><span>{p.status}</span></div><p>{p.country||'Country not recorded'} · {p.nda_signed?'NDA signed':'NDA outstanding'}{p.rating!==null?` · ${p.rating}/5`:''}</p></article>)}</div></section>;
}
