import { requireUserContext } from '@/lib/auth/context';
import { listPartners } from '@/lib/repositories/workflow';
import { createPartnerFormAction } from '../workflow-actions';
import { workspaceLabel } from '@/lib/presentation/vocabulary';

const input='border border-white/10 rounded-lg bg-white px-3 py-2 text-black';
export default async function PartnersPage({ searchParams }: { searchParams?: Promise<Record<string,string|undefined>> }) {
  const params=searchParams?await searchParams:{};const {supabase,organisationId}=await requireUserContext();const partners=await listPartners(supabase,organisationId);const approved=partners.filter(p=>p.status==='approved').length;const ndaReady=partners.filter(p=>p.nda_signed).length;
  return <section className="vp-page">
    <header className="vp-header"><div><p className="vp-kicker">Partners</p><h1>Your execution partner network.</h1><p className="vp-subtitle">See partner status, NDA readiness, capabilities and ratings. Assign partners from the relevant Acquisition or Case record.</p></div><div className="vp-toolbar"><details><summary>Add partner</summary><div className="vp-toolbar-panel"><form action={createPartnerFormAction} className="stack"><div className="grid gap-4 md:grid-cols-2"><input className={input} name="company_name" placeholder="Company name" required/><input className={input} name="country" placeholder="Country"/><input className={input} name="contact_name" placeholder="Contact name"/><input className={input} name="email" type="email" placeholder="Email"/><input className={input} name="phone" placeholder="Phone"/><select className={input} name="status" defaultValue="prospective"><option value="prospective">Prospective</option><option value="approved">Approved</option><option value="suspended">Suspended</option><option value="inactive">Inactive</option></select><select className={input} name="nda_signed" defaultValue="false"><option value="false">NDA not signed</option><option value="true">NDA signed</option></select><input className={input} name="rating" type="number" min="0" max="5" step="0.1" placeholder="Rating"/></div><textarea className={input} name="services" required rows={3} placeholder="Capabilities and services"/><textarea className={input} name="notes" rows={3} placeholder="Notes"/><button className="button">Add partner</button></form></div></details></div></header>
    {params.created?<div className="vp-callout"><strong>Partner added</strong><p>The partner is now available in your directory.</p></div>:null}{params.error?<div className="vp-callout"><strong>Partner could not be added</strong><p>Please review the details and try again.</p></div>:null}
    <section className="vp-object vp-object--hero"><p className="vp-label">Overview</p><div className="vp-compact-metrics"><div className="vp-metric"><span>Total partners</span><strong>{partners.length}</strong></div><div className="vp-metric"><span>Approved</span><strong>{approved}</strong></div><div className="vp-metric"><span>NDA ready</span><strong>{ndaReady}</strong></div></div></section>
    <section><div className="vp-section-title"><div><p className="vp-label">Partner directory</p><h2>Execution partners</h2></div></div><div className="vp-list">{partners.length===0?<div className="vp-empty">No execution partners yet.</div>:partners.map(p=><article className="vp-row" key={p.id}><div><h3>{p.company_name}</h3><p>{p.services || 'Capabilities not recorded'}</p></div><div className="vp-row-status">{workspaceLabel(p.status)} · {p.nda_signed?'NDA ready':'NDA needed'}</div><div><strong>{p.rating!==null?`${p.rating}/5`:'Not rated'}</strong></div></article>)}</div></section>
  </section>;
}
