import Link from 'next/link';
import { redirect } from 'next/navigation';
import { requireUserContext } from '@/lib/auth/context';
import { listClientQuotes } from '@/lib/repositories/workflow';
import { listLeads } from '@/lib/repositories/leads';
import { createProjectFormAction } from '../workflow-actions';
import { normaliseProjectStage, projectStageMeta } from '@/lib/projects/stages';
import { resolveFinancialGate } from '@/lib/finance/state';
import { ProductEmptyState, ProductFilterBar, ProductMetric, ProductMetrics, ProductPageHeader, ProductSectionHeader, ProductStatus, type ProductTone } from '@/components/workspace/ProductUI';

const input='border border-white/10 rounded-lg bg-white px-3 py-2 text-black';
const PAGE_SIZE=25;
type View='all'|'attention'|'mobilisation'|'delivery'|'client_review'|'closeout'|'closed';
type QueueRow={id:string;project_number:string;title:string;project_status:string;project_stage:string;start_date:string|null;due_date:string|null;created_at:string;total_count:number|string};
const viewMeta:Record<View,{label:string;description:string}>={all:{label:'All active',description:'Every current project.'},attention:{label:'Needs attention',description:'Projects with a live blocker, overdue date or unresolved exception.'},mobilisation:{label:'Mobilisation',description:'Accepted work not yet authorised for execution.'},delivery:{label:'In delivery',description:'Projects in execution and technical review.'},client_review:{label:'Client review',description:'Projects waiting on client-facing review or issue.'},closeout:{label:'Closeout',description:'Completion-stage work waiting for closure.'},closed:{label:'Closed',description:'Completed historical project records.'}};
function href(view:View,page=1,q=''){const p=new URLSearchParams();if(view!=='all')p.set('view',view);if(page>1)p.set('page',String(page));if(q)p.set('q',q);const s=p.toString();return `/workspace/projects${s?`?${s}`:''}`}
function formatDate(value:string|null){if(!value)return 'Not set';const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}
function money(value:unknown,currency='GBP'){try{return new Intl.NumberFormat('en-GB',{style:'currency',currency,maximumFractionDigits:0}).format(Number(value||0))}catch{return `${currency} ${Number(value||0).toFixed(0)}`}}
function stageTone(attention:boolean,stage:string):ProductTone{if(attention)return 'attention';if(stage==='closed')return 'complete';return 'active'}

export default async function Page({searchParams}:{searchParams?:Promise<Record<string,string|undefined>>}){
  const params=searchParams?await searchParams:{};if(params.project)redirect(`/workspace/projects/${params.project}`);const requested=String(params.view||'all');const view=(Object.keys(viewMeta).includes(requested)?requested:'all') as View;const q=String(params.q||'').trim();const requestedPage=Number.parseInt(String(params.page||'1'),10);const page=Number.isFinite(requestedPage)&&requestedPage>0?requestedPage:1;const {supabase,organisationId}=await requireUserContext();
  const [{data,error},quotes,leads]=await Promise.all([supabase.rpc('op_project_queue',{p_organisation_id:organisationId,p_view:view==='attention'?'all':view==='mobilisation'?'all':view==='client_review'?'delivery':view,p_limit:200,p_offset:0}),listClientQuotes(supabase,organisationId),listLeads(supabase,organisationId)]);if(error)throw new Error(`Project queue could not be loaded: ${error.message}`);const baseRows=(data||[]) as QueueRow[];const ids=baseRows.map(r=>r.id);
  const [projectDetails,taskRows,deliveryRows]=await Promise.all([ids.length?supabase.from('projects').select('id,project_manager_id,due_date,project_stage,quote_id, project_manager:profiles(full_name), lead:leads(company_name), quote:quotes(total,currency)').eq('organisation_id',organisationId).in('id',ids):Promise.resolve({data:[] as any[]}),ids.length?supabase.from('tasks').select('entity_id,status').eq('organisation_id',organisationId).eq('entity_type','project').in('entity_id',ids):Promise.resolve({data:[] as any[]}),ids.length?supabase.from('project_delivery_items').select('project_id,status,due_date').eq('organisation_id',organisationId).in('project_id',ids):Promise.resolve({data:[] as any[]})]);
  const detailMap=new Map((projectDetails.data||[]).map((p:any)=>[p.id,p]));const taskMap=new Map<string,{open:number;blocked:number}>();for(const t of taskRows.data||[]){const key=String((t as any).entity_id);const current=taskMap.get(key)||{open:0,blocked:0};if(!['completed','cancelled'].includes(String((t as any).status)))current.open++;if(String((t as any).status)==='blocked')current.blocked++;taskMap.set(key,current)}const deliveryMap=new Map<string,{open:number;blocked:number;overdue:number}>();const now=Date.now();for(const d of deliveryRows.data||[]){const key=String((d as any).project_id);const current=deliveryMap.get(key)||{open:0,blocked:0,overdue:0};if(!['complete','cancelled'].includes(String((d as any).status)))current.open++;if(String((d as any).status)==='blocked')current.blocked++;if((d as any).due_date&&!['complete','cancelled'].includes(String((d as any).status))&&new Date(String((d as any).due_date)).getTime()<now)current.overdue++;deliveryMap.set(key,current)}
  const enriched=await Promise.all(baseRows.map(async row=>{const detail:any=detailMap.get(row.id)||{};const stage=normaliseProjectStage(row.project_stage);const tasks=taskMap.get(row.id)||{open:0,blocked:0};const delivery=deliveryMap.get(row.id)||{open:0,blocked:0,overdue:0};let finance={authorised:true,displayState:'Not required',reason:''};if(stage==='mobilisation'){const result=await supabase.rpc('op_project_financial_gate',{p_project_id:row.id});finance=resolveFinancialGate(result.data)}const overdue=Boolean(row.due_date&&new Date(row.due_date).getTime()<now&&!['closed','completed','cancelled'].includes(String(row.project_status)));const attention=overdue||!finance.authorised||tasks.blocked>0||delivery.blocked>0||delivery.overdue>0;const nextAction=!finance.authorised?'Resolve finance':delivery.blocked||delivery.overdue?'Resolve delivery':tasks.blocked?'Resolve task blocker':stage==='mobilisation'?'Authorise execution':projectStageMeta[stage].action;return {...row,stage,detail,tasks,delivery,finance,overdue,attention,nextAction}}));
  let filtered=enriched;if(view==='attention')filtered=filtered.filter(p=>p.attention);if(view==='mobilisation')filtered=filtered.filter(p=>p.stage==='mobilisation'||p.stage==='ready_for_execution');if(view==='client_review')filtered=filtered.filter(p=>['ready_for_client_issue','issued_to_client','client_review'].includes(p.stage));if(q){const needle=q.toLowerCase();filtered=filtered.filter(p=>[p.project_number,p.title,p.detail?.lead?.company_name,p.detail?.project_manager?.full_name].some(v=>String(v||'').toLowerCase().includes(needle)))}const total=filtered.length;const totalPages=Math.max(1,Math.ceil(total/PAGE_SIZE));const pageRows=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);const attentionCount=enriched.filter(p=>p.attention).length;const mobilisationCount=enriched.filter(p=>p.stage==='mobilisation'||p.stage==='ready_for_execution').length;const deliveryCount=enriched.filter(p=>['in_progress','internal_review','partner_correction','ready_for_client_issue','issued_to_client','client_review'].includes(p.stage)).length;const closeoutCount=enriched.filter(p=>p.stage==='completion').length;

  return <section className="vp-page">
    <ProductPageHeader eyebrow="Work · Projects" title="Project portfolio" description="Triage 20–100+ projects from one operating register. Open Project 360 only when the row shows a decision, blocker or delivery action that needs attention." actions={<details><summary className="button secondary">Administrative exception</summary><div className="vp-toolbar-panel"><form action={createProjectFormAction} className="stack"><div className="grid gap-4 md:grid-cols-2"><select className={input} name="lead_id" required><option value="">Select Case</option>{leads.map(l=><option key={l.id} value={l.id}>{l.title||l.company_name}</option>)}</select><select className={input} name="quote_id"><option value="">No linked quote</option>{quotes.map(qt=><option key={qt.id} value={qt.id}>{qt.quote_number} · {qt.status}</option>)}</select><input className={input} name="project_number" placeholder="OP-PRJ-0001" required/><input className={input} name="title" placeholder="Project title" required/></div><textarea className={input} name="notes" rows={3} placeholder="Reason" required/><button className="button">Create exceptional project</button></form></div></details>} />

    <ProductMetrics label="Project portfolio summary">
      <ProductMetric label="Active portfolio" value={enriched.filter(p=>p.stage!=='closed').length} detail="Current project-owned work" />
      <ProductMetric label="Needs attention" value={attentionCount} detail="Blocked, overdue or off-plan" tone={attentionCount?'attention':'complete'} />
      <ProductMetric label="Mobilisation" value={mobilisationCount} detail="Not yet in execution" tone={mobilisationCount?'waiting':'neutral'} />
      <ProductMetric label="In delivery" value={deliveryCount} detail={`${closeoutCount} currently in closeout`} tone={deliveryCount?'active':'neutral'} />
    </ProductMetrics>

    <ProductFilterBar>
      {(Object.keys(viewMeta) as View[]).map(key=><Link key={key} className={`button ${view===key?'':'secondary'}`} href={href(key,1,q)}>{viewMeta[key].label}</Link>)}
      <form method="get" className="product-toolbar__group" style={{marginLeft:'auto',flex:'1 1 300px',justifyContent:'flex-end'}}>{view!=='all'?<input type="hidden" name="view" value={view}/>:null}<input name="q" type="search" defaultValue={q} placeholder="Search project, customer or owner"/><button className="button secondary">Search</button>{q?<Link className="button secondary" href={href(view)}>Clear</Link>:null}</form>
    </ProductFilterBar>

    <section>
      <ProductSectionHeader eyebrow="Operating register" title={`${total} project${total===1?'':'s'}`} meta={viewMeta[view].description} />
      {pageRows.length===0?<ProductEmptyState title="No projects match this view" description="Change the portfolio filter or clear search to broaden the register." />:<div className="project-portfolio-register">
        <div className="project-portfolio-head" aria-hidden="true"><span>Project</span><span>Stage</span><span>Owner</span><span>Due</span><span>Value</span><span>Delivery</span><span>Finance</span><span>Next action</span></div>
        {pageRows.map((p:any)=><Link className={`project-portfolio-row ${p.attention?'project-portfolio-row--attention':''}`} href={`/workspace/projects/${p.id}`} key={p.id}>
          <div data-label="Project"><strong>{p.project_number}</strong><span>{p.title}</span><small>{p.detail?.lead?.company_name||'Customer not recorded'}</small></div>
          <div data-label="Stage"><ProductStatus tone={stageTone(p.attention,p.stage)}>{projectStageMeta[normaliseProjectStage(String(p.project_stage))].label}</ProductStatus>{p.attention?<small>Needs attention</small>:null}</div>
          <div data-label="Owner"><strong>{p.detail?.project_manager?.full_name||'Unassigned'}</strong></div>
          <div data-label="Due"><strong>{formatDate(p.due_date)}</strong>{p.overdue?<small>Overdue</small>:null}</div>
          <div data-label="Value"><strong>{money(p.detail?.quote?.total,p.detail?.quote?.currency||'GBP')}</strong></div>
          <div data-label="Delivery"><strong>{p.delivery.open} open</strong>{p.delivery.blocked||p.delivery.overdue?<small>{p.delivery.blocked} blocked · {p.delivery.overdue} overdue</small>:<small>On plan</small>}</div>
          <div data-label="Finance"><strong>{normaliseProjectStage(String(p.project_stage))==='mobilisation'?p.finance.displayState:'—'}</strong></div>
          <div data-label="Next action"><strong>{p.nextAction} →</strong></div>
        </Link>)}
      </div>}
      {totalPages>1?<nav className="vp-pagination" style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,marginTop:16}}>{page>1?<Link className="button secondary" href={href(view,page-1,q)}>← Previous</Link>:<span/>}<span style={{color:'var(--saas-muted)',fontSize:11}}>Page {page} of {totalPages}</span>{page<totalPages?<Link className="button secondary" href={href(view,page+1,q)}>Next →</Link>:<span/>}</nav>:null}
    </section>
  </section>;
}
