'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { assertRole, requireUserContext } from '@/lib/auth/context';

const roles=['owner','admin','operator','engineering','commercial','reviewer'] as const;
function required(fd:FormData,key:string){const value=String(fd.get(key)||'').trim();if(!value)throw new Error(`${key.replaceAll('_',' ')} is required.`);return value;}
function int(fd:FormData,key:string,fallback=1){const n=Number(fd.get(key)??fallback);if(!Number.isInteger(n))throw new Error(`${key} must be an integer.`);return n;}
function destination(params:Record<string,string>){return `/workspace/risk?${new URLSearchParams(params).toString()}`;}
function refresh(){revalidatePath('/workspace/risk');revalidatePath('/workspace/intelligence');revalidatePath('/workspace');}
async function audit(supabase:any,org:string,user:string,type:string,id:string,event:string,data:Record<string,unknown>){await supabase.rpc('op_record_activity',{p_organisation_id:org,p_user_id:user,p_entity_type:type,p_entity_id:id,p_event_type:event,p_event_data:data});}

export async function createRiskAction(fd:FormData){let next='/workspace/risk';try{const {supabase,user,profile,organisationId}=await requireUserContext();assertRole(profile.role,[...roles]);const entityType=String(fd.get('entity_type')||'organisation');const entityId=String(fd.get('entity_id')||'')||null;const likelihood=int(fd,'likelihood');const impact=int(fd,'impact');if(likelihood<1||likelihood>5||impact<1||impact>5)throw new Error('Likelihood and impact must be between 1 and 5.');const {data,error}=await supabase.from('risk_register').insert({organisation_id:organisationId,entity_type:entityType,entity_id:entityId,title:required(fd,'title'),category:String(fd.get('category')||'operational'),likelihood,impact,status:'open',owner_id:String(fd.get('owner_id')||'')||null,due_date:String(fd.get('due_date')||'')||null,mitigation:String(fd.get('mitigation')||'').trim()||null,created_by:user.id}).select('id,title').single();if(error||!data)throw new Error(error?.message||'Risk could not be created.');if(entityId)await audit(supabase,organisationId,user.id,entityType==='project'?'project':entityType==='lead'?'lead':'risk',entityId,'risk_created',{riskId:data.id,title:data.title,score:likelihood*impact});refresh();next=destination({updated:'Risk registered.'});}catch(error){next=destination({error:error instanceof Error?error.message:'Risk could not be created.'});}redirect(next);}

export async function actOnRiskAction(fd:FormData){let next='/workspace/risk';try{const {supabase,user,profile,organisationId}=await requireUserContext();assertRole(profile.role,[...roles]);const id=required(fd,'risk_id');const action=required(fd,'risk_action');const targets:Record<string,string>={mitigate:'mitigating',accept:'accepted',close:'closed',reopen:'open'};const target=targets[action];if(!target)throw new Error('Invalid risk action.');const {data:risk,error:readError}=await supabase.from('risk_register').select('id,title,status').eq('organisation_id',organisationId).eq('id',id).single();if(readError||!risk)throw new Error(readError?.message||'Risk not found.');if(action==='reopen'&&!['accepted','closed'].includes(String(risk.status)))throw new Error('Only accepted or closed risks can be reopened.');if(action!=='reopen'&&['closed'].includes(String(risk.status)))throw new Error('Closed risks must be reopened before further action.');const residualRaw=String(fd.get('residual_score')||'').trim();const residual=residualRaw?Number(residualRaw):null;const mitigation=String(fd.get('mitigation')||'').trim();const {error}=await supabase.from('risk_register').update({status:target,residual_score:residual,mitigation:mitigation||undefined,updated_at:new Date().toISOString()}).eq('organisation_id',organisationId).eq('id',id);if(error)throw new Error(error.message);await audit(supabase,organisationId,user.id,'risk',id,`risk_${action}`,{from:risk.status,to:target,residualScore:residual});refresh();next=destination({updated:`Risk ${action==='mitigate'?'moved into mitigation':action==='accept'?'accepted':action==='close'?'closed':'reopened'}.`});}catch(error){next=destination({error:error instanceof Error?error.message:'Risk action failed.'});}redirect(next);}

export async function createComplianceAction(fd:FormData){let next='/workspace/risk';try{const {supabase,user,profile,organisationId}=await requireUserContext();assertRole(profile.role,[...roles]);const {error}=await supabase.from('compliance_register').insert({organisation_id:organisationId,entity_type:String(fd.get('entity_type')||'organisation'),entity_id:String(fd.get('entity_id')||'')||null,control_type:required(fd,'control_type'),title:required(fd,'title'),status:'missing',effective_date:String(fd.get('effective_date')||'')||null,expiry_date:String(fd.get('expiry_date')||'')||null,evidence_document_id:String(fd.get('evidence_document_id')||'')||null,owner_id:String(fd.get('owner_id')||'')||null,notes:String(fd.get('notes')||'').trim()||null,created_by:user.id});if(error)throw new Error(error.message);refresh();next=destination({updated:'Compliance control registered.'});}catch(error){next=destination({error:error instanceof Error?error.message:'Compliance control could not be created.'});}redirect(next);}

export async function actOnComplianceAction(fd:FormData){let next='/workspace/risk';try{const {supabase,user,profile,organisationId}=await requireUserContext();assertRole(profile.role,[...roles]);const id=required(fd,'compliance_id');const action=required(fd,'compliance_action');const {data:control,error:readError}=await supabase.from('compliance_register').select('id,title,status,evidence_document_id,expiry_date').eq('organisation_id',organisationId).eq('id',id).single();if(readError||!control)throw new Error(readError?.message||'Compliance control not found.');let target:string;if(action==='confirm_valid'){if(!control.evidence_document_id)throw new Error('Valid compliance requires governed evidence. Link evidence before confirming validity.');target='valid';}else if(action==='waive'){assertRole(profile.role,['owner','admin']);target='waived';}else if(action==='mark_pending'){target='pending';}else throw new Error('Invalid compliance action.');const expiry=String(fd.get('expiry_date')||control.expiry_date||'')||null;const {error}=await supabase.from('compliance_register').update({status:target,expiry_date:expiry,notes:String(fd.get('notes')||'').trim()||null,updated_at:new Date().toISOString()}).eq('organisation_id',organisationId).eq('id',id);if(error)throw new Error(error.message);await audit(supabase,organisationId,user.id,'compliance',id,`compliance_${action}`,{from:control.status,to:target,evidenceDocumentId:control.evidence_document_id});refresh();next=destination({updated:action==='confirm_valid'?'Compliance evidence confirmed.':action==='waive'?'Compliance requirement waived.':'Compliance marked pending.'});}catch(error){next=destination({error:error instanceof Error?error.message:'Compliance action failed.'});}redirect(next);}

// Compatibility-only handlers retained for old forms/links; normal operator UI uses the business actions above.
export async function updateRiskStatusAction(fd:FormData){let next='/workspace/risk';try{const {supabase,profile,organisationId}=await requireUserContext();assertRole(profile.role,['owner','admin']);const id=required(fd,'risk_id');const status=required(fd,'status');const residualRaw=String(fd.get('residual_score')||'').trim();const residual=residualRaw?Number(residualRaw):null;const {error}=await supabase.from('risk_register').update({status,residual_score:residual,mitigation:String(fd.get('mitigation')||'').trim()||null,updated_at:new Date().toISOString()}).eq('organisation_id',organisationId).eq('id',id);if(error)throw new Error(error.message);refresh();next=destination({updated:'Administrative risk repair saved.'});}catch(error){next=destination({error:error instanceof Error?error.message:'Risk could not be updated.'});}redirect(next);}
export async function updateComplianceStatusAction(fd:FormData){let next='/workspace/risk';try{const {supabase,profile,organisationId}=await requireUserContext();assertRole(profile.role,['owner','admin']);const id=required(fd,'compliance_id');const {error}=await supabase.from('compliance_register').update({status:required(fd,'status'),expiry_date:String(fd.get('expiry_date')||'')||null,notes:String(fd.get('notes')||'').trim()||null,updated_at:new Date().toISOString()}).eq('organisation_id',organisationId).eq('id',id);if(error)throw new Error(error.message);refresh();next=destination({updated:'Administrative compliance repair saved.'});}catch(error){next=destination({error:error instanceof Error?error.message:'Compliance control could not be updated.'});}redirect(next);}
