import Link from 'next/link';
import { requireUserContext } from '@/lib/auth/context';
import { ActionDialog, EvidenceRow } from '@/components/workspace/InteractionPrimitives';
import { createComplianceAction, createRiskAction, actOnComplianceAction, actOnRiskAction } from './actions';

function score(l:unknown,i:unknown){return Number(l||0)*Number(i||0)}
function band(value:number){if(value>=16)return 'Critical';if(value>=12)return 'High';if(value>=6)return 'Medium';return 'Low';}
function date(value:unknown){if(!value)return '—';return new Date(String(value)).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});}
function riskState(status:string){if(status==='open')return 'Needs decision';if(status==='mitigating')return 'Mitigation underway';if(status==='accepted')return 'Accepted';if(status==='closed')return 'Closed';return status.replaceAll('_',' ')}
function complianceState(status:string,expired:boolean,dueSoon:boolean){if(expired)return 'Expired';if(dueSoon&&status==='valid')return 'Due soon';if(status==='missing')return 'Evidence missing';if(status==='pending')return 'Evidence pending';if(status==='valid')return 'Valid';if(status==='waived')return 'Waived';return status.replaceAll('_',' ')}

function RiskAction({risk,action,label,primary=false}:{risk:any;action:'mitigate'|'accept'|'close'|'reopen';label:string;primary?:boolean}){
  const description=action==='mitigate'?'Record that active mitigation is now underway.':action==='accept'?'Record the business decision to accept this risk at its current assessed exposure.':action==='close'?'Close this risk only when the underlying exposure no longer requires active treatment.':'Reopen this risk because active treatment or reassessment is required again.';
  return <ActionDialog title={`${label} risk · ${risk.title}`} triggerLabel={label} triggerTone={primary?'primary':'secondary'} description={description}><div className="stack"><div className="op-evidence-list"><EvidenceRow label="Risk" value={risk.title}/><EvidenceRow label="Current state" value={riskState(risk.status)}/><EvidenceRow label="Exposure" value={`${band(score(risk.likelihood,risk.impact))} · score ${score(risk.likelihood,risk.impact)}`}/></div><form action={actOnRiskAction}><input type="hidden" name="risk_id" value={risk.id}/><input type="hidden" name="risk_action" value={action}/><button className="button" type="submit">Confirm {label.toLowerCase()}</button></form></div></ActionDialog>;
}

function ComplianceAction({item,action,label,disabled=false,primary=false}:{item:any;action:'confirm_valid'|'mark_pending'|'waive';label:string;disabled?:boolean;primary?:boolean}){
  const description=action==='confirm_valid'?'Confirm valid only when the required governed evidence is linked and current.':action==='mark_pending'?'Record that this control is waiting for evidence or completion.':'Waive this compliance requirement only through an explicit governed business decision.';
  return <ActionDialog title={`${label} · ${item.title}`} triggerLabel={label} triggerTone={primary?'primary':'secondary'} disabled={disabled} description={description}><div className="stack"><div className="op-evidence-list"><EvidenceRow label="Requirement" value={item.title}/><EvidenceRow label="Current state" value={complianceState(item.status,false,false)}/><EvidenceRow label="Evidence" value={item.evidence_document_id?'Controlled evidence linked':'No controlled evidence linked'} tone={item.evidence_document_id?'complete':'attention'}/></div><form action={actOnComplianceAction}><input type="hidden" name="compliance_id" value={item.id}/><input type="hidden" name="compliance_action" value={action}/><button className="button" type="submit">Confirm {label.toLowerCase()}</button></form></div></ActionDialog>;
}

export default async function RiskPage({searchParams}:{searchParams?:Promise<Record<string,string|undefined>>}){
  const params=searchParams?await searchParams:{};const {supabase,organisationId}=await requireUserContext();
  const [risksResult,complianceResult,projectsResult,partnersResult,membersResult,documentsResult]=await Promise.all([
    supabase.from('risk_register').select('*').eq('organisation_id',organisationId).order('created_at',{ascending:false}).limit(200),
    supabase.from('compliance_register').select('*').eq('organisation_id',organisationId).order('created_at',{ascending:false}).limit(200),
    supabase.from('projects').select('id,project_number,title').eq('organisation_id',organisationId).order('created_at',{ascending:false}).limit(100),
    supabase.from('partners').select('id,company_name').eq('organisation_id',organisationId).order('company_name'),
    supabase.from('profiles').select('id,full_name,role').eq('organisation_id',organisationId).eq('is_active',true).order('full_name'),
    supabase.from('documents').select('id,reference,title,status').eq('organisation_id',organisationId).in('status',['approved','issued']).order('created_at',{ascending:false}).limit(100),
  ]);
  const risks=risksResult.data||[];const compliance=complianceResult.data||[];const projects=projectsResult.data||[];const partners=partnersResult.data||[];const members=membersResult.data||[];const documents=documentsResult.data||[];
  const open=risks.filter(r=>['open','mitigating'].includes(r.status));const critical=open.filter(r=>score(r.likelihood,r.impact)>=16);const high=open.filter(r=>score(r.likelihood,r.impact)>=12);
  const today=new Date();const soon=new Date(Date.now()+30*86400000);const exceptions=compliance.filter(c=>['missing','expired'].includes(c.status)||(c.expiry_date&&new Date(c.expiry_date)<=soon));

  const createRisk=<ActionDialog title="Register risk" triggerLabel="Add risk" description="Create an explicit off-plan risk. Normal client, Partner or review waiting must not be represented as a risk."><form action={createRiskAction} className="stack"><label>Title<input name="title" required/></label><div className="grid gap-4 md:grid-cols-2"><label>Applies to<select name="entity_type" defaultValue="project"><option value="organisation">Organisation</option><option value="project">Project</option><option value="partner">Partner</option><option value="client">Client</option></select></label><label>Record<select name="entity_id" defaultValue=""><option value="">Organisation / unlinked</option><optgroup label="Projects">{projects.map(p=><option key={p.id} value={p.id}>{p.project_number} · {p.title}</option>)}</optgroup><optgroup label="Partners">{partners.map(p=><option key={p.id} value={p.id}>{p.company_name}</option>)}</optgroup></select></label><label>Category<select name="category" defaultValue="operational"><option value="commercial">Commercial</option><option value="technical">Technical</option><option value="delivery">Delivery</option><option value="financial">Financial</option><option value="client">Client</option><option value="partner">Partner</option><option value="operational">Operational</option><option value="compliance">Compliance</option><option value="security">Security</option></select></label><label>Owner<select name="owner_id"><option value="">Unassigned</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name||m.role}</option>)}</select></label><label>Likelihood (1–5)<input type="number" min="1" max="5" name="likelihood" defaultValue="2" required/></label><label>Impact (1–5)<input type="number" min="1" max="5" name="impact" defaultValue="2" required/></label><label>Due date<input type="date" name="due_date"/></label></div><label>Initial mitigation<textarea name="mitigation" rows={3}/></label><button className="button">Register risk</button></form></ActionDialog>;

  const createCompliance=<ActionDialog title="Add compliance requirement" triggerLabel="Add requirement" description="Register the control requirement and its evidence relationship. Status is governed later through contextual business actions."><form action={createComplianceAction} className="stack"><label>Type<input name="control_type" placeholder="NDA, insurance, GDPR, retention..." required/></label><label>Title<input name="title" required/></label><div className="grid gap-4 md:grid-cols-2"><label>Applies to<select name="entity_type" defaultValue="organisation"><option value="organisation">Organisation</option><option value="project">Project</option><option value="partner">Partner</option><option value="client">Client</option></select></label><label>Record<select name="entity_id"><option value="">Organisation / unlinked</option><optgroup label="Projects">{projects.map(p=><option key={p.id} value={p.id}>{p.project_number} · {p.title}</option>)}</optgroup><optgroup label="Partners">{partners.map(p=><option key={p.id} value={p.id}>{p.company_name}</option>)}</optgroup></select></label><label>Owner<select name="owner_id"><option value="">Unassigned</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name||m.role}</option>)}</select></label><label>Effective date<input type="date" name="effective_date"/></label><label>Expiry date<input type="date" name="expiry_date"/></label></div><label>Evidence document<select name="evidence_document_id"><option value="">No linked document yet</option>{documents.map(d=><option key={d.id} value={d.id}>{d.reference} · {d.title}</option>)}</select></label><label>Notes<textarea name="notes" rows={3}/></label><button className="button">Register requirement</button></form></ActionDialog>;

  return <section className="vp-page">
    <header className="vp-header"><div><p className="vp-kicker">Risk & compliance</p><h1>See what needs attention before it becomes a problem.</h1><p className="vp-subtitle">Off-plan risks and compliance evidence stay explicit, while database states are driven by business actions.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{createRisk}{createCompliance}</div></header>
    {params.updated?<div className="vp-callout"><strong>Updated</strong><p>{params.updated}</p></div>:null}{params.error?<div className="vp-callout"><strong>Action could not be completed</strong><p>{params.error}</p></div>:null}
    <section className="vp-object vp-object--hero"><p className="vp-label">Overview</p><div className="vp-compact-metrics"><div className="vp-metric"><span>Open risks</span><strong>{open.length}</strong></div><div className="vp-metric"><span>High / critical</span><strong>{high.length}</strong></div><div className="vp-metric"><span>Critical</span><strong>{critical.length}</strong></div><div className="vp-metric"><span>Compliance issues</span><strong>{exceptions.length}</strong></div></div></section>

    <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:20}}>
      <section className="card" style={{width:'100%'}}>
        <div className="vp-section-title"><div><p className="vp-label">Risks</p><h2>Open risks</h2></div></div>
        <div className="vp-list" style={{marginTop:16}}>{risks.slice(0,20).map(r=>{const riskScore=score(r.likelihood,r.impact);return <div className="vp-row" key={r.id}><div><strong>{r.title}</strong><p>{r.category} · {band(riskScore)} · score {riskScore}</p></div><div className="vp-row-status">{riskState(r.status)}</div><div><small>Due</small><strong style={{display:'block'}}>{date(r.due_date)}</strong></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{r.status==='open'?<RiskAction risk={r} action="mitigate" label="Mitigate" primary/>:null}{['open','mitigating'].includes(r.status)?<><RiskAction risk={r} action="accept" label="Accept"/><RiskAction risk={r} action="close" label="Close"/></>:null}{['accepted','closed'].includes(r.status)?<RiskAction risk={r} action="reopen" label="Reopen"/>:null}</div></div>})}</div>
      </section>

      <section className="card" style={{width:'100%'}}>
        <div className="vp-section-title"><div><p className="vp-label">Compliance</p><h2>Requirements and expiry</h2></div></div>
        <div className="vp-list" style={{marginTop:16}}>{compliance.slice(0,20).map(c=>{const expired=Boolean(c.expiry_date&&new Date(c.expiry_date)<today);const dueSoon=Boolean(c.expiry_date&&new Date(c.expiry_date)<=soon);return <div className="vp-row" key={c.id}><div><strong>{c.title}</strong><p>{c.control_type}{c.evidence_document_id?' · Evidence linked':' · Evidence required'}</p></div><div className="vp-row-status">{complianceState(c.status,expired,dueSoon)}</div><div><small>Expiry</small><strong style={{display:'block'}}>{date(c.expiry_date)}</strong></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{!['valid','waived'].includes(c.status)?<><ComplianceAction item={c} action="confirm_valid" label="Confirm valid" primary disabled={!c.evidence_document_id}/><ComplianceAction item={c} action="mark_pending" label="Mark pending"/></>:null}{c.status!=='waived'?<ComplianceAction item={c} action="waive" label="Waive"/>:null}</div></div>})}</div>
      </section>
    </div>
    <p><Link href="/workspace/intelligence">View these items in Executive →</Link></p>
  </section>;
}
