import Link from 'next/link';
import { requireUserContext } from '@/lib/auth/context';
import { approvePartnerPayableAction, createInvoiceAction, createPartnerPayableAction, issueInvoiceAction, recordClientPaymentAction, recordPartnerPaymentAction, setCommercialTermsAction } from './actions';

function money(value:unknown,currency='GBP'){const amount=Number(value||0);try{return new Intl.NumberFormat('en-GB',{style:'currency',currency}).format(amount)}catch{return `${currency} ${amount.toFixed(2)}`}}
function date(value:unknown){if(!value)return '—';const d=new Date(String(value));return Number.isNaN(d.getTime())?String(value):d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}

export default async function CommercialControlPage({searchParams}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){
  const params=searchParams?await searchParams:{};
  const selectedProject=String(params.project||'');
  const {supabase,organisationId}=await requireUserContext();
  const [projectsResult,invoicesResult,paymentsResult,payablesResult,partnerPaymentsResult,partnersResult,termsResult]=await Promise.all([
    supabase.from('projects').select('id,project_number,title,status,project_stage,lead_id,quote_id,quotes(total,currency,status)').eq('organisation_id',organisationId).order('created_at',{ascending:false}).limit(100),
    supabase.from('invoices').select('*').eq('organisation_id',organisationId).order('created_at',{ascending:false}).limit(100),
    supabase.from('payments').select('*').eq('organisation_id',organisationId).eq('status','cleared').order('paid_at',{ascending:false}).limit(100),
    supabase.from('partner_payables').select('*,partners(company_name)').eq('organisation_id',organisationId).order('created_at',{ascending:false}).limit(100),
    supabase.from('partner_payments').select('*').eq('organisation_id',organisationId).eq('status','cleared').order('paid_at',{ascending:false}).limit(100),
    supabase.from('partners').select('id,company_name,status').eq('organisation_id',organisationId).order('company_name'),
    supabase.from('commercial_terms').select('*').eq('organisation_id',organisationId),
  ]);
  const projects=projectsResult.data||[];const invoices=invoicesResult.data||[];const payments=paymentsResult.data||[];const payables=payablesResult.data||[];const partnerPayments=partnerPaymentsResult.data||[];const partners=partnersResult.data||[];const terms=termsResult.data||[];
  const projectId=selectedProject||String(projects[0]?.id||'');const project=projects.find(p=>p.id===projectId);const projectTerms=terms.find(t=>t.project_id===projectId);
  let gate:any=null;if(projectId){const result=await supabase.rpc('op_project_financial_gate',{p_project_id:projectId});gate=result.data;}
  const invoiced=invoices.filter(i=>!['draft','cancelled','refunded'].includes(i.status)).reduce((sum,i)=>sum+Number(i.total||0),0);
  const collected=payments.reduce((sum,p)=>sum+Number(p.amount||0),0);
  const outstanding=Math.max(0,invoiced-collected);
  const partnerCommitted=payables.filter(p=>['approved','scheduled','paid'].includes(p.status)).reduce((sum,p)=>sum+Number(p.total||0),0);
  const partnerPaid=partnerPayments.reduce((sum,p)=>sum+Number(p.amount||0),0);
  const overdue=invoices.filter(i=>['issued','part_paid','overdue'].includes(i.status)&&i.due_date&&new Date(i.due_date)<new Date()).length;

  return <section className="vp-page">
    <header className="vp-header"><div><p className="vp-kicker">Commercial control</p><h1>Cash, commitments and financial authorisation.</h1><p className="vp-subtitle">Client receivables, partner liabilities and mobilisation authority are controlled against the same project record.</p></div></header>
    {params.updated||params.created?<div className="vp-callout"><strong>Commercial control updated</strong><p>{String(params.updated||params.created)}</p></div>:null}
    {params.error?<div className="vp-callout"><strong>Action could not be completed</strong><p>{String(params.error)}</p></div>:null}

    <section className="vp-object vp-object--hero"><p className="vp-label">Financial position</p><div className="vp-compact-metrics">
      <div className="vp-metric"><span>Invoiced</span><strong>{money(invoiced)}</strong></div><div className="vp-metric"><span>Collected</span><strong>{money(collected)}</strong></div><div className="vp-metric"><span>Receivables</span><strong>{money(outstanding)}</strong></div><div className="vp-metric"><span>Partner committed</span><strong>{money(partnerCommitted)}</strong></div><div className="vp-metric"><span>Partner paid</span><strong>{money(partnerPaid)}</strong></div><div className="vp-metric"><span>Overdue invoices</span><strong>{overdue}</strong></div>
    </div></section>

    <section className="card" style={{width:'100%'}}><div className="vp-section-title"><div><p className="vp-label">Project commercial gate</p><h2>Financial authorisation</h2></div><form method="get"><select name="project" defaultValue={projectId} onChange={undefined}><option value="">Select project</option>{projects.map(p=><option value={p.id} key={p.id}>{p.project_number} · {p.title}</option>)}</select><button className="button secondary">Open</button></form></div>
      {project?<div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(320px,.8fr)',gap:20,marginTop:18}}>
        <div><p className="vp-label">{project.project_number}</p><h3>{project.title}</h3><div className="vp-compact-metrics"><div className="vp-metric"><span>Gate</span><strong>{gate?.authorised?'Authorised':'Blocked'}</strong></div><div className="vp-metric"><span>Basis</span><strong>{String(gate?.basis||'Not set').replaceAll('_',' ')}</strong></div><div className="vp-metric"><span>Required</span><strong>{money(gate?.required||0)}</strong></div><div className="vp-metric"><span>Received</span><strong>{money(gate?.received||0)}</strong></div></div><p style={{marginTop:14}}>{gate?.reason||'Commercial terms have not been configured.'}</p><Link href={`/workspace/projects/${project.id}`}>Open Project 360 →</Link></div>
        <details className="vp-disclosure" open={!gate?.authorised}><summary>Configure commercial terms</summary><form action={setCommercialTermsAction} className="stack" style={{paddingTop:16}}><input type="hidden" name="project_id" value={project.id}/><input type="hidden" name="quote_id" value={String(project.quote_id||'')}/><label>Authorisation basis<select name="authorisation_basis" defaultValue={projectTerms?.authorisation_basis||'deposit'}><option value="deposit">Deposit received</option><option value="po">Purchase order</option><option value="credit">Approved credit terms</option><option value="manual">Manual finance override</option><option value="none">No pre-mobilisation payment condition</option></select></label><div className="grid gap-4 md:grid-cols-2"><label>Payment terms (days)<input type="number" min="0" name="payment_terms_days" defaultValue={projectTerms?.payment_terms_days??30}/></label><label>Deposit %<input type="number" min="0" max="100" step="0.01" name="deposit_percent" defaultValue={projectTerms?.deposit_percent??0}/></label><label>Required deposit amount<input type="number" min="0" step="0.01" name="deposit_required_amount" defaultValue={projectTerms?.deposit_required_amount??0}/></label><label>PO number<input name="po_number" defaultValue={projectTerms?.po_number||''}/></label></div><label><input style={{width:'auto'}} type="checkbox" name="credit_approved" defaultChecked={Boolean(projectTerms?.credit_approved)}/> Credit approved</label><label>Override / authorisation reason<textarea name="override_reason" rows={3} defaultValue={projectTerms?.override_reason||''}/></label><button className="button">Save commercial terms</button></form></details>
      </div>:<p style={{marginTop:18}}>Select a project to inspect its financial gate.</p>}
    </section>

    <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:20}}>
      <section className="card" style={{width:'100%'}}><p className="vp-label">Receivables</p><h2>Client invoices</h2><details className="vp-disclosure"><summary>Create invoice</summary><form action={createInvoiceAction} className="stack" style={{paddingTop:16}}><label>Project<select name="project_id" required defaultValue={projectId}><option value="">Select project</option>{projects.map(p=><option value={p.id} key={p.id}>{p.project_number} · {p.title}</option>)}</select></label><div className="grid gap-4 md:grid-cols-2"><label>Type<select name="invoice_type" defaultValue="milestone"><option value="deposit">Deposit</option><option value="milestone">Milestone</option><option value="final">Final</option><option value="credit_note">Credit note</option></select></label><label>Subtotal<input type="number" step="0.01" min="0" name="subtotal" required/></label><label>VAT rate<input type="number" step="0.01" min="0" name="vat_rate" defaultValue="20"/></label><label>Due date<input type="date" name="due_date" required/></label></div><label>Description<textarea name="description" rows={2}/></label><input type="hidden" name="currency" value="GBP"/><button className="button">Create invoice</button></form></details><div className="vp-list" style={{marginTop:14}}>{invoices.slice(0,12).map(i=><div className="vp-row" key={i.id}><div><strong>{i.invoice_number}</strong><p>{i.invoice_type.replaceAll('_',' ')} · due {date(i.due_date)}</p></div><div className="vp-row-status">{i.status.replaceAll('_',' ')}</div><div><strong>{money(i.total,i.currency)}</strong><small style={{display:'block'}}>{money(i.amount_paid,i.currency)} paid</small></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link className="button secondary" href={`/workspace/commercial-control/invoices/${i.id}`}>Open</Link>{i.status==='draft'?<form action={issueInvoiceAction}><input type="hidden" name="invoice_id" value={i.id}/><button className="button">Issue</button></form>:!['cancelled','refunded','paid'].includes(i.status)?<details><summary>Record payment</summary><form action={recordClientPaymentAction} className="stack"><input type="hidden" name="invoice_id" value={i.id}/><input name="amount" type="number" step="0.01" min="0.01" placeholder="Amount" required/><select name="payment_method" defaultValue="bank_transfer"><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="cash">Cash</option><option value="other">Other</option></select><input name="reference" placeholder="Payment reference"/><button className="button">Record</button></form></details>:null}</div></div>)}</div></section>

      <section className="card" style={{width:'100%'}}><p className="vp-label">Payables</p><h2>Execution partner liabilities</h2><details className="vp-disclosure"><summary>Record partner invoice</summary><form action={createPartnerPayableAction} className="stack" style={{paddingTop:16}}><label>Project<select name="project_id" required defaultValue={projectId}><option value="">Select project</option>{projects.map(p=><option value={p.id} key={p.id}>{p.project_number} · {p.title}</option>)}</select></label><label>Partner<select name="partner_id" required><option value="">Select partner</option>{partners.map(p=><option value={p.id} key={p.id}>{p.company_name}</option>)}</select></label><div className="grid gap-4 md:grid-cols-2"><label>Partner invoice ref<input name="invoice_reference"/></label><label>Subtotal<input type="number" step="0.01" min="0" name="subtotal" required/></label><label>VAT<input type="number" step="0.01" min="0" name="vat" defaultValue="0"/></label><label>Due date<input type="date" name="due_date"/></label></div><label><input style={{width:'auto'}} type="checkbox" name="evidence_confirmed"/> Delivery evidence confirmed</label><label>Description<textarea name="description" rows={2}/></label><input type="hidden" name="currency" value="GBP"/><button className="button">Record partner payable</button></form></details><div className="vp-list" style={{marginTop:14}}>{payables.slice(0,12).map(p=><div className="vp-row" key={p.id}><div><strong>{p.payable_number}</strong><p>{(p.partners as any)?.company_name||'Partner'} · {p.invoice_reference||'No invoice reference'}</p></div><div className="vp-row-status">{p.status}</div><div><strong>{money(p.total,p.currency)}</strong><small style={{display:'block'}}>{money(p.amount_paid,p.currency)} paid</small></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{['received','matched'].includes(p.status)?<form action={approvePartnerPayableAction}><input type="hidden" name="payable_id" value={p.id}/><button className="button" disabled={!p.evidence_confirmed}>Approve</button></form>:null}{['approved','scheduled','paid'].includes(p.status)&&Number(p.amount_paid)<Number(p.total)?<details><summary>Record payment</summary><form action={recordPartnerPaymentAction} className="stack"><input type="hidden" name="payable_id" value={p.id}/><input name="amount" type="number" step="0.01" min="0.01" placeholder="Amount" required/><select name="payment_method" defaultValue="bank_transfer"><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="other">Other</option></select><input name="reference" placeholder="Payment reference"/><button className="button">Record</button></form></details>:null}</div></div>)}</div></section>
    </div>
  </section>;
}
