import Link from 'next/link';
import { requireUserContext } from '@/lib/auth/context';
import { operatorErrorMessage } from '@/lib/workspace/operatorErrors';
import { resolveFinancialGate, resolveInvoiceState, resolvePayableState } from '@/lib/finance/state';
import { approvePartnerPayableAction, createInvoiceAction, createPartnerPayableAction, issueInvoiceAction, recordClientPaymentAction, recordPartnerPaymentAction, setCommercialTermsAction } from './actions';

function money(value:unknown,currency='GBP'){const amount=Number(value||0);try{return new Intl.NumberFormat('en-GB',{style:'currency',currency}).format(amount)}catch{return `${currency} ${amount.toFixed(2)}`}}
function date(value:unknown){if(!value)return '—';const d=new Date(String(value));return Number.isNaN(d.getTime())?String(value):d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}
function positivePage(value:unknown){const n=Number(value||1);return Number.isInteger(n)&&n>0?n:1;}
function pageHref(params:Record<string,string|string[]|undefined>,key:string,value:number){const next=new URLSearchParams();for(const [k,v] of Object.entries(params)){if(v!==undefined&&k!==key){const item=Array.isArray(v)?v[0]:v;if(item)next.set(k,item);}}next.set(key,String(value));return `/workspace/commercial-control?${next.toString()}`;}

export default async function CommercialControlPage({searchParams}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){
  const params=searchParams?await searchParams:{};
  const selectedProject=String(Array.isArray(params.project)?params.project[0]:params.project||'');
  const invoicePage=positivePage(params.invoicePage);const payablePage=positivePage(params.payablePage);const pageSize=25;
  const {supabase,organisationId}=await requireUserContext();

  let invoiceQuery=supabase.from('invoices').select('*',{count:'exact'}).eq('organisation_id',organisationId).order('created_at',{ascending:false});
  let payableQuery=supabase.from('partner_payables').select('*,partners(company_name)',{count:'exact'}).eq('organisation_id',organisationId).order('created_at',{ascending:false});
  if(selectedProject){invoiceQuery=invoiceQuery.eq('project_id',selectedProject);payableQuery=payableQuery.eq('project_id',selectedProject);}

  const [projectsResult,invoicesResult,payablesResult,partnersResult,snapshotResult]=await Promise.all([
    supabase.from('projects').select('id,project_number,title,status,project_stage,lead_id,quote_id').eq('organisation_id',organisationId).order('created_at',{ascending:false}).limit(100),
    invoiceQuery.range((invoicePage-1)*pageSize,invoicePage*pageSize-1),
    payableQuery.range((payablePage-1)*pageSize,payablePage*pageSize-1),
    supabase.from('partners').select('id,company_name,status').eq('organisation_id',organisationId).order('company_name'),
    supabase.rpc('op_executive_snapshot',{p_organisation_id:organisationId}),
  ]);

  let projects=projectsResult.data||[];const invoices=invoicesResult.data||[];const payables=payablesResult.data||[];const partners=partnersResult.data||[];const snapshot=(snapshotResult.data||{}) as Record<string,unknown>;
  if(selectedProject&&!projects.some((p:any)=>p.id===selectedProject)){const targeted=await supabase.from('projects').select('id,project_number,title,status,project_stage,lead_id,quote_id').eq('organisation_id',organisationId).eq('id',selectedProject).maybeSingle();if(targeted.data)projects=[targeted.data,...projects];}
  const projectId=selectedProject||String((projects[0] as any)?.id||'');const project=(projects as any[]).find(p=>p.id===projectId);
  let projectTerms:any=null;let gateRaw:any=null;
  if(projectId){const [termsResult,gateResult]=await Promise.all([supabase.from('commercial_terms').select('*').eq('organisation_id',organisationId).eq('project_id',projectId).maybeSingle(),supabase.rpc('op_project_financial_gate',{p_project_id:projectId})]);projectTerms=termsResult.data;gateRaw=gateResult.data;}
  const gate=resolveFinancialGate(gateRaw);
  const invoiceCount=invoicesResult.count||0;const payableCount=payablesResult.count||0;const invoicePages=Math.max(1,Math.ceil(invoiceCount/pageSize));const payablePages=Math.max(1,Math.ceil(payableCount/pageSize));
  const scoped=Boolean(selectedProject&&project);

  return <section className="vp-page">
    <header className="vp-header"><div>{scoped?<Link href={`/workspace/projects/${project.id}?focus=record-next-action`}>← Back to Project 360</Link>:null}<p className="vp-kicker">Commercial control</p><h1>{scoped?`${project.project_number} · Finance`:'Cash, commitments and financial authorisation.'}</h1><p className="vp-subtitle">{scoped?'Financial authorisation, client invoices and partner liabilities for this project.':'Client receivables, partner liabilities and mobilisation authority across the business.'}</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{scoped?<Link className="button secondary" href="/workspace/commercial-control">View full ledger</Link>:null}<Link className="button secondary" href="/workspace/intelligence">Executive Intelligence</Link></div></header>

    {params.updated||params.created?<div data-continuity-notice className="vp-callout"><strong>Commercial control updated</strong><p>{String(params.updated||params.created)}</p></div>:null}
    {params.error?<div data-continuity-notice className="vp-callout"><strong>Action could not be completed</strong><p>{operatorErrorMessage(String(params.error))}</p></div>:null}
    {snapshotResult.error?<div className="vp-callout"><strong>Financial data layer is not active yet.</strong><p>{operatorErrorMessage(snapshotResult.error.message)}</p></div>:null}

    {!scoped?<section className="vp-object vp-object--hero"><p className="vp-label">Financial position · full ledger</p><div className="vp-compact-metrics"><div className="vp-metric"><span>Invoiced</span><strong>{money(snapshot.invoicedValue)}</strong></div><div className="vp-metric"><span>Collected</span><strong>{money(snapshot.cashCollected)}</strong></div><div className="vp-metric"><span>Receivables</span><strong>{money(snapshot.receivablesOutstanding)}</strong></div><div className="vp-metric"><span>Partner committed</span><strong>{money(snapshot.partnerCommitted)}</strong></div><div className="vp-metric"><span>Partner paid</span><strong>{money(snapshot.partnerPaid)}</strong></div><div className="vp-metric"><span>Overdue invoices</span><strong>{Number(snapshot.overdueInvoices||0)}</strong></div></div></section>:null}

    <section id="financial-gate" className="card" style={{width:'100%'}}>
      <div className="vp-section-title"><div><p className="vp-label">Project financial control</p><h2>Financial authorisation</h2></div><form method="get" style={{display:'flex',gap:8}}><select name="project" defaultValue={projectId}><option value="">Select project</option>{(projects as any[]).map(p=><option value={p.id} key={p.id}>{p.project_number} · {p.title}</option>)}</select><button className="button secondary">Open</button></form></div>
      {project?<div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(320px,.8fr)',gap:20,marginTop:18}}><div><p className="vp-label">{project.project_number}</p><h3>{project.title}</h3><div className="vp-compact-metrics"><div className="vp-metric"><span>Gate</span><strong>{gate.displayState}</strong></div><div className="vp-metric"><span>Basis</span><strong>{gate.basis}</strong></div><div className="vp-metric"><span>Required</span><strong>{money(gate.required)}</strong></div><div className="vp-metric"><span>Received</span><strong>{money(gate.received)}</strong></div>{gate.shortfall>0?<div className="vp-metric"><span>Shortfall</span><strong>{money(gate.shortfall)}</strong></div>:null}</div><p style={{marginTop:14}}>{gate.reason}</p><Link href={`/workspace/projects/${project.id}?focus=record-next-action`}>Return to Project 360 →</Link></div><details className="vp-disclosure" open={!gate.authorised}><summary>Configure commercial terms</summary><form action={setCommercialTermsAction} className="stack" style={{paddingTop:16}}><input type="hidden" name="project_id" value={project.id}/><input type="hidden" name="quote_id" value={String(project.quote_id||'')}/><label>Authorisation basis<select name="authorisation_basis" defaultValue={projectTerms?.authorisation_basis||'deposit'}><option value="deposit">Deposit received</option><option value="po">Purchase order</option><option value="credit">Approved credit terms</option><option value="manual">Manual finance override</option><option value="none">No pre-mobilisation payment condition</option></select></label><div className="grid gap-4 md:grid-cols-2"><label>Payment terms (days)<input type="number" min="0" name="payment_terms_days" defaultValue={projectTerms?.payment_terms_days??30}/></label><label>Deposit %<input type="number" min="0" max="100" step="0.01" name="deposit_percent" defaultValue={projectTerms?.deposit_percent??0}/></label><label>Required deposit amount<input type="number" min="0" step="0.01" name="deposit_required_amount" defaultValue={projectTerms?.deposit_required_amount??0}/></label><label>PO number<input name="po_number" defaultValue={projectTerms?.po_number||''}/></label></div><label><input style={{width:'auto'}} type="checkbox" name="credit_approved" defaultChecked={Boolean(projectTerms?.credit_approved)}/> Credit approved</label><label>Override / authorisation reason<textarea name="override_reason" rows={3} defaultValue={projectTerms?.override_reason||''}/></label><button className="button">Save commercial terms</button></form></details></div>:<p style={{marginTop:18}}>Select a project to inspect its financial gate.</p>}
    </section>

    <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:20}}>
      <section id="receivables" className="card" style={{width:'100%'}}>
        <p className="vp-label">Receivables</p><h2>{scoped?'Project invoices':'Client invoices'}</h2>
        <details className="vp-disclosure"><summary>Create invoice</summary><form action={createInvoiceAction} className="stack" style={{paddingTop:16}}><label>Project<select name="project_id" required defaultValue={projectId}><option value="">Select project</option>{(projects as any[]).map(p=><option value={p.id} key={p.id}>{p.project_number} · {p.title}</option>)}</select></label><div className="grid gap-4 md:grid-cols-2"><label>Type<select name="invoice_type" defaultValue="milestone"><option value="deposit">Deposit</option><option value="milestone">Milestone</option><option value="final">Final</option><option value="credit_note">Credit note</option></select></label><label>Subtotal<input type="number" step="0.01" min="0" name="subtotal" required/></label><label>VAT rate<input type="number" step="0.01" min="0" name="vat_rate" defaultValue="20"/></label><label>Due date<input type="date" name="due_date" required/></label></div><label>Description<textarea name="description" rows={2}/></label><input type="hidden" name="currency" value="GBP"/><button className="button">Create invoice</button></form></details>
        <div className="vp-list" style={{marginTop:14}}>{(invoices as any[]).length===0?<div className="vp-empty">{scoped?'No invoices for this project yet.':'No invoices recorded.'}</div>:(invoices as any[]).map(i=>{const state=resolveInvoiceState(i);return <div id={`invoice-${i.id}`} className="vp-row" key={i.id}><div><strong>{i.invoice_number}</strong><p>{String(i.invoice_type||'invoice').replaceAll('_',' ')} · due {date(i.due_date)}</p></div><div className="vp-row-status">{state.displayStatus}</div><div><strong>{money(i.total,i.currency)}</strong><small style={{display:'block'}}>{money(i.amount_paid,i.currency)} paid · {money(state.balance,i.currency)} outstanding</small></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link className="button secondary" href={`/workspace/commercial-control/invoices/${i.id}`}>Open</Link>{state.canIssue?<form action={issueInvoiceAction}><input type="hidden" name="invoice_id" value={i.id}/><button className="button">Issue</button></form>:null}{state.canRecordPayment?<details><summary>Record payment</summary><form action={recordClientPaymentAction} className="stack"><input type="hidden" name="invoice_id" value={i.id}/><input name="amount" type="number" step="0.01" min="0.01" max={state.balance||undefined} placeholder="Amount" required/><select name="payment_method" defaultValue="bank_transfer"><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="cash">Cash</option><option value="other">Other</option></select><input name="reference" placeholder="Payment reference"/><button className="button">Record</button></form></details>:null}</div></div>})}</div>
        {invoicePages>1?<div style={{display:'flex',justifyContent:'space-between',marginTop:16}}><span>Page {invoicePage} of {invoicePages} · {invoiceCount} invoices</span><div style={{display:'flex',gap:8}}>{invoicePage>1?<Link className="button secondary" href={pageHref(params,'invoicePage',invoicePage-1)}>Previous</Link>:null}{invoicePage<invoicePages?<Link className="button secondary" href={pageHref(params,'invoicePage',invoicePage+1)}>Next</Link>:null}</div></div>:null}
      </section>

      <section id="payables" className="card" style={{width:'100%'}}>
        <p className="vp-label">Payables</p><h2>{scoped?'Project partner liabilities':'Execution partner liabilities'}</h2>
        <details className="vp-disclosure"><summary>Record partner invoice</summary><form action={createPartnerPayableAction} className="stack" style={{paddingTop:16}}><label>Project<select name="project_id" required defaultValue={projectId}><option value="">Select project</option>{(projects as any[]).map(p=><option value={p.id} key={p.id}>{p.project_number} · {p.title}</option>)}</select></label><label>Partner<select name="partner_id" required><option value="">Select partner</option>{(partners as any[]).map(p=><option value={p.id} key={p.id}>{p.company_name}</option>)}</select></label><div className="grid gap-4 md:grid-cols-2"><label>Partner invoice ref<input name="invoice_reference"/></label><label>Subtotal<input type="number" step="0.01" min="0" name="subtotal" required/></label><label>VAT<input type="number" step="0.01" min="0" name="vat" defaultValue="0"/></label><label>Due date<input type="date" name="due_date"/></label></div><label><input style={{width:'auto'}} type="checkbox" name="evidence_confirmed"/> Delivery evidence confirmed</label><label>Description<textarea name="description" rows={2}/></label><input type="hidden" name="currency" value="GBP"/><button className="button">Record partner payable</button></form></details>
        <div className="vp-list" style={{marginTop:14}}>{(payables as any[]).length===0?<div className="vp-empty">{scoped?'No partner liabilities for this project yet.':'No partner liabilities recorded.'}</div>:(payables as any[]).map(p=>{const state=resolvePayableState(p);return <div id={`payable-${p.id}`} className="vp-row" key={p.id}><div><strong>{p.payable_number}</strong><p>{p.partners?.company_name||'Partner'} · {p.invoice_reference||'No invoice reference'}</p>{state.approvalBlockedReason?<small>{state.approvalBlockedReason}</small>:null}</div><div className="vp-row-status">{state.displayStatus}</div><div><strong>{money(p.total,p.currency)}</strong><small style={{display:'block'}}>{money(p.amount_paid,p.currency)} paid · {money(state.balance,p.currency)} outstanding</small></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{['received','matched'].includes(state.status)?<form action={approvePartnerPayableAction}><input type="hidden" name="payable_id" value={p.id}/><button className="button" disabled={!state.canApprove}>Approve</button></form>:null}{state.canRecordPayment?<details><summary>Record payment</summary><form action={recordPartnerPaymentAction} className="stack"><input type="hidden" name="payable_id" value={p.id}/><input name="amount" type="number" step="0.01" min="0.01" max={state.balance||undefined} placeholder="Amount" required/><select name="payment_method" defaultValue="bank_transfer"><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="other">Other</option></select><input name="reference" placeholder="Payment reference"/><button className="button">Record</button></form></details>:null}</div></div>})}</div>
        {payablePages>1?<div style={{display:'flex',justifyContent:'space-between',marginTop:16}}><span>Page {payablePage} of {payablePages} · {payableCount} payables</span><div style={{display:'flex',gap:8}}>{payablePage>1?<Link className="button secondary" href={pageHref(params,'payablePage',payablePage-1)}>Previous</Link>:null}{payablePage<payablePages?<Link className="button secondary" href={pageHref(params,'payablePage',payablePage+1)}>Next</Link>:null}</div></div>:null}
      </section>
    </div>
  </section>;
}
