'use server';

import { redirect } from 'next/navigation';
import { revalidatePath } from 'next/cache';
import { requireUserContext, assertRole } from '@/lib/auth/context';
import { projectStages, type ProjectStage } from '@/lib/projects/stages';
import { assertCanAdvanceProjectStage } from '@/lib/business/invariants';

const roles = ['owner','admin','operator','engineering','commercial'] as const;
function required(formData:FormData,key:string){const value=String(formData.get(key)||'').trim();if(!value)throw new Error(`${key.replaceAll('_',' ')} is required.`);return value;}
function projectUrl(projectId:string,params:Record<string,string>){return `/workspace/projects/${projectId}?${new URLSearchParams(params).toString()}`;}
function refreshProject(projectId:string){revalidatePath(`/workspace/projects/${projectId}`);revalidatePath(`/workspace/projects/${projectId}/delivery`);revalidatePath('/workspace/projects');revalidatePath('/workspace/leads');revalidatePath('/workspace');revalidatePath('/workspace/commercial-control');revalidatePath('/workspace/payments');revalidatePath('/workspace/intelligence');}
async function audit(supabase:any,organisationId:string,userId:string,projectId:string,eventType:string,eventData:Record<string,unknown>){await supabase.from('activity_events').insert({organisation_id:organisationId,entity_type:'project',entity_id:projectId,user_id:userId,event_type:eventType,event_data:eventData});}

export async function updateProjectMobilisationAction(formData:FormData){const projectId=required(formData,'project_id');let destination=`/workspace/projects/${projectId}`;try{const managerId=required(formData,'project_manager_id');const startDate=required(formData,'start_date');const dueDate=required(formData,'due_date');const{supabase,user,profile,organisationId}=await requireUserContext();assertRole(profile.role,[...roles]);const{data:project,error:projectError}=await supabase.from('projects').select('id,project_stage,status').eq('organisation_id',organisationId).eq('id',projectId).single();if(projectError||!project)throw new Error(projectError?.message||'Project not found.');if(String(project.project_stage||'mobilisation')!=='mobilisation')throw new Error('Mobilisation controls can only be changed while the Project is in Mobilisation.');if(['completed','closed','cancelled'].includes(String(project.status)))throw new Error('This Project is no longer operational.');const{error}=await supabase.rpc('op_update_project_mobilisation',{p_organisation_id:organisationId,p_user_id:user.id,p_project_id:projectId,p_project_manager_id:managerId,p_start_date:startDate,p_due_date:dueDate});if(error)throw new Error(error.message);refreshProject(projectId);destination=projectUrl(projectId,{updated:'Mobilisation controls saved.',focus:'record-readiness'});}catch(error){destination=projectUrl(projectId,{error:error instanceof Error?error.message:'Project setup could not be saved.',focus:'record-readiness'});}redirect(destination);}

export async function createProjectActivityAction(formData:FormData){const projectId=required(formData,'project_id');let destination=`/workspace/projects/${projectId}`;try{const{supabase,user,profile,organisationId}=await requireUserContext();assertRole(profile.role,[...roles]);const{data:project,error:projectError}=await supabase.from('projects').select('id,project_stage,status').eq('organisation_id',organisationId).eq('id',projectId).single();if(projectError||!project)throw new Error(projectError?.message||'Project not found.');if(['completed','closed','cancelled'].includes(String(project.status)))throw new Error('Activities cannot be added to a non-operational Project.');const currentStage=String(project.project_stage||'mobilisation');const requestedStage=String(formData.get('project_stage')||currentStage);if(requestedStage!==currentStage)throw new Error('Activity stage must match the Project current stage. Refresh the Project before creating the activity.');const{error}=await supabase.rpc('op_create_project_activity',{p_organisation_id:organisationId,p_user_id:user.id,p_project_id:projectId,p_title:required(formData,'title'),p_activity_type:String(formData.get('activity_type')||'delivery'),p_owner_id:String(formData.get('owner_id')||'')||null,p_due_at:String(formData.get('due_at')||'')||null,p_priority:String(formData.get('priority')||'normal'),p_notes:String(formData.get('notes')||'')||null,p_project_stage:currentStage,p_linked_document_id:String(formData.get('linked_document_id')||'')||null});if(error)throw new Error(error.message);refreshProject(projectId);destination=projectUrl(projectId,{activity:'Activity created.',focus:'record-activities'});}catch(error){destination=projectUrl(projectId,{error:error instanceof Error?error.message:'Activity could not be created.',focus:'record-activities'});}redirect(destination);}

export async function setProjectActivityStatusAction(formData:FormData){const projectId=required(formData,'project_id');let destination=`/workspace/projects/${projectId}`;try{const{supabase,user,profile,organisationId}=await requireUserContext();assertRole(profile.role,[...roles]);const{data:project,error:projectError}=await supabase.from('projects').select('id,status').eq('organisation_id',organisationId).eq('id',projectId).single();if(projectError||!project)throw new Error(projectError?.message||'Project not found.');if(['completed','closed','cancelled'].includes(String(project.status)))throw new Error('Activities on a non-operational Project cannot be changed.');const{error}=await supabase.rpc('op_set_project_activity_status',{p_organisation_id:organisationId,p_user_id:user.id,p_task_id:required(formData,'task_id'),p_status:required(formData,'status')});if(error)throw new Error(error.message);refreshProject(projectId);destination=projectUrl(projectId,{activity:'Activity status updated.',focus:'record-activities'});}catch(error){destination=projectUrl(projectId,{error:error instanceof Error?error.message:'Activity status could not be updated.',focus:'record-activities'});}redirect(destination);}

export async function createProjectDeliveryItemAction(formData:FormData){const projectId=required(formData,'project_id');let destination=`/workspace/projects/${projectId}`;try{const{supabase,user,profile,organisationId}=await requireUserContext();assertRole(profile.role,[...roles]);const[{data:project,error:projectError},{data:assignment,error:assignmentError}]=await Promise.all([supabase.from('projects').select('id,status').eq('organisation_id',organisationId).eq('id',projectId).single(),supabase.from('project_execution_assignments').select('partner_id').eq('organisation_id',organisationId).eq('project_id',projectId).maybeSingle()]);if(projectError||!project)throw new Error(projectError?.message||'Project not found.');if(assignmentError)throw new Error(assignmentError.message);if(['completed','closed','cancelled'].includes(String(project.status)))throw new Error('Delivery items cannot be added to a non-operational Project.');const itemType=String(formData.get('item_type')||'deliverable');if(!['deliverable','milestone','dependency'].includes(itemType))throw new Error('Invalid delivery item type.');const payload={organisation_id:organisationId,project_id:projectId,item_type:itemType,title:required(formData,'title'),description:String(formData.get('description')||'').trim()||null,status:'not_started',priority:String(formData.get('priority')||'normal'),owner_id:String(formData.get('owner_id')||'')||null,partner_id:assignment?.partner_id||null,depends_on_id:String(formData.get('depends_on_id')||'')||null,due_date:String(formData.get('due_date')||'')||null,revision:null,internal_review_status:formData.get('internal_review_required')==='on'?'pending':'not_required',client_review_status:formData.get('client_review_required')==='on'?'pending':'not_required',linked_document_id:String(formData.get('linked_document_id')||'')||null,notes:String(formData.get('notes')||'').trim()||null,created_by:user.id};const{data:item,error}=await supabase.from('project_delivery_items').insert(payload).select('id,title').single();if(error||!item)throw new Error(error?.message||'Delivery item could not be created.');await audit(supabase,organisationId,user.id,projectId,'delivery_item_created',{deliveryItemId:item.id,itemType,title:item.title});refreshProject(projectId);destination=projectUrl(projectId,{activity:`${itemType==='milestone'?'Milestone':itemType==='dependency'?'Dependency':'Deliverable'} created.`,focus:'delivery-control'});}catch(error){destination=projectUrl(projectId,{error:error instanceof Error?error.message:'Delivery item could not be created.',focus:'delivery-control'});}redirect(destination);}

export async function updateProjectDeliveryItemAction(formData:FormData){const projectId=required(formData,'project_id');const itemId=required(formData,'item_id');let destination=`/workspace/projects/${projectId}`;try{const{supabase,user,profile,organisationId}=await requireUserContext();assertRole(profile.role,[...roles]);const{data:item,error:readError}=await supabase.from('project_delivery_items').select('id,project_id,status,title,partner_id,revision,internal_review_status,client_review_status').eq('organisation_id',organisationId).eq('id',itemId).single();if(readError||!item)throw new Error(readError?.message||'Delivery item not found.');if(item.project_id!==projectId)throw new Error('Delivery item does not belong to this Project.');const updates={owner_id:String(formData.get('owner_id')||'')||null,due_date:String(formData.get('due_date')||'')||null,notes:String(formData.get('notes')||'').trim()||null};const{error}=await supabase.from('project_delivery_items').update(updates).eq('organisation_id',organisationId).eq('id',itemId);if(error)throw new Error(error.message);await audit(supabase,organisationId,user.id,projectId,'delivery_item_details_updated',{deliveryItemId:itemId,title:item.title});refreshProject(projectId);destination=projectUrl(projectId,{activity:'Delivery details updated.',focus:`delivery-item-${itemId}`});}catch(error){destination=projectUrl(projectId,{error:error instanceof Error?error.message:'Delivery item could not be updated.',focus:'delivery-control'});}redirect(destination);}

export async function advanceProjectStageAction(formData:FormData){const projectId=String(formData.get('project_id')||'');const submittedStages=formData.getAll('target_stage').map(String);const targetStage=String(submittedStages.at(-1)||'') as ProjectStage;const note=String(formData.get('note')||'').trim();let destination=`/workspace/projects/${projectId}`;if(!projectId||!projectStages.includes(targetStage))redirect(`${destination}?error=${encodeURIComponent('Invalid project stage request.')}&focus=record-next-action`);try{const{supabase,user,profile,organisationId}=await requireUserContext();assertRole(profile.role,[...roles]);await assertCanAdvanceProjectStage(supabase,organisationId,projectId,targetStage);const{error}=await supabase.rpc('op_advance_project_stage',{p_project_id:projectId,p_target_stage:targetStage,p_actor_id:user.id,p_note:note||null});if(error)throw new Error(error.message);refreshProject(projectId);destination=projectUrl(projectId,{advanced:targetStage,focus:targetStage==='closed'?'record-summary':'record-next-action'});}catch(error){destination=projectUrl(projectId,{error:error instanceof Error?error.message:'Project stage could not be advanced.',focus:'record-next-action'});}redirect(destination);}
