import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireUserContext } from '@/lib/auth/context';
import { getProjectById } from '@/lib/repositories/workflow';
import { workspaceLabel } from '@/lib/presentation/vocabulary';
import { normaliseProjectStage, projectStageMeta, projectStages } from '@/lib/projects/stages';
import { advanceProjectStageAction, createProjectActivityAction, setProjectActivityStatusAction, updateProjectMobilisationAction } from './actions';

function value(record: Record<string,unknown>|null|undefined,key:string,fallback='Not recorded'){const entry=record?.[key];return entry===null||entry===undefined||entry===''?fallback:String(entry)}
function money(amount:unknown,currency:unknown){const number=Number(amount??0);try{return new Intl.NumberFormat('en-GB',{style:'currency',currency:String(currency||'GBP')}).format(number)}catch{return `${String(currency||'GBP')} ${number.toFixed(2)}`}}
function formatDate(input:unknown,fallback='Not set'){if(!input)return fallback;const date=new Date(String(input));return Number.isNaN(date.getTime())?String(input):date.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}

type Readiness={ready:boolean;stage:string;reasons:string[];activityTotal:number;activityOpen:number;approvedDocuments:number;issuedDocuments:number};

export default async function ProjectWorkspacePage({params,searchParams}:{params:Promise<{id:string}>;searchParams?:Promise<Record<string,string|undefined>>}){
  const {id}=await params;const query=searchParams?await searchParams:{};const {supabase,organisationId}=await requireUserContext();
  let project;try{project=await getProjectById(supabase,organisationId,id)}catch{notFound()}

  const [tasksResult,documentsResult,activityResult,membersResult,readinessResult]=await Promise.all([
    supabase.from('tasks').select('*').eq('organisation_id',organisationId).eq('entity_type','project').eq('entity_id',id).order('created_at',{ascending:false}),
    supabase.from('documents').select('*').eq('organisation_id',organisationId).eq('project_id',id).order('created_at',{ascending:false}),
    supabase.from('activity_events').select('*').eq('organisation_id',organisationId).eq('entity_type','project').eq('entity_id',id).order('created_at',{ascending:false}).limit(30),
    supabase.from('profiles').select('id,full_name,role').eq('organisation_id',organisationId).order('full_name'),
    supabase.rpc('op_project_stage_readiness',{p_project_id:id}),
  ]);

  const projectRecord=project as typeof project&{project_stage?:string};const stage=normaliseProjectStage(projectRecord.project_stage);const stageMeta=projectStageMeta[stage];const stageIndex=projectStages.indexOf(stage);
  const lead=project.lead as Record<string,unknown>|null|undefined;const quote=project.quote as Record<string,unknown>|null|undefined;const manager=project.project_manager as Record<string,unknown>|null|undefined;
  const tasks=tasksResult.data??[];const documents=documentsResult.data??[];const events=activityResult.data??[];const members=membersResult.data??[];
  const readiness=(readinessResult.data||{ready:false,stage,reasons:['Apply the Project Delivery OS migration to activate governed stage gates.'],activityTotal:tasks.length,activityOpen:tasks.filter(t=>!['completed','cancelled'].includes(t.status)).length,approvedDocuments:0,issuedDocuments:0}) as Readiness;
  const openTasks=tasks.filter(t=>!['completed','cancelled'].includes(t.status));
  const mobilisationControls={manager:Boolean(project.project_manager_id),start:Boolean(project.start_date),due:Boolean(project.due_date)};
  const mobilisationControlsReady=mobilisationControls.manager&&mobilisationControls.start&&mobilisationControls.due;
  const remainingRequirements=readiness.reasons.length;

  return <section className="project-os-page">
    <header className="project-os-header"><div><Link href="/workspace/projects" className="project-os-back">← Back to projects</Link><p className="project-os-reference">{project.project_number}</p><h1>{project.title}</h1><div className="project-os-meta"><span>Project workspace</span><span>Created {formatDate(project.created_at)}</span><span>Last updated {formatDate(project.updated_at)}</span></div></div><section className="project-os-stage-card"><p>Current stage</p><h2>{stageMeta.label}</h2><span className="project-os-health"><i/> {readiness.ready?'Ready to progress':'Gate controlled'}</span><div><small>Stage objective</small><strong>{stageMeta.objective}</strong></div></section></header>

    {query.advanced?<div className="project-os-notice success"><strong>Delivery stage advanced</strong><span>The project is now at {projectStageMeta[normaliseProjectStage(query.advanced)].label}.</span></div>:null}
    {query.updated||query.activity?<div className="project-os-notice success"><strong>{query.updated||query.activity}</strong></div>:null}
    {query.error?<div className="project-os-notice error"><strong>Action could not be completed</strong><span>{query.error}</span></div>:null}

    <section className="project-os-progress-card"><p className="project-os-section-label">Delivery progression</p><div className="project-os-progress-scroll"><ol className="project-os-progress">{projectStages.map((item,index)=>{const state=index<stageIndex?'complete':index===stageIndex?'current':'future';return <li key={item} className={state}><div className="project-os-node"><span>{index+1}</span></div><strong>{projectStageMeta[item].label}</strong>{state==='current'?<small>Current</small>:null}</li>})}</ol></div><div className="project-os-progress-footer"><p>{stageMeta.completion}</p><span>{readiness.activityOpen} open activities · {readiness.approvedDocuments} approved documents · {readiness.issuedDocuments} issued</span></div></section>

    <div className="project-os-decision-grid">
      <section className="project-os-panel project-os-readiness">
        <p className="project-os-section-label">{stage==='mobilisation'?'Mobilisation readiness':'Stage readiness'}</p>

        {stage==='mobilisation'?<>
          <div className="project-os-checklist">
            <div className="project-os-check-row"><span className={`project-os-check-icon ${mobilisationControls.manager?'ready':'missing'}`}>{mobilisationControls.manager?'✓':'!'}</span><div><strong>Project manager</strong><small>{mobilisationControls.manager?value(manager,'full_name','Assigned'):'Assign an accountable project manager.'}</small></div><span className={mobilisationControls.manager?'project-os-ready':'project-os-missing'}>{mobilisationControls.manager?'Saved':'Required'}</span></div>
            <div className="project-os-check-row"><span className={`project-os-check-icon ${mobilisationControls.start?'ready':'missing'}`}>{mobilisationControls.start?'✓':'!'}</span><div><strong>Start date</strong><small>{mobilisationControls.start?formatDate(project.start_date):'Record the planned mobilisation start date.'}</small></div><span className={mobilisationControls.start?'project-os-ready':'project-os-missing'}>{mobilisationControls.start?'Saved':'Required'}</span></div>
            <div className="project-os-check-row"><span className={`project-os-check-icon ${mobilisationControls.due?'ready':'missing'}`}>{mobilisationControls.due?'✓':'!'}</span><div><strong>Due date</strong><small>{mobilisationControls.due?formatDate(project.due_date):'Record the controlled delivery due date.'}</small></div><span className={mobilisationControls.due?'project-os-ready':'project-os-missing'}>{mobilisationControls.due?'Saved':'Required'}</span></div>
          </div>
          <details className="vp-disclosure" open={!mobilisationControlsReady}><summary>{mobilisationControlsReady?'Mobilisation controls saved':'Complete mobilisation controls'}</summary><form action={updateProjectMobilisationAction} className="stack" style={{paddingTop:16}}><input type="hidden" name="project_id" value={id}/><label>Project manager<select name="project_manager_id" required defaultValue={String(project.project_manager_id||'')}><option value="">Select manager</option>{members.map(member=><option key={member.id} value={member.id}>{member.full_name||member.role}</option>)}</select></label><div className="grid gap-4 md:grid-cols-2"><label>Start date<input name="start_date" type="date" required defaultValue={project.start_date?String(project.start_date).slice(0,10):''}/></label><label>Due date<input name="due_date" type="date" required defaultValue={project.due_date?String(project.due_date).slice(0,10):''}/></label></div><button className="button">Save mobilisation controls</button></form></details>
          <div style={{marginTop:18}}><p className="project-os-section-label">Remaining gate requirements</p>{readiness.ready?<div className="project-os-blocker"><div><strong>All evidence requirements are satisfied</strong><p>Operational controls and governed evidence are ready for progression.</p></div></div>:<div className="project-os-checklist">{readiness.reasons.map(reason=><div className="project-os-check-row" key={reason}><span className="project-os-check-icon missing">!</span><div><strong>{reason}</strong><small>This is a stage-gate requirement, separate from the saved mobilisation controls.</small></div><span className="project-os-missing">Outstanding</span></div>)}</div>}</div>
        </>:readiness.ready?<div className="project-os-blocker"><div><strong>All stage requirements are ready</strong><p>The next governed transition is permitted.</p></div></div>:<div className="project-os-checklist">{readiness.reasons.map(reason=><div className="project-os-check-row" key={reason}><span className="project-os-check-icon missing">!</span><div><strong>{reason}</strong><small>Resolve this evidence requirement before progression.</small></div><span className="project-os-missing">Outstanding</span></div>)}</div>}
      </section>

      <section className="project-os-panel project-os-action-panel"><p className="project-os-section-label">Next permitted action</p><div className="project-os-action-icon">→</div><h2>{stageMeta.action}</h2><p>{readiness.ready?'All required evidence exists.':`${remainingRequirements} governed requirement${remainingRequirements===1?'':'s'} remain before this transition is permitted.`}</p>{stageMeta.next?<form action={advanceProjectStageAction}><input type="hidden" name="project_id" value={project.id}/><input type="hidden" name="target_stage" value={stageMeta.next}/><label>Decision note<textarea name="note" rows={3} placeholder="Optional governed transition note"/></label><button className="button" disabled={!readiness.ready}>{stageMeta.action}</button>{stage==='internal_review'?<button className="button secondary" name="target_stage" value="partner_correction" disabled={!readiness.ready}>Request partner correction</button>:null}</form>:<strong>Project closed</strong>}</section>

      <section className="project-os-panel project-os-summary"><p className="project-os-section-label">Project summary</p><dl><div><dt>Customer</dt><dd>{value(lead,'company_name')}</dd></div><div><dt>Case</dt><dd>{value(lead,'title')}</dd></div><div><dt>Manager</dt><dd>{value(manager,'full_name')}</dd></div><div><dt>Dates</dt><dd>{formatDate(project.start_date)} → {formatDate(project.due_date)}</dd></div><div><dt>Commercial value</dt><dd>{quote?money(quote.total,quote.currency):'Not recorded'}</dd></div><div><dt>Quote status</dt><dd>{quote?workspaceLabel(value(quote,'status'),'quote'):'Not recorded'}</dd></div></dl>{project.lead_id?<Link href={`/workspace/leads/${project.lead_id}`}>Open source case →</Link>:null}</section>
    </div>

    <div className="project-os-lower-grid">
      <section className="project-os-panel project-os-documents"><div className="project-os-panel-heading"><p className="project-os-section-label">Controlled documents</p><Link href={`/workspace/documents?project=${id}`}>View project registry</Link></div><div className="project-os-document-list">{documents.length===0?<div className="project-os-empty-row"><span>▤</span><div><strong>No project documents generated</strong><small>Generate stage evidence from the project document workflow.</small></div></div>:documents.slice(0,8).map(document=><div className="project-os-document-row" key={document.id}><span className="project-os-doc-icon">▤</span><div><strong>{document.title}</strong><small>{document.reference}</small></div><span className="project-os-tag">{workspaceLabel(document.status,'document')}</span><small>{formatDate(document.updated_at||document.created_at)}</small><Link className="button secondary" href={`/workspace/documents/${document.id}`}>Open</Link></div>)}</div><p className="project-os-help">Approved and issued documents are evaluated by the current stage gate.</p></section>

      <section className="project-os-panel project-os-activities"><div className="project-os-panel-heading"><p className="project-os-section-label">Delivery activities</p><span>{tasks.length} activities</span></div><details className="vp-disclosure" open={tasks.length===0}><summary>Add delivery activity</summary><form action={createProjectActivityAction} className="stack" style={{paddingTop:16}}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="project_stage" value={stage}/><label>Activity title<input name="title" required/></label><div className="grid gap-4 md:grid-cols-2"><label>Type<select name="activity_type" defaultValue="delivery"><option value="delivery">Delivery</option><option value="internal_review">Internal review</option><option value="partner_correction">Partner correction</option><option value="client_review">Client review</option><option value="closeout">Closeout</option></select></label><label>Owner<select name="owner_id" defaultValue=""><option value="">Unassigned</option>{members.map(member=><option key={member.id} value={member.id}>{member.full_name||member.role}</option>)}</select></label><label>Due date<input name="due_at" type="datetime-local"/></label><label>Priority<select name="priority" defaultValue="normal"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="critical">Critical</option></select></label></div><label>Linked document<select name="linked_document_id" defaultValue=""><option value="">No linked document</option>{documents.map(document=><option key={document.id} value={document.id}>{document.reference} · {document.title}</option>)}</select></label><label>Notes<textarea name="notes" rows={3}/></label><button className="button">Create activity</button></form></details><div className="project-os-activity-list">{tasks.length===0?<div className="project-os-empty-state"><strong>No activities yet</strong><p>Create the first governed delivery activity above.</p></div>:tasks.slice(0,10).map(task=><div key={task.id}><div><strong>{task.title}</strong><small>{workspaceLabel(task.status,'task')} · {task.activity_type?.replaceAll('_',' ')||'delivery'} · {task.due_at?formatDate(task.due_at):'No due date'}</small></div><form action={setProjectActivityStatusAction}><input type="hidden" name="project_id" value={id}/><input type="hidden" name="task_id" value={task.id}/>{!['completed','cancelled'].includes(task.status)?<><button className="button secondary" name="status" value="in_progress">Start</button><button className="button" name="status" value="completed">Complete</button><button className="button secondary" name="status" value="blocked">Block</button></>:<button className="button secondary" name="status" value="open">Reopen</button>}</form></div>)}</div></section>
    </div>

    <section className="project-os-panel project-os-history"><p className="project-os-section-label">Project history</p><div>{events.length===0?<p>No project events recorded.</p>:events.slice(0,12).map(event=><div className="project-os-history-row" key={event.id}><span>→</span><div><strong>{event.event_type.replaceAll('_',' ').replaceAll('.',' ')}</strong><small>{formatDate(event.created_at)}</small></div></div>)}</div></section>
  </section>;
}
