import Link from 'next/link';
import { requireUserContext } from '@/lib/auth/context';
import { createProjectDeliveryItemAction, updateProjectDeliveryItemAction } from './actions';

function date(value:unknown){if(!value)return 'No due date';const d=new Date(String(value));return Number.isNaN(d.getTime())?String(value):d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});}
function label(value:unknown){return String(value||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());}
function overdue(item:any){if(!item.due_date||['complete','cancelled'].includes(String(item.status)))return false;const due=new Date(`${String(item.due_date).slice(0,10)}T23:59:59`);return !Number.isNaN(due.getTime())&&due.getTime()<Date.now();}

export default async function ProjectDeliveryControl({projectId,closed=false}:{projectId:string;closed?:boolean}){
  const {supabase,organisationId}=await requireUserContext();
  const [itemsResult,membersResult,partnersResult,documentsResult]=await Promise.all([
    supabase.from('project_delivery_items').select('*,owner:profiles!project_delivery_items_owner_id_fkey(id,full_name,role),partner:partners!project_delivery_items_partner_id_fkey(id,company_name),dependency:project_delivery_items!project_delivery_items_depends_on_id_fkey(id,title,status)').eq('organisation_id',organisationId).eq('project_id',projectId).order('created_at',{ascending:true}),
    supabase.from('profiles').select('id,full_name,role').eq('organisation_id',organisationId).eq('is_active',true).order('full_name'),
    supabase.from('partners').select('id,company_name,status').eq('organisation_id',organisationId).order('company_name'),
    supabase.from('documents').select('id,reference,title,status').eq('organisation_id',organisationId).eq('project_id',projectId).order('created_at',{ascending:false}),
  ]);

  if(itemsResult.error){return <section id="delivery-control" className="vp-callout"><strong>Delivery control needs its database migration</strong><p>Apply <code>20260809215500_project_delivery_control.sql</code> to activate deliverables, milestones and dependencies. Existing Project activities continue to work.</p></section>}

  const items=itemsResult.data??[];const members=membersResult.data??[];const partners=partnersResult.data??[];const documents=documentsResult.data??[];
  const deliverables=items.filter((item:any)=>item.item_type==='deliverable');const milestones=items.filter((item:any)=>item.item_type==='milestone');const dependencies=items.filter((item:any)=>item.item_type==='dependency');
  const open=items.filter((item:any)=>!['complete','cancelled'].includes(item.status));const overdueItems=open.filter(overdue);const blocked=open.filter((item:any)=>item.status==='blocked');const awaitingReview=open.filter((item:any)=>['internal_review','client_review'].includes(item.status)||item.internal_review_status==='changes_required'||item.client_review_status==='changes_required');

  const renderItem=(item:any)=><article id={`delivery-item-${item.id}`} className="vp-row" key={item.id}>
    <div style={{minWidth:0}}><strong>{item.title}</strong><p>{label(item.item_type)} · {item.owner?.full_name||'Unassigned'}{item.partner?.company_name?` · ${item.partner.company_name}`:''}</p><small>{item.due_date?`Due ${date(item.due_date)}`:'No due date'}{item.revision?` · Rev ${item.revision}`:''}{item.dependency?` · Depends on ${item.dependency.title}`:''}</small></div>
    <div className="vp-row-status">{overdue(item)?'Overdue':label(item.status)}</div>
    <div><small>Internal</small><strong style={{display:'block'}}>{label(item.internal_review_status)}</strong><small>Client</small><strong style={{display:'block'}}>{label(item.client_review_status)}</strong></div>
    <details className="vp-disclosure"><summary>Update</summary><form action={updateProjectDeliveryItemAction} className="stack" style={{paddingTop:14}}><input type="hidden" name="project_id" value={projectId}/><input type="hidden" name="item_id" value={item.id}/><label>Status<select name="status" defaultValue={item.status}><option value="not_started">Not started</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="internal_review">Internal review</option><option value="ready_to_issue">Ready to issue</option><option value="client_review">Client review</option><option value="complete">Complete</option><option value="cancelled">Cancelled</option></select></label><div className="grid gap-4 md:grid-cols-2"><label>Owner<select name="owner_id" defaultValue={item.owner_id||''}><option value="">Unassigned</option>{members.map((member:any)=><option key={member.id} value={member.id}>{member.full_name||member.role}</option>)}</select></label><label>Partner<select name="partner_id" defaultValue={item.partner_id||''}><option value="">No partner</option>{partners.map((partner:any)=><option key={partner.id} value={partner.id}>{partner.company_name}</option>)}</select></label><label>Due date<input type="date" name="due_date" defaultValue={item.due_date?String(item.due_date).slice(0,10):''}/></label><label>Revision<input name="revision" defaultValue={item.revision||''}/></label><label>Internal review<select name="internal_review_status" defaultValue={item.internal_review_status}><option value="not_required">Not required</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="changes_required">Changes required</option></select></label><label>Client review<select name="client_review_status" defaultValue={item.client_review_status}><option value="not_required">Not required</option><option value="pending">Pending</option><option value="accepted">Accepted</option><option value="changes_required">Changes required</option></select></label></div><label>Notes<textarea name="notes" rows={2} defaultValue={item.notes||''}/></label><button className="button">Save delivery item</button></form></details>
  </article>;

  return <section id="delivery-control" className="stack" style={{gap:16}}>
    <div className="vp-compact-metrics"><div className="vp-metric"><span>Open items</span><strong>{open.length}</strong></div><div className="vp-metric"><span>Overdue</span><strong>{overdueItems.length}</strong></div><div className="vp-metric"><span>Blocked</span><strong>{blocked.length}</strong></div><div className="vp-metric"><span>Needs review</span><strong>{awaitingReview.length}</strong></div></div>

    {(overdueItems.length||blocked.length||awaitingReview.length)?<div className="vp-callout"><strong>Delivery needs attention</strong><p>{overdueItems.length} overdue · {blocked.length} blocked · {awaitingReview.length} awaiting or returned from review.</p></div>:items.length?<div className="vp-callout"><strong>Delivery is on track</strong><p>No overdue, blocked or review-return items currently need attention.</p></div>:null}

    <div className="grid gap-4 lg:grid-cols-3"><div><p className="vp-label">Deliverables</p><h3>{deliverables.length} outputs</h3></div><div><p className="vp-label">Milestones</p><h3>{milestones.length} checkpoints</h3></div><div><p className="vp-label">Dependencies</p><h3>{dependencies.length} constraints</h3></div></div>

    {items.length?<div className="vp-list">{items.map(renderItem)}</div>:<div className="vp-empty"><strong>No delivery plan yet</strong><p>Add the outputs, checkpoints and dependencies that define this Project's delivery.</p></div>}

    {!closed?<details className="vp-disclosure"><summary>+ Add deliverable, milestone or dependency</summary><form action={createProjectDeliveryItemAction} className="stack" style={{paddingTop:16}}><input type="hidden" name="project_id" value={projectId}/><div className="grid gap-4 md:grid-cols-2"><label>Type<select name="item_type" defaultValue="deliverable"><option value="deliverable">Deliverable</option><option value="milestone">Milestone</option><option value="dependency">Dependency</option></select></label><label>Title<input name="title" required/></label><label>Owner<select name="owner_id" defaultValue=""><option value="">Unassigned</option>{members.map((member:any)=><option key={member.id} value={member.id}>{member.full_name||member.role}</option>)}</select></label><label>Execution partner<select name="partner_id" defaultValue=""><option value="">No partner</option>{partners.map((partner:any)=><option key={partner.id} value={partner.id}>{partner.company_name}</option>)}</select></label><label>Due date<input name="due_date" type="date"/></label><label>Priority<select name="priority" defaultValue="normal"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="critical">Critical</option></select></label><label>Revision<input name="revision" placeholder="e.g. P01"/></label><label>Depends on<select name="depends_on_id" defaultValue=""><option value="">No dependency</option>{items.filter((item:any)=>item.status!=='cancelled').map((item:any)=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label></div><label>Description<textarea name="description" rows={2}/></label><div style={{display:'flex',gap:18,flexWrap:'wrap'}}><label style={{display:'flex',alignItems:'center',gap:8}}><input style={{width:'auto'}} type="checkbox" name="internal_review_required"/> Internal review required</label><label style={{display:'flex',alignItems:'center',gap:8}}><input style={{width:'auto'}} type="checkbox" name="client_review_required"/> Client review required</label></div><label>Linked document<select name="linked_document_id" defaultValue=""><option value="">No linked document</option>{documents.map((document:any)=><option key={document.id} value={document.id}>{document.reference} · {document.title}</option>)}</select></label><label>Notes<textarea name="notes" rows={3}/></label><button className="button">Add to delivery plan</button></form></details>:null}

    <div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Link className="button secondary" href={`/workspace/documents?project=${projectId}`}>Project documents</Link><Link className="button secondary" href={`/workspace/communications/project/${projectId}`}>Project communications</Link></div>
  </section>;
}
