import Link from 'next/link';
import { requireUserContext } from '@/lib/auth/context';
import { createProjectDeliveryItemAction, updateProjectDeliveryItemAction } from './actions';
import { actOnProjectDeliveryItemAction } from './delivery-actions';
import { ActionDialog, ContextDrawer, EvidenceRow, ProductDisclosure } from '@/components/workspace/InteractionPrimitives';

function date(value:unknown){if(!value)return 'No due date';const d=new Date(String(value));return Number.isNaN(d.getTime())?String(value):d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});}
function label(value:unknown){return String(value||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());}
function overdue(item:any){if(!item.due_date||['complete','cancelled'].includes(String(item.status)))return false;const due=new Date(`${String(item.due_date).slice(0,10)}T23:59:59`);return !Number.isNaN(due.getTime())&&due.getTime()<Date.now();}

export default async function ProjectDeliveryControl({projectId,closed=false}:{projectId:string;closed?:boolean}){
  const {supabase,organisationId}=await requireUserContext();
  const [itemsResult,membersResult,executionResult,documentsResult]=await Promise.all([
    supabase.from('project_delivery_items').select('*').eq('organisation_id',organisationId).eq('project_id',projectId).order('created_at',{ascending:true}),
    supabase.from('profiles').select('id,full_name,role').eq('organisation_id',organisationId).eq('is_active',true).order('full_name'),
    supabase.from('project_execution_assignments').select('partner_id').eq('organisation_id',organisationId).eq('project_id',projectId).maybeSingle(),
    supabase.from('documents').select('id,reference,title,status').eq('organisation_id',organisationId).eq('project_id',projectId).order('created_at',{ascending:false}),
  ]);
  if(itemsResult.error)return <section id="delivery-control" className="vp-callout"><strong>Delivery control could not be loaded</strong><p>Refresh the page. If the problem persists, use History & audit for diagnosis.</p></section>;
  if(executionResult.error)throw new Error(`Execution Partner could not be resolved: ${executionResult.error.message}`);
  const executionPartnerId=executionResult.data?.partner_id?String(executionResult.data.partner_id):'';
  const {data:executionPartner,error:executionPartnerError}=executionPartnerId?await supabase.from('partners').select('id,company_name').eq('organisation_id',organisationId).eq('id',executionPartnerId).maybeSingle():{data:null,error:null};
  if(executionPartnerError)throw new Error(`Execution Partner could not be loaded: ${executionPartnerError.message}`);

  const rawItems=itemsResult.data??[];const members=membersResult.data??[];const documents=documentsResult.data??[];
  const memberById=new Map(members.map((member:any)=>[member.id,member]));const rawItemById=new Map(rawItems.map((item:any)=>[item.id,item]));
  const documentById=new Map(documents.map((document:any)=>[document.id,document]));
  const items=rawItems.map((item:any)=>({...item,owner:item.owner_id?memberById.get(item.owner_id)||null:null,partnerName:item.partner_id&&item.partner_id===executionPartnerId?executionPartner?.company_name||'Execution Partner':item.partner_id?'Recorded Partner':null,dependency:item.depends_on_id?rawItemById.get(item.depends_on_id)||null:null,linkedDocument:item.linked_document_id?documentById.get(item.linked_document_id)||null:null}));
  const open=items.filter((item:any)=>!['complete','cancelled'].includes(item.status));const overdueItems=open.filter(overdue);const blocked=open.filter((item:any)=>item.status==='blocked');const awaitingReview=open.filter((item:any)=>['internal_review','client_review'].includes(item.status)||item.internal_review_status==='changes_required'||item.client_review_status==='changes_required');

  const actionButton=(item:any,verb:string,text:string,primary=false)=><form action={actOnProjectDeliveryItemAction}><input type="hidden" name="project_id" value={projectId}/><input type="hidden" name="item_id" value={item.id}/><input type="hidden" name="delivery_action" value={verb}/><button className={`button${primary?'':' secondary'}`} type="submit">{text}</button></form>;
  const actionControls=(item:any)=>{if(closed||['complete','cancelled'].includes(String(item.status)))return null;const status=String(item.status);const internal=String(item.internal_review_status||'not_required');const client=String(item.client_review_status||'not_required');return <div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{status==='not_started'?<>{actionButton(item,'start_work','Start work',true)}{actionButton(item,'mark_blocked','Mark blocked')}</>:null}{status==='in_progress'?<>{internal!=='not_required'?actionButton(item,'submit_internal_review','Submit for Internal Review',true):client!=='not_required'?actionButton(item,'send_to_client','Send to Client',true):actionButton(item,'complete_delivery','Complete delivery',true)}{actionButton(item,'mark_blocked','Mark blocked')}</>:null}{status==='blocked'?actionButton(item,'resolve_blocker','Resolve blocker',true):null}{status==='internal_review'?<>{actionButton(item,'approve_internally','Approve internally',true)}{actionButton(item,'request_partner_correction','Request Partner correction')}</>:null}{status==='ready_to_issue'?(client!=='not_required'?actionButton(item,'send_to_client','Send to Client',true):actionButton(item,'complete_delivery','Complete delivery',true)):null}{status==='client_review'?<>{actionButton(item,'record_client_acceptance','Record Client acceptance',true)}{actionButton(item,'request_partner_correction','Request Partner correction')}</>:null}</div>};

  const renderItem=(item:any)=><article id={`delivery-item-${item.id}`} className="vp-row" key={item.id}>
    <div style={{minWidth:0}}><strong>{item.title}</strong><p>{label(item.item_type)} · {item.owner?.full_name||'Unassigned'}{item.partnerName?` · ${item.partnerName}`:''}</p><small>{item.due_date?`Due ${date(item.due_date)}`:'No due date'}{item.dependency?` · Depends on ${item.dependency.title}`:''}</small>{actionControls(item)}</div>
    <div className="vp-row-status">{overdue(item)?'Overdue':label(item.status)}</div>
    <div><small>Review</small><strong style={{display:'block'}}>{item.status==='internal_review'?'Internal decision needed':item.status==='client_review'?'Awaiting client outcome':item.internal_review_status==='changes_required'||item.client_review_status==='changes_required'?'Correction required':item.status==='ready_to_issue'?'Cleared for issue':'No review action now'}</strong></div>
    <ContextDrawer title="Delivery item details" triggerLabel="Details" triggerTone="quiet" description="Supporting delivery context and administrative details."><div className="stack" style={{gap:12}}><EvidenceRow label="Execution Partner" value={item.partnerName||executionPartner?.company_name||'Not yet released'}/>{item.linkedDocument?<EvidenceRow label="Controlled document" value={`${item.linkedDocument.reference} · ${item.linkedDocument.title}`} meta={label(item.linkedDocument.status)}/>:null}{item.revision?<EvidenceRow label="Recorded revision" value={item.revision}/>:null}<ProductDisclosure summary="Edit administrative details"><form action={updateProjectDeliveryItemAction} className="stack" style={{paddingTop:14}}><input type="hidden" name="project_id" value={projectId}/><input type="hidden" name="item_id" value={item.id}/><input type="hidden" name="status" value={item.status}/><input type="hidden" name="internal_review_status" value={item.internal_review_status}/><input type="hidden" name="client_review_status" value={item.client_review_status}/><input type="hidden" name="partner_id" value={item.partner_id||executionPartnerId}/><div className="grid gap-4 md:grid-cols-2"><label>Owner<select name="owner_id" defaultValue={item.owner_id||''}><option value="">Unassigned</option>{members.map((member:any)=><option key={member.id} value={member.id}>{member.full_name||member.role}</option>)}</select></label><label>Due date<input type="date" name="due_date" defaultValue={item.due_date?String(item.due_date).slice(0,10):''}/></label></div><label>Notes<textarea name="notes" rows={2} defaultValue={item.notes||''}/></label><button className="button secondary">Save details</button></form></ProductDisclosure></div></ContextDrawer>
  </article>;

  return <section id="delivery-control" className="stack" style={{gap:16}}>
    {(overdueItems.length||blocked.length||awaitingReview.length)?<div className="vp-callout"><strong>Delivery needs attention</strong><p>{overdueItems.length} overdue · {blocked.length} blocked · {awaitingReview.length} awaiting or returned from review.</p></div>:null}
    {items.length?<div className="vp-list">{items.map(renderItem)}</div>:<div className="vp-empty"><strong>No delivery plan yet</strong><p>Add the outputs, checkpoints and dependencies that define this Project's delivery.</p></div>}
    {!closed?<ActionDialog title="Add to delivery plan" triggerLabel="Add delivery item" description="Create an output, checkpoint or dependency. Review policy and document linkage are optional supporting controls."><form action={createProjectDeliveryItemAction} className="stack"><input type="hidden" name="project_id" value={projectId}/><input type="hidden" name="partner_id" value={executionPartnerId}/><div className="grid gap-4 md:grid-cols-2"><label>Type<select name="item_type" defaultValue="deliverable"><option value="deliverable">Deliverable</option><option value="milestone">Milestone</option><option value="dependency">Dependency</option></select></label><label>Title<input name="title" required/></label><label>Owner<select name="owner_id" defaultValue=""><option value="">Unassigned</option>{members.map((member:any)=><option key={member.id} value={member.id}>{member.full_name||member.role}</option>)}</select></label><label>Due date<input name="due_date" type="date"/></label><label>Priority<select name="priority" defaultValue="normal"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="critical">Critical</option></select></label><label>Depends on<select name="depends_on_id" defaultValue=""><option value="">No dependency</option>{items.filter((item:any)=>item.status!=='cancelled').map((item:any)=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label></div><label>Description<textarea name="description" rows={2}/></label><ProductDisclosure summary="Review and document controls"><div className="stack" style={{paddingTop:12}}><div style={{display:'flex',gap:18,flexWrap:'wrap'}}><label style={{display:'flex',alignItems:'center',gap:8}}><input style={{width:'auto'}} type="checkbox" name="internal_review_required"/> Internal review required</label><label style={{display:'flex',alignItems:'center',gap:8}}><input style={{width:'auto'}} type="checkbox" name="client_review_required"/> Client review required</label></div><label>Linked controlled document<select name="linked_document_id" defaultValue=""><option value="">No linked document</option>{documents.map((document:any)=><option key={document.id} value={document.id}>{document.reference} · {document.title}</option>)}</select></label></div></ProductDisclosure><ProductDisclosure summary="Additional notes"><label>Notes<textarea name="notes" rows={3}/></label></ProductDisclosure><button className="button">Add to delivery plan</button></form></ActionDialog>:null}
    <div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Link className="button secondary" href={`/workspace/documents?project=${projectId}`}>Project documents</Link><Link className="button secondary" href={`/workspace/communications/project/${projectId}`}>Project communications</Link></div>
  </section>;
}