import { requireUserContext } from '@/lib/auth/context';
import { createKnowledgeAction, toggleKnowledgePinAction } from './actions';

function date(value:unknown){return new Date(String(value)).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});}

export default async function KnowledgePage({searchParams}:{searchParams?:Promise<Record<string,string|undefined>>}){
  const params=searchParams?await searchParams:{};const selected=String(params.entry||'');const {supabase,organisationId}=await requireUserContext();
  const {data:entries,error}=await supabase.from('knowledge_entries').select('*').eq('organisation_id',organisationId).order('is_pinned',{ascending:false}).order('updated_at',{ascending:false}).limit(200);
  const list=entries||[];const current=list.find(e=>e.id===selected)||list[0]||null;
  return <section className="vp-page">
    <header className="vp-header"><div><p className="vp-kicker">Knowledge</p><h1>Save what your team learns.</h1><p className="vp-subtitle">Keep lessons, standards, client preferences, reusable scope notes and important decisions easy to find and reuse.</p></div></header>
    {params.updated?<div className="vp-callout"><strong>{params.updated}</strong></div>:null}{params.error?<div className="vp-callout"><strong>Action could not be completed</strong><p>Please review the entry and try again.</p></div>:null}{error?<div className="vp-callout"><strong>Knowledge is temporarily unavailable</strong><p>Please try again shortly.</p></div>:null}
    <div style={{display:'grid',gridTemplateColumns:'minmax(280px,.75fr) minmax(0,1.25fr)',gap:20,alignItems:'start'}}>
      <aside className="card" style={{width:'100%'}}><details className="vp-disclosure"><summary>Add knowledge</summary><form action={createKnowledgeAction} className="stack" style={{paddingTop:16}}><label>Type<select name="knowledge_type" defaultValue="lesson"><option value="lesson">Lesson learned</option><option value="decision">Decision</option><option value="standard">Standard</option><option value="scope">Reusable scope</option><option value="partner_insight">Partner insight</option><option value="client_preference">Client preference</option><option value="note">Note</option></select></label><label>Title<input name="title" required/></label><label>Summary<textarea name="summary" rows={2}/></label><label>Details<textarea name="body" rows={7} required/></label><label>Tags<input name="tags" placeholder="cad, drawing-pack, client-x"/></label><label><input type="checkbox" style={{width:'auto'}} name="is_pinned"/> Pin this entry</label><button className="button">Save entry</button></form></details><div className="vp-list" style={{marginTop:16}}>{list.map(e=><a href={`/workspace/knowledge?entry=${e.id}`} className="vp-row" key={e.id}><div><strong>{e.is_pinned?'★ ':''}{e.title}</strong><p>{e.knowledge_type.replaceAll('_',' ')} · {date(e.updated_at)}</p></div></a>)}{list.length===0?<div className="vp-empty">No knowledge entries yet.</div>:null}</div></aside>
      <section className="card" style={{width:'100%',minHeight:420}}>{current?<><div className="vp-section-title"><div><p className="vp-label">{current.knowledge_type.replaceAll('_',' ')}</p><h2>{current.title}</h2></div><form action={toggleKnowledgePinAction}><input type="hidden" name="entry_id" value={current.id}/><input type="hidden" name="pinned" value={current.is_pinned?'false':'true'}/><button className="button secondary">{current.is_pinned?'Unpin':'Pin'}</button></form></div>{current.summary?<p className="vp-subtitle">{current.summary}</p>:null}<div style={{whiteSpace:'pre-wrap',lineHeight:1.7,marginTop:24}}>{current.body}</div>{current.tags?.length?<p style={{marginTop:28}}>{current.tags.map((t:string)=><span className="vp-row-status" key={t} style={{marginRight:8}}>{t}</span>)}</p>:null}</>:<div className="vp-empty">Add your first lesson, standard or reusable decision.</div>}</section>
    </div>
  </section>;
}
