import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { signOut } from '@/app/login/actions';

export default async function WorkspaceLayout({ children }: { children: React.ReactNode }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect('/login');
  return <div className="workspace"><aside className="sidebar"><Link href="/workspace" className="brand" aria-label="Overflow Partner Workspace home">Overflow<span>Partner</span></Link><nav aria-label="Workspace" style={{display:'grid',gap:18,marginTop:30}}><Link href="/workspace">Dashboard</Link><details open><summary>Acquisition</summary><div style={{display:'grid',gap:8,padding:'10px 0 0 12px'}}><Link href="/workspace/acquisition">Prospects</Link></div></details><details open><summary>CRM</summary><div style={{display:'grid',gap:8,padding:'10px 0 0 12px'}}><Link href="/workspace/companies">Companies</Link><Link href="/workspace/contacts">Contacts</Link><Link href="/workspace/leads">Leads</Link></div></details><details open><summary>Engineering</summary><div style={{display:'grid',gap:8,padding:'10px 0 0 12px'}}><Link href="/workspace/leads">Technical Intake</Link><Link href="/workspace/partners">Partners</Link><Link href="/workspace/partner-quotes">Partner RFQs & Quotes</Link></div></details><details open><summary>Commercial</summary><div style={{display:'grid',gap:8,padding:'10px 0 0 12px'}}><Link href="/workspace/commercial-reviews">Commercial Review</Link><Link href="/workspace/quotes">Client Quotes</Link></div></details><details open><summary>Delivery</summary><div style={{display:'grid',gap:8,padding:'10px 0 0 12px'}}><Link href="/workspace/projects">Projects</Link><Link href="/workspace/documents">Documents</Link></div></details><details><summary>Administration</summary><div style={{display:'grid',gap:8,padding:'10px 0 0 12px'}}><Link href="/workspace/tasks">Tasks</Link><Link href="/workspace/activity">Activity</Link><Link href="/workspace/users">Users</Link></div></details></nav><form action={signOut} style={{marginTop:36}}><button className="button secondary" type="submit">Sign out</button></form></aside><main className="content">{children}</main></div>;
}
