import Link from 'next/link';
import { requireUserContext } from '@/lib/auth/context';
import { createDocumentRevisionAction, withdrawControlledDocumentAction } from '@/app/workspace/documents/control-actions';
import { ProductEmptyState, ProductMetric, ProductMetrics, ProductNotice, ProductPageHeader, ProductSectionHeader, ProductStatus, type ProductTone } from '@/components/workspace/ProductUI';

type RegistryDocument={id:string;document_type:string;reference:string;title:string;status:string;version:number;created_at:string;updated_at:string|null;lead_id:string|null;project_id:string|null;revision_code?:string|null;issue_purpose?:string|null;control_state?:string|null;is_current_revision?:boolean|null;supersedes_document_id?:string|null;superseded_by_document_id?:string|null};
type IssueRecord={id:string;document_id:string;revision_code:string;issue_sequence:number;purpose:string;recipient_name:string|null;recipient_email:string|null;issued_at:string};
type Props={leadId?:string|null;projectId?:string|null};
function canonicalDocumentSlug(value:string){const aliases:Record<string,string>={client_quote:'client-quote',client_requirements:'client-requirements',scope_of_work:'scope-of-work',statement_of_work:'statement-of-work',commercial_approval:'commercial-approval',partner_technical_assessment_report:'partner-technical-assessment-report',vendor_safe_package:'vendor-safe-package',handover_pack:'handover-pack',completion_report:'completion-report',document_register:'document-register'};return aliases[value]||value.replaceAll('_','-')}
function openUrl(document:RegistryDocument){const context=document.project_id?`project=${document.project_id}`:`case=${document.lead_id}`;return `/workspace/documents/templates/${canonicalDocumentSlug(document.document_type)}?${context}&document_record=${document.id}`}
function revision(document:RegistryDocument){return document.revision_code||`P${String(Math.max(1,Number(document.version||1))).padStart(2,'0')}`}
function state(document:RegistryDocument){return document.control_state||document.status.replaceAll('_',' ')}
function formatDate(value:string){return new Intl.DateTimeFormat('en-GB',{dateStyle:'medium'}).format(new Date(value))}
function tone(document:RegistryDocument):ProductTone{const current=state(document).toLowerCase();if(['issued','published','approved'].includes(current)||['issued','published','approved'].includes(document.status))return 'complete';if(['superseded','withdrawn'].includes(current))return 'neutral';if(['changes requested','changes_requested'].includes(current)||document.status==='changes_requested')return 'attention';if(['review','in review','in_review','signed'].includes(current)||['in_review','signed'].includes(document.status))return 'waiting';return 'active'}

export default async function DocumentEngineIndex({leadId,projectId}:Props){
  const {supabase,organisationId}=await requireUserContext();
  const contextType=projectId?'project':leadId?'case':null;const contextId=projectId||leadId||null;
  let query=supabase.from('documents').select('id,document_type,reference,title,status,version,created_at,updated_at,lead_id,project_id,revision_code,issue_purpose,control_state,is_current_revision,supersedes_document_id,superseded_by_document_id').eq('organisation_id',organisationId).order('created_at',{ascending:false});
  if(projectId)query=query.eq('project_id',projectId);else if(leadId)query=query.eq('lead_id',leadId);
  const {data,error}=await query;const documents=(data||[]) as RegistryDocument[];const ids=documents.map(item=>item.id);let issues:IssueRecord[]=[];
  if(ids.length){const issueResult=await supabase.from('document_issue_records').select('id,document_id,revision_code,issue_sequence,purpose,recipient_name,recipient_email,issued_at').eq('organisation_id',organisationId).in('document_id',ids).order('issued_at',{ascending:false});if(!issueResult.error)issues=(issueResult.data||[]) as IssueRecord[];}
  const current=documents.filter(d=>d.is_current_revision!==false&&state(d)!=='superseded'&&state(d)!=='withdrawn');const historical=documents.filter(d=>!current.includes(d));
  const review=current.filter(d=>['draft','in_review','changes_requested','signed','working','review'].includes(String(d.status))||['working','review'].includes(state(d))).length;const issued=current.filter(d=>['issued','published'].includes(d.status)||state(d)==='issued').length;
  const backHref=contextType&&contextId?(contextType==='project'?`/workspace/projects/${contextId}`:`/workspace/leads/${contextId}`):undefined;

  return <section className="vp-page document-registry">
    <ProductPageHeader eyebrow="Operations · Document control" title={contextType?'Controlled documents':'Document register'} description={contextType?'Current revisions, approvals, controlled issues and historical revisions attached to this operating record.':'The current revision of every controlled document, its review state, issue history and superseded lineage in one register.'} backHref={backHref} backLabel={contextType==='project'?'Back to Project':'Back to Case'} actions={contextType?<Link className="button secondary" href="/workspace/documents">Global register</Link>:undefined}/>
    <ProductMetrics label="Document control summary">
      <ProductMetric label="Current revisions" value={current.length} detail="Valid working set" />
      <ProductMetric label="Needs review" value={review} detail="Draft, review or changes requested" tone={review?'waiting':'complete'} />
      <ProductMetric label="Issued" value={issued} detail="Controlled releases" tone={issued?'complete':'neutral'} />
      <ProductMetric label="Historical" value={historical.length} detail="Superseded or withdrawn revisions" />
    </ProductMetrics>

    {error?<ProductNotice title="Document control unavailable" tone="blocked"><p>{error.message}</p><p>Confirm the document-control migration is active before continuing.</p></ProductNotice>:null}
    {!error&&documents.length===0?<ProductEmptyState title={contextType?`No controlled documents for this ${contextType}`:'No controlled documents yet'} description="Documents enter this register automatically when they are created from the operating workflow." action={backHref?<Link className="button" href={backHref}>Return to operating record</Link>:<><Link className="button" href="/workspace/leads">Open Cases</Link> <Link className="button secondary" href="/workspace/projects">Open Projects</Link></>}/>:null}

    {current.length?<Register title="Current revisions" description="The revision currently valid for work, review or issue." documents={current} current/>:null}
    {historical.length?<details className="vp-disclosure"><summary>Historical revisions · {historical.length}</summary><div style={{paddingTop:14}}><Register title="Revision history" description="Superseded or withdrawn revisions retained for audit and traceability." documents={historical}/></div></details>:null}

    {issues.length?<section className="product-panel"><ProductSectionHeader eyebrow="Issue history" title="Controlled releases" meta={`${issues.length} issue record${issues.length===1?'':'s'}`}/><div className="document-registry__table-scroll"><table><thead><tr><th>Document</th><th>Revision</th><th>Issue</th><th>Purpose</th><th>Recipient</th><th>Issued</th></tr></thead><tbody>{issues.map(issue=>{const doc=documents.find(d=>d.id===issue.document_id);return <tr key={issue.id}><td><strong>{doc?.reference||'Document'}</strong><small>{doc?.title}</small></td><td>{issue.revision_code}</td><td>#{issue.issue_sequence}</td><td>{issue.purpose.replaceAll('_',' ')}</td><td>{issue.recipient_name||issue.recipient_email||'Controlled release'}</td><td>{formatDate(issue.issued_at)}</td></tr>})}</tbody></table></div></section>:null}
  </section>;
}

function Register({title,description,documents,current=false}:{title:string;description:string;documents:RegistryDocument[];current?:boolean}){
  return <section className="product-panel document-registry__table-wrap"><ProductSectionHeader eyebrow="Document register" title={title} meta={`${documents.length} document${documents.length===1?'':'s'}`}/><p style={{margin:'-4px 0 12px',color:'var(--saas-muted)',fontSize:11}}>{description}</p><div className="document-registry__table-scroll"><table><thead><tr><th>Document number</th><th>Document</th><th>Revision</th><th>Control state</th><th>Purpose</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{documents.map(document=><tr id={`document-${document.id}`} key={document.id}><td><strong>{document.reference}</strong></td><td><span>{document.title}</span><small>{canonicalDocumentSlug(document.document_type).replaceAll('-',' ')}</small></td><td><strong>{revision(document)}</strong><small>v{document.version}</small></td><td><ProductStatus tone={tone(document)}>{state(document).replaceAll('_',' ')}</ProductStatus></td><td>{(document.issue_purpose||'internal').replaceAll('_',' ')}</td><td>{formatDate(document.updated_at||document.created_at)}</td><td><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link className="button secondary" href={openUrl(document)}>Open</Link>{current&&['signed','approved','issued','published'].includes(document.status)?<form action={createDocumentRevisionAction}><input type="hidden" name="document_id" value={document.id}/><button className="button secondary" type="submit">New revision</button></form>:null}{current&&['approved','issued','published'].includes(document.status)?<details className="vp-disclosure" style={{minWidth:170}}><summary>Withdraw</summary><form action={withdrawControlledDocumentAction} className="stack" style={{paddingTop:10}}><input type="hidden" name="document_id" value={document.id}/><label>Reason<textarea name="reason" rows={2} required/></label><button className="button secondary" type="submit">Withdraw revision</button></form></details>:null}</div></td></tr>)}</tbody></table></div></section>
}
